Translate DiagnosticsSystemGettingStarted.md
HoloLabInc/MixedRealityToolkit-Unity pull request #12
Opened 2019-08-30 03:14 UTC by cindychen0204

DiagnosticsSystemGettingStarted.md　の日本語訳

2019-08-30 03:42 UTC, tarukosu reviewed
コメントしました！

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +- Diagnostics API documentation
変更されちゃっている

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +> ビルドとデプロイの手順を必要とせずにアプリケーションを開発しながら Unity の Play モードを使用することは可能ですが、ターゲットハードウェアとプラットフォーム上で実行されているコンパイル済みアプリケーションを使用して診断システムの結果を評価することが重要です。
> ビルドとデプロイの手順を必要とせずにアプリケーションを開発しながら Unity の Play モードを使用することは可能ですが

アプリケーションを開発する際、ビルドとデプロイの手順が必要ない Unity の Play モードを利用することも可能ですが、

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +> 診断システムは、製品開発サイクル全体を通じて有効にすることを_**強く**_、最終バージョンをビルドしてリリースする前の最後の変更として無効にすることをお勧めします。
> 診断システムは、製品開発サイクル全体を通じて有効にすることを_**強く**_、最終バージョンをビルドしてリリースする前の最後の変更として無効にすることをお勧めします。

```
診断システムは、製品開発サイクル全体を通じて有効にし、最終バージョンをビルドしてリリースする前の最後の変更として無効にすることを **_強く_** お勧めします。
```

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +1. [有効にする](#診断を有効に) 診断システム
`[診断を有効にする](#診断を有効に)`

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +2. [設定する](#診断の設定オプション) 診断オプション
`[診断のオプションを設定する](#診断のオプションを設定する)`

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +1. Hierarchy で MixedRealityToolkit オブジェクトを選択します。
Hierarchy
-> シーンヒエラルキー

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +2. Inspector を [Diagnostics System] セクションに移動し、[Enable] にチェックを入れます。
インスペクターで「Diagnostics System」セクションに移動し、「Enable」にチェックを入れます。

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +3. 診断システムの実行を選択する
実行 -> 実装

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +![診断システムの導入を選択する](../../Documentation/Images/Diagnostics/DiagnosticsSelectSystemType.png)
導入 -> 実装

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +### 診断の設定オプション
診断のオプションを設定する

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +診断システムは、設定プロファイルを使用して、表示するコンポーネントを指定し、その設定を構成します。使用可能なコンポーネント設定の詳細については、[診断システムの設定](../../Documentation/Diagnostics/ConfiguringDiagnostics.md)を参照してください。
診断システムは、設定プロファイルを使用して、表示するコンポーネントを指定し、それらの設定を行います。

2019-08-30 03:42 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +診断システムを必要なオプションで設定すると、プロジェクトをターゲットプラットフォームにビルド、デプロイできます。
診断システムが望ましいオプションで設定されていれば、

2019-08-30 03:44 UTC, cindychen0204 commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +![診断システムの導入を選択する](../../Documentation/Images/Diagnostics/DiagnosticsSelectSystemType.png)
実装か導入か結構悩みました💦

2019-08-30 03:44 UTC, cindychen0204 commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +- Diagnostics API documentation
ちなみにこれはどういう意味でしょうか？

2019-08-30 03:44 UTC, cindychen0204 commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +- Diagnostics API documentation
(xref:Microsoft.MixedReality.Toolkit.Diagnostics)

2019-08-30 03:48 UTC, cindychen0204 commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +> 診断システムは、製品開発サイクル全体を通じて有効にすることを_**強く**_、最終バージョンをビルドしてリリースする前の最後の変更として無効にすることをお勧めします。
でも、原文を見ると、製品開発サイクル全体を通じて有効にすることを強く勧められているみたいです

2019-08-30 03:50 UTC, cindychen0204 commented
返信しました！

2019-08-30 04:01 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +> 診断システムは、製品開発サイクル全体を通じて有効にすることを_**強く**_、最終バージョンをビルドしてリリースする前の最後の変更として無効にすることをお勧めします。
ごめん、ちょっとよくわからないです

2019-08-30 04:03 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +- Diagnostics API documentation
https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#using-cross-reference
これかな

2019-08-30 04:04 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +1. [診断を有効にする](#診断を有効に) 診断システム
診断システム　は消してください！

2019-08-30 04:05 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +2. [診断のオプションを設定する](#診断のオプションを設定する) 診断オプション
診断システム　は消してください！

2019-08-30 04:05 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +2. [診断のオプションを設定する](#診断のオプションを設定する) 診断オプション
診断オプション　も

2019-08-30 04:05 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +2. [診断のオプションを設定する](#診断のオプションを設定する) 診断オプション
`
2. [診断のオプションを設定する](#診断のオプションを設定する) 診断オプション
`
->
`
2. [診断のオプションを設定する](#診断のオプションを設定する)
`

2019-08-30 04:29 UTC, tattichan commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +> 診断システムは、製品開発サイクル全体を通じて有効にすることを_**強く**_、最終バージョンをビルドしてリリースする前の最後の変更として無効にすることをお勧めします。
たるこすさんの訳でいいとおもいます

2019-08-30 04:29 UTC, tattichan commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +> 診断システムは、製品開発サイクル全体を通じて有効にすることを_**強く**_、最終バージョンをビルドしてリリースする前の最後の変更として無効にすることをお勧めします。
たるこすさんの訳でいいとおもいます

2019-08-30 04:30 UTC, decoc requested changes

2019-08-30 04:30 UTC, tattichan commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +診断システムは、MixedRealityToolkit オブジェクト (または別のサービスレジストラコンポーネント (service registrar component)) コンポーネントによって管理されます。
サービス登録コンポーネント

2019-08-30 04:35 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +診断システムは、MixedRealityToolkit オブジェクト (または別のサービスレジストラコンポーネント (service registrar component)) コンポーネントによって管理されます。
ここも xref 消えちゃってるね

2019-08-30 04:36 UTC, tarukosu commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +診断システムは、MixedRealityToolkit オブジェクト (または別のサービスレジストラコンポーネント (service registrar component)) コンポーネントによって管理されます。
`
[サービス登録 (service registar)](xref:Microsoft.MixedReality.Toolkit.IMixedRealityServiceRegistrar) コンポーネント 
`

2019-08-30 08:53 UTC, cindychen0204 commented
修正しました！

2019-09-05 05:39 UTC, tattichan commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +### 診断を有効に
診断を有効にする

2019-09-05 05:44 UTC, tattichan commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +## 参考に
参考

2019-09-05 05:44 UTC, tattichan commented on Documentation.ja/Diagnostics/DiagnosticsSystemGettingStarted.md
> +次の手順では、MixedRealityToolkit オブジェクトの使用を想定しています。他のサービスレジストラに必要な手順は異なる場合があります。
他の

2019-09-06 18:23 UTC, decoc approved these changes

2019-09-08 00:23 UTC, merged