ConfiguringDiagnostics.md　の日本語訳
HoloLabInc/MixedRealityToolkit-Unity pull request #14
Opened 2019-08-30 03:37 UTC by cindychen0204

ConfiguringDiagnostics.md　の日本語訳

2019-08-30 04:40 UTC, tarukosu commented
@tattichan 
プロファイラの項目などの説明だと、英語を前に持ってきたほうがいいと思うんだけど、どう思いますか？

Show Profiler （プロファイラの表示）

のような感じで


![image](https://user-images.githubusercontent.com/4415085/63993454-84968500-cb2b-11e9-9029-a965d1136d3d.png)

2019-08-30 04:41 UTC, decoc requested changes

2019-08-30 04:41 UTC, tattichan commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +# 診断システムの構成
診断システム (Diagnostics System) の構成

Write Preview

2019-08-30 04:41 UTC, tattichan commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +- [一般的な設定](#一般的な設定)
一般設定 (General Settings)

2019-08-30 04:41 UTC, tattichan commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +## 一般的な設定
一般設定 (General Settings)

2019-08-30 04:41 UTC, tattichan commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +### 診断を表示
診断の表示

2019-08-30 04:41 UTC, tattichan commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +診断システムに設定された診断オプションを表示するかどうかを示します。
診断システムが設定された診断オプションを表示するかどうかを示します。

2019-08-30 04:41 UTC, tattichan commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +プロファイラウィンドウを固定するビューポート (view port) のどの部分に固定するかを設定します。デフォルト値は[下中央]です。
[]はどこからきたの？

2019-08-30 04:41 UTC, tattichan commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +ビューポート (view port) の中心からビジュアルプロファイラを配置するまでのオフセット。オフセットは[ウィンドウアンカー (Window Anchor)](#ウィンドウアンカー (Window Anchor))の方向に向けます。
オフセットは[ウィンドウアンカー (Window Anchor)](#ウィンドウアンカー (Window Anchor))の方向です。

2019-08-30 04:41 UTC, tattichan commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +## 参照に
参考

2019-08-30 04:44 UTC, tarukosu reviewed
プロファイラかプロファイラーか

2019-08-30 04:44 UTC, tarukosu commented on Documentation.ja/Diagnostics/ConfiguringDiagnostics.md
> +プロファイラウィンドウを固定するビューポート (view port) のどの部分に固定するかを設定します。デフォルト値は[下中央]です。
プロファイラウィンドウをビューポート (view port) のどの部分に固定するかを設定します。

2019-08-30 05:49 UTC, tattichan commented
> @tattichan
> プロファイラの項目などの説明だと、英語を前に持ってきたほうがいいと思うんだけど、どう思いますか？
> 
> Show Profiler （プロファイラの表示）
> 
> のような感じで
> 
> ![image](https://user-images.githubusercontent.com/4415085/63993454-84968500-cb2b-11e9-9029-a965d1136d3d.png)

同意です！

2019-08-30 06:40 UTC, tattichan commented
> プロファイラかプロファイラーか

プロファイラ　かな（宗教）

2019-08-30 08:46 UTC, cindychen0204 commented
修正しました！

2019-09-05 05:45 UTC, decoc approved these changes

2019-09-05 09:59 UTC, merged