visualprofiler.md 日本語訳
HoloLabInc/MixedRealityToolkit-Unity pull request #15
Opened 2019-08-30 10:18 UTC by cindychen0204

2019-08-30 12:56 UTC, decoc requested changes

2019-08-30 12:56 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +アプリケーションの開発中は、ビジュアルプロファイラが現在シーンと関係性のあるデータを表示するので、シーンの複数の部分に注目してください。
関係性のある→関連のある

2019-08-30 12:56 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +## ビジュアルプロファイラ (Visual Profiler) のカスタマイズ
書き方統一できてない

2019-08-30 12:56 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +アプリケーションを使用する場合は、メモリの合計使用量を探します。主な指標は：メモリ制限の近い、使用状況の急激な変化です。
主な指標に、メモリ使用制限の近さと使用状況の急激な変化を含んでいます。

2019-08-30 12:56 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +メモリ使用率表示を使用すると、現在のビューがアプリケーションのメモリ消費に与える影響を簡易に理解できます。
容易に理解できます。

2019-08-30 12:56 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +フレームレートの右側には、CPU に費やされるフレーム時間 (ミリ秒単位)です。前述の目標フレームレートを実現するために、アプリケーションはフレームごとに次の時間を費やすことができます。
右側は

2019-08-30 12:56 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +フレームレートの右側には、CPU に費やされるフレーム時間 (ミリ秒単位)です。前述の目標フレームレートを実現するために、アプリケーションはフレームごとに次の時間を費やすことができます。
アプリケーションがフレームごとに費やすことのできる時間は以下の通りです。

2019-08-30 12:56 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +特定のプラットフォームとハードウェア構成は、達成可能なフレームレートの最大値で重要な役割を果たします。一般的にターゲット値の例は以下です：
以下です→次の通りです

2019-08-30 14:55 UTC, cindychen0204 commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +## ビジュアルプロファイラ (Visual Profiler) のカスタマイズ
## Visual Profiler (ビジュアルプロファイラ) のカスタマイズ
にします

2019-08-30 14:55 UTC, cindychen0204 commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +## ビジュアルプロファイラ (Visual Profiler) のカスタマイズ
## Visual Profiler (ビジュアルプロファイラ) のカスタマイズ

2019-08-30 14:55 UTC, cindychen0204 reviewed
修正しました！

2019-09-08 04:21 UTC, decoc requested changes

2019-09-08 04:21 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +ビジュアルプロファイラ (Visual Profiler) は、Mixed Reality アプリケーションのパフォーマンスを観察できる、便利な機能を提供します。プロファイラーは、以下の Mixed Reality Toolkit プラットフォームでサポートされています：
プロファイラー → プロファイラ

2019-09-08 04:21 UTC, tattichan commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +アプリケーションの開発中は、ビジュアルプロファイラが現在シーンと関連のあるデータを表示するので、シーンの複数の部分に注目してください。
表示するため、

2019-09-10 14:47 UTC, cindychen0204 commented
修正しましたー！

2019-09-12 13:38 UTC, decoc requested changes

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +# ビジュアルプロファイラ (Visual Profiler) を使用する
プロファイラー

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +ビジュアルプロファイラの見た目と動きは、診断システムプロファイルを通じてカスタマイズできます。詳細については、「診断システム (Diagnostic System) の構成」(ConfiguringDiagnostics.md) を参照してください。
プロファイラ－

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +## Visual Profiler (ビジュアルプロファイラ) のカスタマイズ
プロファイラ－

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +![ビジュアルプロファイラフレーム グラフ](../../Documentation/Images/Diagnostics/VisualProfilerMemory.png)
プロファイラー

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +![ビジュアルプロファイラフレーム グラフ](../../Documentation/Images/Diagnostics/VisualProfilerMissedFrames.png)
プロファイラー

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +ビジュアルプロファイラインターフェイスには、次のコンポーネントが含まれます。
プロファイラー

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +![ビジュアルプロファイラ インターフェイス](../../Documentation/Images/Diagnostics/VisualProfiler.png)
プロファイラー

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +## Visual Profiler Interface (ビジュアルプロファイラインターフェイス)
プロファイラー

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +アプリケーションの開発中は、ビジュアルプロファイラが現在シーンと関連のあるデータを表示するため、シーンの複数の部分に注目してください。
プロファイラー

2019-09-12 13:38 UTC, decoc commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +ビジュアルプロファイラ (Visual Profiler) は、Mixed Reality アプリケーションのパフォーマンスを観察できる、便利な機能を提供します。プロファイラは、以下の Mixed Reality Toolkit プラットフォームでサポートされています：
プロファイラー

2019-09-18 01:36 UTC, cindychen0204 commented
修正しました！

2019-09-18 02:23 UTC, tarukosu requested changes

2019-09-18 02:23 UTC, tarukosu commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +アプリケーションを使用する場合は、欠落したフレームを探します。フレームの欠落は、アプリケーションがターゲット フレームレートに達していないと、まだ最適化作業が必要な場合があることを示します。
フレームの欠落は、アプリケーションがターゲット フレームレートに達していないと、まだ最適化作業が必要な場合があることを示します。
ー＞
フレームの欠落は、アプリケーションがターゲット フレーム レートに達しておらず、最適化の作業が必要かもしれないことを示しています。

2019-09-18 02:23 UTC, tarukosu commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +フレームグラフは、アプリケーション フレームレート履歴のグラフを提供します。
フレーム レート

2019-09-18 02:23 UTC, tarukosu commented on Documentation.ja/Diagnostics/UsingVisualProfiler.md
> +ビジュアル プロファイラーの見た目と動きは、診断システム プロファイルを通じてカスタマイズできます。詳細については、「診断システム (Diagnostic System) の構成」(ConfiguringDiagnostics.md) を参照してください。
[診断システム (Diagnostic System) の構成]

2019-09-18 02:37 UTC, cindychen0204 commented
修正しました。

2019-09-18 02:40 UTC, tarukosu approved these changes
OK です！

2019-09-18 02:43 UTC, tarukosu commented
@tattichan レビュー終わりました

2019-09-18 15:55 UTC, merged