Profiles翻訳
HoloLabInc/MixedRealityToolkit-Unity pull request #18
Opened 2019-09-04 05:42 UTC by holohiko

## Overview

## Changes
- Fixes: # .

## Verification
> This optional section is a place where you can detail the specific type of verification 
> you want from reviewers. For example, if you want reviewers to checkout the PR locally
> and validate the functionality of specific scenarios, provide instructions
> on the specific scenarios and what you want verified.
>
> If there are specific areas of concern or question feel free to highlight them here so
> that reviewers can watch out for those issues.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

2019-09-04 05:57 UTC, decoc requested changes

2019-09-04 05:57 UTC, tattichan commented on Documentation.ja/Profiles/Profiles.md
> +例えば入力機能の設定はinput の[ Profile ](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityInputSystemProfile.asset)にまとめられてい
Unity Editor -> エディター内の

2019-09-04 05:57 UTC, tattichan commented on Documentation.ja/Profiles/Profiles.md
> +> 実行時に Profile が変更可能であるように意図されていますが、現在のところはこれは正しく動作しません- [参考](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4289)
予定ですが くらいでいいかも

2019-09-04 05:57 UTC, tattichan commented on Documentation.ja/Profiles/Profiles.md
> +  - Boundary System が無効になっています( AR には Boundary ( VR のエリア境界線)がないため)
Eye racking になってます

2019-09-04 07:54 UTC, holohiko commented on Documentation.ja/Profiles/Profiles.md
> +例えば入力機能の設定はinput の[ Profile ](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityInputSystemProfile.asset)にまとめられてい
似たようにEditorになってるところ全部「エディター」にしておきます

2019-09-04 08:08 UTC, holohiko commented on Documentation.ja/Profiles/Profiles.md
> +例えば入力機能の設定はinput の[ Profile ](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityInputSystemProfile.asset)にまとめられてい
対応しました

2019-09-04 08:08 UTC, holohiko commented on Documentation.ja/Profiles/Profiles.md
> +> 実行時に Profile が変更可能であるように意図されていますが、現在のところはこれは正しく動作しません- [参考](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4289)
対応

2019-09-04 08:08 UTC, holohiko commented on Documentation.ja/Profiles/Profiles.md
> +  - Boundary System が無効になっています( AR には Boundary ( VR のエリア境界線)がないため)
対応しました。ありがとうございます

2019-09-05 05:34 UTC, decoc approved these changes

2019-09-05 06:01 UTC, merged