Feature gettingstartedwiththemrtk md
HoloLabInc/MixedRealityToolkit-Unity pull request #2
Opened 2019-08-27 09:30 UTC by tattichan

## Overview
[MRTKのGetting Started ](https://github.com/HoloLabInc/MixedRealityToolkit-Unity/blob/feature/GettingStartedWithTheMRTK.md/Documentation/GettingStartedWithTheMRTK.md) 部分の翻訳

2019-08-27 14:21 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +# MRTKを始める
MRTK の後にスペース

2019-08-27 14:26 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +2. Assets の下から以下をダウンロードします。
markdown 記法で、1. にしておけば自動で連番がふられます

2019-08-27 14:27 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +より詳細な配布の仕組みは、[MRTKをダウンロードする](DownloadingTheMRTK.md)を参照して下さい。
MRTK のあとにスペース

2019-08-27 14:30 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +次のステップで、**MRTK のパッケージ を Unity プロジェクトへインポート** すると、インポートした時点でプロジェクトで選択されているプラットフォームに応じた変更がプロジェクトに適応されます。
次のステップ **MRTK のパッケージ を Unity プロジェクトへインポートする** では、...
みたいな感じかな

2019-08-27 14:31 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. ダウンロードした `Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage` をインポートします。「Asset -> Import Package -> Custom Package」から, .unitypackage ファイルを選択し, インポートする全ての項目がチェックされていることを確認してから、「Import」を選択し
「」にするか "" にするか、どちらがいいかな...

2019-08-27 14:32 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. ダウンロードした `Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage` をインポートします。「Asset -> Import Package -> Custom Package」から, .unitypackage ファイルを選択し, インポートする全ての項目がチェックされていることを確認してから、「Import」を選択し
あと, と 、 も統一したい

2019-08-27 14:35 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +[Hand Interaction のサンプルシーン](README_HandInteractionExamples.md) は、MRTK の様々なUXコントロールとインタラクションを公開しているため、MRTK を始めるには最適な場所です。はじめに、MRTK をインポートし、サンプルシーンを開いて、Editor でシーンを探索します。
UX の前後にスペース

2019-08-27 14:35 UTC, tattichan commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. ダウンロードした `Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage` をインポートします。「Asset -> Import Package -> Custom Package」から, .unitypackage ファイルを選択し, インポートする全ての項目がチェックされていることを確認してから、「Import」を選択し
いくつかドキュメント見ると「」ですね…

2019-08-27 14:36 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +このようなプロンプトが表示された場合は、「Import TMP essentials」 ボタンを選択します。「TMP Essentials」とは、Text Mesh プライグインを指し、MRTK のサンプルの一部はテキストレンダリングを改善するために使用しています。(詳細については、[Unity のテキスト](https://docs.microsoft.com/en-us/windows/mi
プライグイン -> プラグイン

2019-08-27 14:37 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +シーンの探索を楽しんでください！ UI コントロールの詳細については、[ハンドインタラクションのサンプルガイド](README_HandInteractionExamples.md) で学ぶことができます。また、[入力シミュレーションのドキュメント](InputSimulation/InputSimulationService.md)を読んで、MRTK のEditor ないの手の入力シミュレーシ
- Editor の前にスペース
- ない －＞ 内

2019-08-27 14:41 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +* [building blocks for UI and interactions](#UIとインタラクションのビルディングブロック) で UX コントロール について学ぶ。
UI のあとにスペース

2019-08-27 14:44 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +フレームワークが再構築されたため、Holotoolkit から Mixed Reality Toolkit v2 への直接的なアップグレードパスはありません。ただし、MRTK を HoloToolkit プロジェクトにインポートし、実装を移行することは可能です。詳細については、 [HoloToolkit to Mixed Reality Toolkit Porting Guide](../Doc
Holotoolkit -> HoloToolkit

2019-08-27 15:03 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +      ![Configure to scene](../Documentation/Images/MRTK_ConfigureScene.png)
先頭にスペースが入ってしまっている？
l. 145 まで

2019-08-27 15:04 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +## UIとインタラクションのビルディングブロック
UI の後にスペース

2019-08-28 02:01 UTC, tarukosu requested changes

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +Mixed Reality Toolkit (MRTK) は、Virtual Reality (VR) 及び Augmented Reality (AR) の Mixed Reality エクスペリエンス を構築するためのクロスプラットフォームツールキットです。
エクスペリエンスの後にスペースが入っている

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +MRTK、またはMR開発が初めての場合は、MRTKv2を使った [チュートリアルを始める](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base)をチェックすることをお勧めします。
MR, MRTKv2 の前後にスペース

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    * `Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage`
`- -> *` になってるのは lint ツールのせい？

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +次のステップ **MRTK のパッケージ を Unity プロジェクトへインポート** するでは、インポートした時点でプロジェクトで選択されているプラットフォームに応じた変更がプロジェクトに適応されます。
適応 -> 適用　かな

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +* File > Build Settings からメニューを開きます。
ここも　`- -> *` になっている

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. ダウンロードした `Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage` をインポートします。「Asset -> Import Package -> Custom Package」から, .unitypackage ファイルを選択し, インポートする全ての項目がチェックされていることを確認してから、「Import」を選択し
`, -> 、` で統一？

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. ダウンロードした `Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage` をインポートします。「Asset -> Import Package -> Custom Package」から, .unitypackage ファイルを選択し, インポートする全ての項目がチェックされていることを確認してから、「Import」を選択し
. -> 。

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. `Microsoft.MixedRealityToolkit.Unity.Examples.unitypackage` も上記と同様の手順でインポートします。examples のパッケージは、オプションであり、現在の MRTK の機能の有用なデモシーンが含まれています。
examples -> Examples のほうが良さそう

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. `Microsoft.MixedRealityToolkit.Unity.Tools.unitypackage` も Foundaiton パッケージと同様にインポートします。tools のパッケージは、オプションであり、MRTK 開発者のエクスペリエンスを向上させる、ExtensionServiceCreator などの便利なツールが含まれています。
tools -> Tools

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. Import the `Microsoft.MixedRealityToolkit.Unity.Extensions.unitypackage` も Foundaiton パッケージと同様にインポートします。 extensions パッケージは、オプションで、 MRTK の便利なオプションコンポーネントのセットを提供します。
Import the を消す

extensions -> Extensions

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +これらのオプションを適応するかは選択的ですが、推奨されています。
適用　かな？

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +* テキストのシリアライズを強制 / メタファイルの可視化 （ソース管理をする　Unity プロジェクトに推奨）。
l64, 65 で、文なのか名詞で止めるのかを統一してほしいです

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +一部のプレハブ、及びアセットには、TextMesh Pro が必要です。つまり、TextMesh Pro のパッケージをインストールし、アセットがプロジェクト内にあることが必要です。（Window -> TextMeshPro -> Import TMP Essential Resources）
半角カッコで

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +[Hand Interaction のサンプルシーン](README_HandInteractionExamples.md) は、MRTK の様々なUX コントロールとインタラクションを公開しているため、MRTK を始めるには最適な場所です。はじめに、MRTK をインポートし、サンプルシーンを開いて、Editor でシーンを探索します。
公開 -> 紹介
のほうが日本語としてわかりやすいかな？

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    ![TMP Essentials](../Documentation/Images/getting_started/MRTK_GettingStarted_TMPro.png)
スペースが入っている

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +* 右マウスを押したままにして、カメラを回転させます。
右マウスー＞マウスの右ボタン

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +* 左マウスをクリックして、ジェスチャーを切り替えます。
マウスの左ボタン

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +## In-Editor Hand Input Simulation を使ってシーンをテストする
以下では "Editor 内の入力シミュレーション" ということばを使っているので、タイトルでも入れておくと良さそう

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    ![Configure to scene](../Documentation/Images/MRTK_ConfigureScene.png)
スペースが入っているのは、lint ツールのせいっぽいね

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    シーンの階層が以下のようになります。
「ヒエラルキー」で統一する？

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    * Mixed Reality Toolkit - フレームワーク全体へ中心の設定のエントリポイントを提供します。
フレームワーク全体に対する中心的な設定のエントリポイント
とかかなぁ

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    * Playspace の下に移動した Main Camera - プレイスペースがSDKと連動してカメラを管理できるようにします。
SDK の周りにスペース

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +これで、デバイスにビルドしてデプロイする準備ができました！[MRTK のビルドとデプロイ](BuildAndDeploy.md) の手順に従ってください。
! のあとにスペース入れたほうが読みやすそう。
ページ見てみないとわからないけど。

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +| HoloLen 2 の関節式の手を含む様々な入力方法をサポートするボタンコントロール | 3D 空間でオブジェクトを操作するための標準UI | 片手、または両手でオブジェクトを操作するためのスクリプト |
UI の前にスペース

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +| 関節式の手の入力によるスクロールをサポートする2D スタイル平面 | Unity でシステムキーボードを使用するスクリプトのサンプル  | 視覚的にオブジェクトと対話可能にするためのスクリプトとテーマサポート |
2D の前にスペース

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +| 関節式の手の入力によるスクロールをサポートする2D スタイル平面 | Unity でシステムキーボードを使用するスクリプトのサンプル  | 視覚的にオブジェクトと対話可能にするためのスクリプトとテーマサポート |
> 対話可能

対話というと言葉のイメージが強いから、別の言葉が良さそう。
そのまま、インタラクションとか？

2019-08-28 02:01 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +| 直接的な手を使ったインタラクションをサポートする値を調整するためのスライダー | フルーエントデザインの要素をサポートし、パフォーマンスの良い MRTK の標準シェーダー | ソルバーを使用してオブジェクトを手の関節にアタッチする方法のデモ |
> 直接的な手を使ったインタラクションをサポートする値を調整するためのスライダー

- 直接的な手を使ったインタラクションをサポートする、値を調整するためのスライダー
- ダイレクトハンドインタラクションをサポートする、値を調整するためのスライダー

2019-08-28 02:31 UTC, tattichan commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    * `Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage`
元のファイルの書き方に引きずられていました
直します；

2019-08-28 02:33 UTC, tattichan commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +次のステップ **MRTK のパッケージ を Unity プロジェクトへインポート** するでは、インポートした時点でプロジェクトで選択されているプラットフォームに応じた変更がプロジェクトに適応されます。
なるほど・・・

https://99bako.com/1278.html

2019-08-28 02:43 UTC, tattichan commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    * `Microsoft.MixedRealityToolkit.Unity.Foundation.unitypackage`
lint の影響です
書き方に一貫性がなかったので統一しました

2019-08-28 08:50 UTC, tattichan commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    ![Configure to scene](../Documentation/Images/MRTK_ConfigureScene.png)
スペース入れないと連番崩れません？

2019-08-28 08:50 UTC, tattichan commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +    シーンの階層が以下のようになります。
あー、難しいですが、Unityがヒエラルキーを使っているのでヒエラルキーにします

2019-08-28 09:27 UTC, tattichan commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +      ![Configure to scene](../Documentation/Images/MRTK_ConfigureScene.png)
これスペース抜くと連番崩れません？

https://qiita.com/uniq/items/ad92182fc3a4a2205f89

2019-08-28 11:17 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +      ![Configure to scene](../Documentation/Images/MRTK_ConfigureScene.png)
なるほど、だから元のだと 
```
4. You will see a ...
```

になってるんだね

2019-08-29 13:31 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +* [Unity 2018.4.x、 2019.1.x or 2019.2.x](https://unity3d.com/get-unity/download/archive)
英語のところは , にしたいけど、どうなんでしょう

2019-08-29 13:39 UTC, tarukosu reviewed
こまかい修正以外は大丈夫だと思います！

2019-08-29 13:39 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +## MRTK を Unity Projectに追加する
Project の後スペース

2019-08-29 13:39 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +1. `Microsoft.MixedRealityToolkit.Unity.Extensions.unitypackage` も Foundaiton パッケージと同様にインポートします。 extensions パッケージは、オプションで、 MRTK の便利なオプションコンポーネントのセットを提供します。
Extensions

2019-08-29 13:39 UTC, tarukosu commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +| 多関節ハンド の入力によるスクロールをサポートする 2D スタイル平面 | Unity でシステムキーボードを使用するスクリプトのサンプル  | 視覚的にオブジェクトとインタラクションするためのスクリプトとテーマサポート |
ハンドの後にスペースが入っている

2019-08-29 14:52 UTC, tattichan commented on Documentation.ja/GettingStartedWithTheMRTK.md
> +* [Unity 2018.4.x、 2019.1.x or 2019.2.x](https://unity3d.com/get-unity/download/archive)
悩みますね。。。違和感っちゃ違和感。。。
ここは原文ママでいきます

2019-08-29 15:00 UTC, merged