ヘッダー、上半部の日本語訳
HoloLabInc/MixedRealityToolkit-Unity pull request #22
Opened 2019-09-05 09:50 UTC by cindychen0204

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Core パッケージは _必須_ コンポーネントであり、すべての MRTK 基盤パッケージの依存関係として使用されます。
> すべての MRTK 基盤パッケージの依存関係として使用されます。

すべての MRTK Foundation パッケージが依存しています。

日本語の読みやすさを考えて、こんな感じでどうでしょう。

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK コアパッケージには以下が含まれます。
上で Core にしてるので、ここも Core かな

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- [一般のインターフェース、クラスとデータ種類](#一般型)
共通のインターフェース、クラス、データ型

かな

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージは、オプションの Foundation、Extensions、Examples MRTK パッケージを発見し、管理するためのサポートを提供します。
Examples じゃなくて experimental （実験的な）だね

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +## 拡張機能パッケージ
他のパッケージは、そのまま英語を残してるから、ここも英語で良さそう

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +#### 一般型
共通型

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージには、他のすべてのコンポーネントで使用されるすべての共通インターフェイス、クラス、およびデータ型の定義が含まれています。定義されたインターフェイスを介して MRTK コンポーネントのみにアクセスし、プラットフォーム間で最高レベルの互換性を実現することを強くお勧めします。
> 他のすべてのコンポーネントで使用されるすべての共通インターフェイス、クラス、およびデータ型の定義が含まれています

他のすべてのコンポーネントで使用される、共通のインターフェイス、クラス、データ型のすべての定義が含まれています

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージには、他のすべてのコンポーネントで使用されるすべての共通インターフェイス、クラス、およびデータ型の定義が含まれています。定義されたインターフェイスを介して MRTK コンポーネントのみにアクセスし、プラットフォーム間で最高レベルの互換性を実現することを強くお勧めします。
プラットフォーム間で最高レベルの互換性を実現するために、定義されたインターフェイスのみを介して MRTK コンポーネントにアクセスすることを強くお勧めします。

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージには、他のすべてのコンポーネントで使用されるすべての共通インターフェイス、クラス、およびデータ型の定義が含まれています。定義されたインターフェイスを介して MRTK コンポーネントのみにアクセスし、プラットフォーム間で最高レベルの互換性を実現することを強くお勧めします。
インターフェイスとインターフェースが混ざってるね

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK のスタンダードシェーダーは MRTK によって提供される事実上すべての材料の基礎を提供する。このシェーダは非常に柔軟性が高く、MRTK がサポートされているさまざまなプラットフォームに最適化されています。最適なパフォーマンスを実現するには、アプリケーションのマテリアルで MRTK スタンダードシェーダーを使用することを強くお勧めします。
材料 -> マテリアル

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK のスタンダードシェーダーは MRTK によって提供される事実上すべての材料の基礎を提供する。このシェーダは非常に柔軟性が高く、MRTK がサポートされているさまざまなプラットフォームに最適化されています。最適なパフォーマンスを実現するには、アプリケーションのマテリアルで MRTK スタンダードシェーダーを使用することを強くお勧めします。
提供するー＞提供します

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK のスタンダードシェーダーは MRTK によって提供される事実上すべての材料の基礎を提供する。このシェーダは非常に柔軟性が高く、MRTK がサポートされているさまざまなプラットフォームに最適化されています。最適なパフォーマンスを実現するには、アプリケーションのマテリアルで MRTK スタンダードシェーダーを使用することを強くお勧めします。
`__強く__`

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +#### Unity 入力プロバイダ
Unity インプットプロバイダ (Unity Input Provider)

2019-09-06 07:49 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Unity 入力プロバイダは、ゲームコントローラ、タッチスクリーン、3D 空間マウスなどの一般的な入力デバイスにアクセスできます。
にアクセスできます

へのアクセスを提供します

2019-09-06 11:27 UTC, cindychen0204 commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Core パッケージは _必須_ コンポーネントであり、すべての MRTK 基盤パッケージの依存関係として使用されます。
同意します！

2019-09-06 11:27 UTC, cindychen0204 commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK コアパッケージには以下が含まれます。
承知です。

2019-09-06 11:28 UTC, cindychen0204 commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- [一般のインターフェース、クラスとデータ種類](#一般型)
承知です。

2019-09-06 11:33 UTC, cindychen0204 commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージは、オプションの Foundation、Extensions、Examples MRTK パッケージを発見し、管理するためのサポートを提供します。
```Mixed Reality Toolkit Core パッケージは、オプションの Foundation、Extensions、Experimental （実験的な）MRTK パッケージを発見し、管理するためのサポートを提供します```
はどうでしょう？

2019-09-06 11:33 UTC, cindychen0204 commented on Documentation.ja/Packaging/MRTK_Packages.md
> +#### Unity 入力プロバイダ
承知

2019-09-08 00:34 UTC, cindychen0204 commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージは、オプションの Foundation、Extensions、Examples MRTK パッケージを発見し、管理するためのサポートを提供します。
experimental わからない人いるかもしれないので日本語も残します。

2019-09-08 00:50 UTC, cindychen0204 commented
修正しました！

2019-09-18 00:31 UTC, tarukosu requested changes

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Foundation は、アプリケーションが Mixed Reality プラットフォーム間で共通の機能を活用できるようにするパッケージのセットです。これらのパッケージは、GitHub の [mrtk_release](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_re
ソース コード

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- [システムサービス](#システムサービス)
システム サービス

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Core パッケージは _必須_ コンポーネントであり、すべての MRTK Foundation パッケージが依存しています。。
。が二個

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- [Unity インプットプロバイダ (Unity Input Provider)](#unity-インプットプロバイダ-unity-input-provider)
インプット プロバイダー
スペースと伸ばし棒

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージには、他のすべてのコンポーネントで使用される共通のインターフェイス、クラス、データ型のすべての定義が含まれています。プラットフォーム間で最高レベルの互換性を実現するために、定義されたインターフェイスのみを介して MRTK コンポーネントにアクセスすることを _強く_ お勧めします。
`_強く_`
_ いらないんじゃない？

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MixedRealityToolkit シーン コンポーネントは、Mixed Reality Toolkit の単一の集中化されたリソースマネージャです。このコンポーネントは、プラットフォームモジュールとサービスモジュールのライフスパンをロードおよび管理し、システムが構成設定にアクセスするためのリソースを提供します。
リソース マネージャー

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MixedRealityToolkit シーン コンポーネントは、Mixed Reality Toolkit の単一の集中化されたリソースマネージャです。このコンポーネントは、プラットフォームモジュールとサービスモジュールのライフスパンをロードおよび管理し、システムが構成設定にアクセスするためのリソースを提供します。
プラットフォーム モジュール
サービス モジュール

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK のスタンダードシェーダーは MRTK によって提供される事実上すべてのマテリアルの基礎を提供します。このシェーダは非常に柔軟性が高く、MRTK がサポートされているさまざまなプラットフォームに最適化されています。最適なパフォーマンスを実現するには、アプリケーションのマテリアルで MRTK スタンダードシェーダーを使用することを強くお勧めします。
スタンダード シェーダー

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK のスタンダードシェーダーは MRTK によって提供される事実上すべてのマテリアルの基礎を提供します。このシェーダは非常に柔軟性が高く、MRTK がサポートされているさまざまなプラットフォームに最適化されています。最適なパフォーマンスを実現するには、アプリケーションのマテリアルで MRTK スタンダードシェーダーを使用することを強くお勧めします。
`_強く_`

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Unity 入力プロバイダは、ゲームコントローラ、タッチスクリーン、3D 空間マウスなどの一般的な入力デバイスにへのアクセスを提供します。
入力プロバイダ
-> インプット プロバイダ

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Unity 入力プロバイダは、ゲームコントローラ、タッチスクリーン、3D 空間マウスなどの一般的な入力デバイスにへのアクセスを提供します。
ゲーム コントローラー
タッチ スクリーン

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Unity 入力プロバイダは、ゲームコントローラ、タッチスクリーン、3D 空間マウスなどの一般的な入力デバイスにへのアクセスを提供します。
にへの
-> への

2019-09-18 00:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +### システムサービス
システム サービス

2019-09-18 01:16 UTC, cindychen0204 commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- [Unity インプットプロバイダ (Unity Input Provider)](#unity-インプットプロバイダ-unity-input-provider)
> スペースと伸ばし棒

はどういう意味でしょうか？

2019-09-18 01:23 UTC, cindychen0204 commented
修正しました！大丈夫そうでしたら下半分も送ります

2019-09-18 01:58 UTC, tarukosu commented
いったん修正分 push してもらえる？

2019-09-18 02:20 UTC, cindychen0204 commented
今Pushしました！

2019-09-18 02:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- [Unity インプット プロバイダ (Unity Input Provider)](#unity-インプット-プロバイダ-unity-input-provider)
プロバイダー

2019-09-18 02:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- [Unity インプット プロバイダ (Unity Input Provider)](#unity-インプット-プロバイダ-unity-input-provider)
二か所あるので注意

2019-09-18 02:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージには、他のすべてのコンポーネントで使用される共通のインターフェイス、クラス、データ型のすべての定義が含まれています。プラットフォーム間で最高レベルの互換性を実現するために、定義されたインターフェイスのみを介して MRTK コンポーネントにアクセスすることをお勧めします。
ごめん、「強く」はいるんだけど、もとのには _ ついてないから消していいかなっていう意味です

2019-09-18 02:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Mixed Reality Toolkit Core パッケージには、他のすべてのコンポーネントで使用される共通のインターフェイス、クラス、データ型のすべての定義が含まれています。プラットフォーム間で最高レベルの互換性を実現するために、定義されたインターフェイスのみを介して MRTK コンポーネントにアクセスすることをお勧めします。
プラットフォーム間で最高レベルの互換性を実現するために、定義されたインターフェイスのみを介して MRTK コンポーネントにアクセスすることを強くお勧めします。

2019-09-18 02:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MixedRealityToolkit シーン コンポーネントは、Mixed Reality Toolkit の単一の集中化されたリソース マネージャです。このコンポーネントは、プラットフォーム モジュールとサービス モジュールのライフスパンをロードおよび管理し、システムが構成設定にアクセスするためのリソースを提供します。
マネージャー

2019-09-18 02:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +#### Unity インプット プロバイダ (Unity Input Provider)
プロバイダー

2019-09-18 02:31 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Unity インプット プロバイダは、ゲーム コントローラ、タッチ スクリーン、3D 空間マウスなどの一般的な入力デバイスへのアクセスを提供します。
プロバイダー

2019-09-18 02:56 UTC, cindychen0204 commented
修正しました

2019-09-18 02:58 UTC, tarukosu commented
@cindychen0204
OK です！
後半部分も追加してください！

2019-09-18 04:16 UTC, cindychen0204 commented
MRTK_Packages.md 下半分の日本語訳

2019-09-18 06:05 UTC, tarukosu requested changes

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Tools パッケージには、Mixed Reality エクスペリエンスを作成するのに役立つツールが含まれています。最終的にコードがアプリケーションの一部としてリリースされません。
最終的にコードがアプリケーションの一部としてリリースされません。
->
これらのコードは、最終的にはアプリケーションの一部としてリリースされることはありません。

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +Examples パッケージには、デモ、サンプル スクリプト、および Foundation パッケージの機能を使用するサンプル シーンが含まれています。
Examples パッケージには、Foundation パッケージの機能を使用するデモ、サンプル スクリプト、およびサンプル シーンが含まれています

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +たとえば、このパッケージには、さまざまなタイプの手のインプット (多関節および非多関節) に対応するサンプル オブジェクトを含む HandInteractionExample シーン (下図) が含まれています。
手のインプット
-> ハンド インプット

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +このパッケージには、アイトラッキングデモも含まれています。ここに記載されています：[documented here](../EyeTracking/EyeTracking_ExamplesOverview.md)
アイ トラッキング デモ

詳細は[こちら](../EyeTracking/EyeTracking_ExamplesOverview.md)に記載されています。

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +一般的には、MRTK に追加される新機能は、ほぼ同じフォルダ構造と場所に従って、Examples パッケージに対応するサンプルはあります。
より一般的には、MRTK のすべての新機能について、同じフォルダ構造と場所にほぼ従って、対応するサンプルが Examples パッケージに含まれているべきです。

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +機能アセットは、Unity アセットとスクリプトとして提供される関連機能のコレクションです。これらの機能の一部：
機能の一部はこちらです：

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK 空間認識システムを使用することで、Microsoft HoloLens などのデバイスから実際の環境データにアクセスできます。
実際の
→ 実世界の

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK 入力システムを使用すると、クロスプラットフォームでの入力にアクセスできます。ユーザー アクションを指定し、ターゲット コントローラー上の最も適切なボタンと軸にそれらのアクションを割り当てることにより設定することができます。
クロス プラットフォーム

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK 入力システムを使用すると、クロスプラットフォームでの入力にアクセスできます。ユーザー アクションを指定し、ターゲット コントローラー上の最も適切なボタンと軸にそれらのアクションを割り当てることにより設定することができます。
ユーザー アクションを指定し、ターゲット コントローラー上の最も適切なボタンと軸にそれらのアクションを割り当てることにより設定することができます。
ー＞
ターゲット コントローラーの最も適切なボタンと軸に、ユーザー アクションを指定して割り当てることで設定できます。

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK 境界システムは、仮想現実 (VR) プレイスペースに関するデータを提供します。ユーザーが境界を構成しているシステムでは、床の平面、長方形のプレイスペース、トラッキング領域などを提供できます。
構成 －＞ 設定

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +MRTK 診断システムは、アプリケーション エクスペリエンス内のリアルタイムのパフォーマンス データを提供します。アプリケーションを使用する場合は、フレーム レート、プロセッサ時間、およびその他の主要なパフォーマンス メトリックを簡単に視野の中に確認できます。
アプリケーションを使用する場合は、フレーム レート、プロセッサ時間、およびその他の主要なパフォーマンス メトリックを簡単に視野の中に確認できます。

アプリケーションを使用する際、フレーム レート、プロセッサー時間、およびその他の主要なパフォーマンス指標をひと目で見ることができます。

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- 視線ターゲティング
ゲイズ ターゲティング

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +#### テレポートシステム (Teleport System)
テレポート システム

2019-09-18 06:05 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- [テレポートシステム](#テレポートシステム-teleport-system)
- [テレポート システム](#テレポート-システム-teleport-system)

2019-09-18 09:03 UTC, cindychen0204 commented
たすこすさんのコメントにより修正しました

2019-09-18 10:27 UTC, tarukosu reviewed
これで最後だと思います！

2019-09-18 10:27 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +- アイトラッキング
アイ トラッキング

2019-09-18 10:27 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +このパッケージには、アイトラッキングデモも含まれています。詳細は[こちら](../EyeTracking/EyeTracking_ExamplesOverview.md)に記載されています：
アイトラッキングデモ
-> アイ トラッキング デモ

記載されています：
-> 記載されています。

2019-09-18 10:55 UTC, cindychen0204 commented
修正しました！

2019-09-18 11:32 UTC, tarukosu commented on Documentation.ja/Packaging/MRTK_Packages.md
> +このパッケージには、アイ トラッキングデモも含まれています。詳細は[こちら](../EyeTracking/EyeTracking_ExamplesOverview.md)に記載されています。
アイ トラッキングラッキング デモ

2019-09-18 11:34 UTC, cindychen0204 commented
修正しました~~

2019-09-18 11:35 UTC, tarukosu approved these changes
OK です！

2019-09-18 11:47 UTC, merged