Doc ja/readme manipulation handler.md
HoloLabInc/MixedRealityToolkit-Unity pull request #28
Opened 2019-09-12 05:19 UTC by cindychen0204

2019-09-12 13:27 UTC, decoc requested changes
隣接した行で，訳が統一されていないのが目立ちます。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *OnManipulationStarted*: 操作が開始されたときに起動されます。
起動します。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *OnManipulationEnded*: 操作が終了すると起動します。
操作が終了した時に起動します。　上と書き方揃えた方がいい

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *OnHoverStarted*: ハンド/コントローラーが操作可能な、近くまたは遠くにホバー (hover) したときに起動します。
操作可能な物の

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *OnHoverEnded*: ハンド/コントローラーが操作可能な、近くまたは遠くにホバー (hover) を解除すると起動します。
操作可能な物の

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +Manipulation handlerは、次のイベントを提供します:
handler スペース

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Maintain rotation to user*: X/Y 軸のオブジェクトの元の回転を、ユーザに維持する
ユーザーに対するオブジェクトの元のX/Y 軸の回転を維持します

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Gravity aligned maintain rotation to user*: オブジェクトの元の回転をユーザに維持しますが、オブジェクトを垂直にします。バウンディングボックスに便利です。
ユーザーに対して元の回転を維持しますが，オブジェクトは垂直にします。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Face user*: オブジェクトが常にユーザーに直面していることを確認します。スレート (slates)/ パネルに便利です。
オブジェクトが常にユーザーを向くようにします。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Face away from user*: オブジェクトが常にユーザーの顔に向かないようにする。後ろ向きに設定されたスレート (slates)/ パネルに便利です。
オブジェクトが常にユーザーを向かないようにします。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Rotate about grab point*: 多関節ハンド/コントローラのためにのみ動作します。オブジェクトを手/コントローラーで保持しているかのように回転します。観察に役立ちます。
多関節ハンド/コントローラでのみ動作します。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Rotate about grab point*: 多関節ハンド/コントローラのためにのみ動作します。オブジェクトを手/コントローラーで保持しているかのように回転します。観察に役立ちます。
オブジェクトをハンド/コントローラー

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Rotate about grab point*: 多関節ハンド/コントローラのためにのみ動作します。オブジェクトを手/コントローラーで保持しているかのように回転します。観察に役立ちます。
観察に便利です。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +オブジェクトが片手でつかまれているときに、オブジェクトを回転させる方法を指定します。
オブジェクトが片手でつかまれているときの，

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +オブジェクトがある距離で片手/コントローラーで、つかまれているときにオブジェクトがどのように動作するかを指定します。
オブジェクトが遠くで片手のハンド/コントローラにつかまれているときに，どのように動作するかを指定します。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> -Specifies how the object will behave when it is being grabbed with one hand / controller near.
オブジェクトが近くで片手のハンド/コントローラにつかまれているときに，どのように動作するかを指定します。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Scale*: スケーリングのみ可能です。
スケーリングのみ許可されます。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Rotate*:回転のみが許可されています。
回転のみ許可されます。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Move Scale*: 移動とスケーリングが許可されています。
許可されます。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Move Rotate*:移動および回転が許可される。
許可されます。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +* *Rotate Scale*: 回転とスケーリングが可能です。
許可されます。

2019-09-12 13:27 UTC, decoc commented on Documentation.ja/README_ManipulationHandler.md
> +引っ張れる Transform。デフォルトでは、コンポーネントのオブジェクトが設定されます。
ドラッグされる Transform。

2019-09-18 04:23 UTC, cindychen0204 commented
デコシさんにコメントによる修正

2019-09-19 04:55 UTC, decoc approved these changes

2019-09-19 05:39 UTC, merged