Profiles Configuration 日本語訳
HoloLabInc/MixedRealityToolkit-Unity pull request #3
Opened 2019-08-27 09:34 UTC by cindychen0204

## Overview 
Profiles Configurationの日本語訳
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MixedRealityConfigurationGuide.html

## Changes
- Fixes: # .

issue2つ出た
本家に報告します

## Verification
> This optional section is a place where you can detail the specific type of verification 
> you want from reviewers. For example, if you want reviewers to checkout the PR locally
> and validate the functionality of specific scenarios, provide instructions
> on the specific scenarios and what you want verified.
>
> If there are specific areas of concern or question feel free to highlight them here so
> that reviewers can watch out for those issues.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

2019-08-27 12:04 UTC, decoc reviewed
feature/ProfilesConfiguration.md のようにブランチを切ってください
次回、以降で大丈夫ですｂ

2019-08-27 12:05 UTC, decoc reviewed
半角英数のあとは半角スペースを入れてください

2019-08-27 12:09 UTC, decoc requested changes
余計な空白や見出しあとの空行なしなど、markdownのフォーマットが崩れているので修正お願いします

VSCodeで作業している場合は、[Markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) などの活用を検討して下さいｖ

2019-08-27 12:14 UTC, cindychen0204 commented
ありがとうございます！

> 半角英数のあとは半角スペースを入れてください

ということはどういうことでしょうか？

2019-08-28 02:25 UTC, decoc requested changes

2019-08-28 02:25 UTC, decoc commented on Documentation.ja/ProfilesConfiguration.md
> +# Input Action Rulesプロフィール
プロファイルかプロフィールかどちらかに統一してください

2019-08-28 02:25 UTC, decoc commented on Documentation.ja/ProfilesConfiguration.md
> +# 入力システム設定
〇〇の設定だったり○○設定だったりと、統一感がないので、○○の設定に合わせませんか？

2019-08-28 02:25 UTC, decoc commented on Documentation.ja/ProfilesConfiguration.md
> +# 境界(Boundary)可視化の設定
直訳してしまうことで、意味が分からなくなってしまうものもあるので、こういった書き方は親切でいいとおもいました！他の箇所でも統一してもらえると助かります

2019-08-28 02:25 UTC, decoc commented on Documentation.ja/ProfilesConfiguration.md
> +## 注意
ここ、書き方合ってますか？
元のマークダウンと見比べてみてください＜●＞＜●＞

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Documentation/MixedRealityConfigurationGuide.md

2019-08-28 02:25 UTC, decoc commented on Documentation.ja/ProfilesConfiguration.md
> +![enter image description here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Images/MRTK_Logo_Rev.png)
ファイルパスは直リンクではなく、相対パスを指定してください。

ex) ../Documentation/Images/MRTK_Logo_Rev.png

2019-08-28 03:08 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +# Input Action Rulesプロフィール
Done!

2019-08-28 03:14 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +# 入力システム設定
Done!

2019-08-28 03:14 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +# 境界(Boundary)可視化の設定
なるほどです。入れておきます。

2019-08-28 03:35 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +# 境界(Boundary)可視化の設定
Done

2019-08-28 03:38 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +## 注意
マークダウンのシャープ記号でしょうか？
日本語単語の「注意」のことでしょうか？

2019-08-28 03:39 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +![enter image description here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Images/MRTK_Logo_Rev.png)
Done

2019-08-28 03:40 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +## 注意
注意の部分です

2019-08-28 03:45 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +## 注意
```
## 注意
```
ではなく、

```
> [!NOTE]
> Almost any profile can be swapped out at runtime, with the exception of the InputActions configuration (see later). The profiles with then automatically adapt to the new configuration / runtime environment automatically.
```

ですね。
Importantなどほかの箇所も何か所か書き方が間違っているので修正お願いします

2019-08-28 12:50 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +## 注意
dONE

2019-08-28 13:55 UTC, decoc requested changes

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> + Mixed Reality Toolkitは、ツールキットを管理するために必要な設定をできるだけ集中して書かれています(ランタイム「モノ」を除く)。
Mixed Reality Toolkit のあとにスペース

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> + Mixed Reality Toolkitは、ツールキットを管理するために必要な設定をできるだけ集中して書かれています(ランタイム「モノ」を除く)。
Mixed Reality Toolkitは、ツールキットを管理するために必要な設定を可能な限り集中化しています (ランタイムの「モノ」は除く)。

かな。

 
tattichan Member Pending

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +# Mixed Reality Toolkit 主な設定プロファイル
Mixed Reality Toolkit の主な設定プロファイル

のほうがいいですね

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +
設定プロファイル[スペース入れる](Congifuration Profile)

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +
書き方が違います

```
> [!NOTE]
> Mixed Reality Toolkit は、プロジェクトの共通のスタートポイントを常に持たせるように、デフォルトの設定画面を「ロック」しています。そして、プロジェクトの進捗に合わせて独自の設定の定義を行うことをお勧めします。MRTKの設定はプレイモード中は編集できません。
```

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkit は、プロジェクトの共通のスタートポイントを常に持たせるように、デフォルトの設定画面を「ロック」しています。そして、プロジェクトの進捗に合わせて独自の設定の定義を行うことをお勧めします。MRTKの設定はプレイモード中は編集できません。
MRTK[スペース]の設定は

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkit は、プロジェクトの共通のスタートポイントを常に持たせるように、デフォルトの設定画面を「ロック」しています。そして、プロジェクトの進捗に合わせて独自の設定の定義を行うことをお勧めします。MRTKの設定はプレイモード中は編集できません。
独自の設定の定義を行うことをお勧めします。-> 独自の設定を定義することをお勧めします。

が自然かな

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkitのすべての「デフォルト」プロファイルは、フォルダ Assets\MixedRealityToolkit.SDK\Profiles 内の SDK プロジェクトにあります。
ixed Reality Toolkit[スペース]の

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkitのすべての「デフォルト」プロファイルは、フォルダ Assets\MixedRealityToolkit.SDK\Profiles 内の SDK プロジェクトにあります。
フォルダ Assets\MixedRealityToolkit.SDK\Profiles 内の　－＞　Assets\MixedRealityToolkit.SDK\Profiles フォルダ内の

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +[!IMPORTANT]
書き方違います

```
> [!IMPORTANT]
> デフォルトの HoloLens2 の設定プロファイルは、HoloLens2 用に最適化されています.  [Profiles](../Documentation/Profiles/Profiles.html)  にご確認ください。
```

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +デフォルトの HoloLens2 の設定プロファイルは、HoloLens2 用に最適化されています.  [Profiles](../Documentation/Profiles/Profiles.html)  にご確認ください。
細かいですが、 HoloLens[スペース]2です

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +デフォルトの HoloLens2 の設定プロファイルは、HoloLens2 用に最適化されています.  [Profiles](../Documentation/Profiles/Profiles.html)  にご確認ください。
. -> 。

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +デフォルトの HoloLens2 の設定プロファイルは、HoloLens2 用に最適化されています.  [Profiles](../Documentation/Profiles/Profiles.html)  にご確認ください。
[Profiles](../Documentation/Profiles/Profiles.html)  「を」ご確認ください。

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +[!NOTE]
他のNoteと一緒
書き方違います

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +ほとんどのプロファイルは、InputActions 設定を除き、実行時に変更できます (後を参照)。プロファイルは、新しい設定/ランタイム環境に自動的に適応します。
(後を参照)　－＞　（後述）

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkit のメイン設定ページにあるこの項目では、プロジェクトの複合現実環境の既定の操作が定義されます。
複合現実環境 -> Mixed Reality 環境

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +カメラ設定では、Mixed Reality プロジェクトのカメラの設定方法を定義し、一般的なクリッピング(clipping)、品質、透明度(transparency)の設定を定義します。
かっこの前にスペース

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +カメラ設定では、Mixed Reality プロジェクトのカメラの設定方法を定義し、一般的なクリッピング(clipping)、品質、透明度(transparency)の設定を定義します。
品質はクオリティとそのままカタカナで書いた方が分かりやすいかも

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +複合現実プロジェクトは、デフォルトの設定で、すべての入力イベントを連結するための堅牢で十分にトレーニングされてきた入力システムを提供します。
複合現実プロジェクト　-> Mixed Reality プロジェクト

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +# エクスペリエンスの設定
エクスペリエンスの設定 (Experience settings) のように書いてあると助かります
他のカメラの設定なども同じように書いてもらえますか？？('ω')

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +MRTKが提供する入力システムの裏には、マルチプラットフォーム/複合現実フレームワークの複雑さを抽象化するために必要な複雑な絡み合わせを駆動し、管理するのに役立ちます。
MRTK[スペース]が

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +MRTKが提供する入力システムの裏には、マルチプラットフォーム/複合現実フレームワークの複雑さを抽象化するために必要な複雑な絡み合わせを駆動し、管理するのに役立ちます。
複合現実フレームワーク -> Mixed Reality フレームワーク

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +MRTKが提供する入力システムの裏には、マルチプラットフォーム/複合現実フレームワークの複雑さを抽象化するために必要な複雑な絡み合わせを駆動し、管理するのに役立ちます。
MRTK が提供する入力システムの背後にはその他のいくつかのシステムがあり、マルチプラットフォーム/Mixed Realityフレームワークの複雑さを抽象化するために、複雑な絡み合わせを駆動させ、管理するのを補助します。

とかかな。driveの訳が難しいね。

2019-08-28 13:55 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +境界(Boundary)システムは、基底になるプラットフォームの境界線/保護システムにより、体感できる境界に変換します。境界ビジュアライザー(Boundary visualizer)設定を使用すると、シーン内で記録された境界をユーザーの位置に対して自動的に表示できます。境界線は、ユーザーがシーン内でテレポートする場所に基づいて反応/更新も行われます。
境界[スペース](Boundary)[スペース]

2019-08-28 13:56 UTC, tattichan commented
一か所指摘されたら、それが他のところにもないか注意深くみながら修正をしてみてください！
例えばスペースのところ

2019-08-28 14:20 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +# エクスペリエンスの設定
すみません。追加します

2019-08-28 14:22 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +MRTKが提供する入力システムの裏には、マルチプラットフォーム/複合現実フレームワークの複雑さを抽象化するために必要な複雑な絡み合わせを駆動し、管理するのに役立ちます。
難しいですね。。

2019-08-30 04:25 UTC, decoc requested changes

2019-08-30 04:25 UTC, decoc commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkit の空間認識設定を使用すると、アプリケーションの起動時に自動的に行うか、プログラムで後で行うか、また視野の範囲を設定するかどうかにかかわらず、システムの起動方法を調整できます。
Mixed Reality Toolkit の空間認識設定を使用すると、アプリケーションの起動時に自動的に行うか、プログラムで後で行うかにかかわらず、システムの起動方法を調整したり、視野の範囲を設定することができます。

かな？

2019-08-30 04:25 UTC, decoc commented on Documentation.ja/ProfilesConfiguration.md
> +また、メッシュとサーフェスの設定を行い、プロジェクトが周囲の環境をどのように理解するかをさらにカスタマイズすることもできます。
理解ー＞認識

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +診断プロファイルには、シーン内の表示ペインを有効/無効にする便利なスイッチオン/オフなど、プロジェクトの実行中に監視するいくつかの簡単なシステムが提供されます。
原文 pane->panel で間違っているね

ペインではなくパネル

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkit のより高度な領域の1つは、フレームワークとの任意の「サービス」の登録を可能にする[サービスロケータパターン](https://en.wikipedia.org/wiki/Service_locator_pattern)の実装です。これにより、フレームワークを新しい機能/システムで簡単に拡張できますし、プロジェクトはこれらの機能を利用して独自のランタイム
フレームワークとの任意の　－＞　フレームワークと任意の

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkit のより高度な領域の1つは、フレームワークとの任意の「サービス」の登録を可能にする[サービスロケータパターン](https://en.wikipedia.org/wiki/Service_locator_pattern)の実装です。これにより、フレームワークを新しい機能/システムで簡単に拡張できますし、プロジェクトはこれらの機能を利用して独自のランタイム
これにより、フレームワークに新しい機能/システムを簡単に拡張でき、プロジェクトはこれらの機能を利用して独自のランタイムコンポーネントも登録できます。

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +登録済みのサービスは、MonoBehaviour または不格好なシングルトンパターンを実装するオーバーヘッドとコストなしで、すべての Unity イベントを最大限に活用できます。これにより、フォアグラウンド（foreground）プロセスとバックグラウンド (background) プロセス(スポーンシステム、ランタイムゲームロジックなど)の両方を実行するためのシーンオーバーヘッドのない純粋な
プロセス[スペース](スポーンシステム

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +入力アクションを使用すると、ランタイムプロジェクトからの物理的なインタラクションや入力を真似ることができます。すべての物理入力 (コントローラ/手/マウス等) は、ランタイムプロジェクトで使用するための論理入力アクションに変換されます。これにより、入力元に関係なく、プロジェクトはシーン内でこれらのアクションを"行う操作" または "これとインタラクション" として実装するだけでできます。
真似る-> 抽象化

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +入力アクションを使用すると、ランタイムプロジェクトからの物理的なインタラクションや入力を真似ることができます。すべての物理入力 (コントローラ/手/マウス等) は、ランタイムプロジェクトで使用するための論理入力アクションに変換されます。これにより、入力元に関係なく、プロジェクトはシーン内でこれらのアクションを"行う操作" または "これとインタラクション" として実装するだけでできます。
「実行する操作」または「対象とインタラクションする」

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +> MRTK は現在、Unity が提供されていない、数多くのネイティブSDKのコントローラーのモデルの gLTF モデルをロード/レンダリングする機能をサポートしていません。これは、使用可能なときに追加されます。
ネイティブ SDK

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +サービスインスペクタの有効にする
を有効にする

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +サービスインスペクタは、シーン内オブジェクトを生成する、エディタ上のみの機能です。これらのオブジェクトを選択すると、ドキュメントリンクを提供するインスペクタが表示され、エディタの視覚情報を制御し、サービスの状態に関する情報が表示されます。
エディタの見た目を制御し

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Mixed Reality Toolkit の主要な設定画面の1つは、プロジェクトで使用できるさまざまな種類のコントローラを設定およびマップする機能です。
マッピング

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +> このシステムは現在、HoloLens や Windows 10 デスクトップなどの Windows 10 プラットフォームで実行されている場合にのみ音声認識をサポートしており、将来 MRTK に追加される他のシステムでも拡張される予定です (日付はまだありません)。
日付は未定です

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +ジェスチャは、さまざまな SDK (HoloLens など) によって提供されるさまざまな "ジェスチャ" 入力メソッドに入力アクションを割り当てることができるシステム固有の実装です。
「ジェスチャ」

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Pointers は、任意の入力デバイスからシーン内のインタラクティブ性を駆動するために使用され、シーン内の任意のオブジェクト (コライダがアタッチされている、または UI コンポーネント) を持つ方向とヒットテストの両方を提供します。Pointers は、デフォルトでは、コントローラ、ヘッドセット(視線/フォーカス)、マウス/タッチ入力用に自動的に設定されます。
インタラクティブ性ー＞インタラクティブな要素

2019-08-30 04:25 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Pointers は、任意の入力デバイスからシーン内のインタラクティブ性を駆動するために使用され、シーン内の任意のオブジェクト (コライダがアタッチされている、または UI コンポーネント) を持つ方向とヒットテストの両方を提供します。Pointers は、デフォルトでは、コントローラ、ヘッドセット(視線/フォーカス)、マウス/タッチ入力用に自動的に設定されます。
入力の向きとヒットテストの両方を、シーン内の任意のオブジェクト (コライダがアタッチされている、または UI コンポーネント) に対して行います。

2019-08-30 08:59 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +診断プロファイルには、シーン内の表示ペインを有効/無効にする便利なスイッチオン/オフなど、プロジェクトの実行中に監視するいくつかの簡単なシステムが提供されます。
ですよね！！！！！！！！

2019-08-30 09:00 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +診断プロファイルには、シーン内の表示ペインを有効/無効にする便利なスイッチオン/オフなど、プロジェクトの実行中に監視するいくつかの簡単なシステムが提供されます。
とんでもないissueです！！！！

2019-08-30 09:10 UTC, cindychen0204 commented
修正しました！

2019-09-08 04:13 UTC, decoc requested changes

2019-09-08 04:13 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +# コントローラの視覚化の設定
視覚化→可視化

2019-09-08 04:13 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +MRTK は、複雑なシーンの読み込み (loading) /アンロード (unloading) の管理に役立つオプションを提供します。シーンシステムがプロジェクトに適しているかどうかを判断するには、[シーン システムの開始ガイド](../Documentation/SceneSystem/SceneSystemGettingStarted.html)を参照してください。
シーンシステムの間にスペースが入ってる

2019-09-08 04:13 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +MRTK は、複雑なシーンの読み込み (loading) /アンロード (unloading) の管理に役立つオプションを提供します。シーンシステムがプロジェクトに適しているかどうかを判断するには、[シーン システムの開始ガイド](../Documentation/SceneSystem/SceneSystemGettingStarted.html)を参照してください。
シーンのロード/アンロードでいいと思う

2019-09-08 04:13 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +これは、独自のコードで行うこともできます。しかし、これは非常に一般的なパターンであったので、フレームワークはこれをそとから変更できるメカニズムを提供します。
そとから→外から

2019-09-08 04:13 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Input Action Rules は、使用可能な入力軸のいずれかに対して設定できます。ただし、1 つの軸タイプからの入力アクションは、同じ軸タイプの別の入力アクションに変換できます。二重軸アクションを別の二重軸アクションにマップできますが、デジタルアクションまたはアクションなしにはマップできません。
１つの のところに余分なスペースが入ってる

2019-09-08 04:13 UTC, tattichan commented on Documentation.ja/ProfilesConfiguration.md
> +Input Action Rules は、使用可能な入力軸のいずれかに対して設定できます。ただし、1 つの軸タイプからの入力アクションは、同じ軸タイプの別の入力アクションに変換できます。二重軸アクションを別の二重軸アクションにマップできますが、デジタルアクションまたはアクションなしにはマップできません。
二重軸→デュアル軸

2019-09-10 14:49 UTC, cindychen0204 commented on Documentation.ja/ProfilesConfiguration.md
> +MRTK は、複雑なシーンの読み込み (loading) /アンロード (unloading) の管理に役立つオプションを提供します。シーンシステムがプロジェクトに適しているかどうかを判断するには、[シーン システムの開始ガイド](../Documentation/SceneSystem/SceneSystemGettingStarted.html)を参照してください。
シーンシステムの間にスペースが入ってる　→マイクロソフトのルールによりそのままに行きます！

2019-09-10 14:51 UTC, cindychen0204 commented
修正しましたー

2019-09-12 13:36 UTC, decoc requested changes

2019-09-12 13:36 UTC, decoc commented on Documentation.ja/ProfilesConfiguration.md
> +シーンの _MixedRealityToolkit_ GameObject にアタッチされている主な設定プロファイル (Congifuration Profile) は、ツールキットの第一のエントリーポイントです。
最初のエントリーポイント

2019-09-18 01:56 UTC, cindychen0204 commented
修正しました
ーカタカナ
ーコントローラ　→　コントローラー

2019-09-18 03:50 UTC, cindychen0204 commented
rebase
行数をオリジナルに合わせた

56行に本家のエラー（同じ文を二回言っている）があるので、その後の行数は2行ずれる

2019-09-18 03:56 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +-[Experience settings](../Documentation/MixedRealityConfigurationGuide.html#experience)
(../Documentation/MixedRealityConfigurationGuide.html#experience)
ページ内リンクなので、
(#experience)
で良いです

2019-09-18 03:56 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +* [Input actions settings](../Documentation/MixedRealityConfigurationGuide.html#input-actions-settings)
ここも、そのままで OK です

2019-09-18 03:56 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +|-------------------------|-------------------------------------------------|--------------------------------------------------------------------------------------------------|-----------------------
| :--- | :--- | :--- | :--- |	

このままでいいと思うんだけど、
:--- と --- って同じかな？

2019-09-18 09:09 UTC, tarukosu reviewed
103 行目までレビューしました

2019-09-18 09:09 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +メインの Mixed Reality Toolkit 設定プロファイルを開くと、インスペクタに次の画面が表示されます。
インスペクタ
[Inspector]（インスペクター）

2019-09-18 09:09 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +Mixed Reality Toolkit のメイン設定ページにあるこの項目では、プロジェクトの Mixed Reality 環境の既定の操作が定義されます。
既定の
他のところでは「デフォルト」で訳してるから、「デフォルトの」でいい気がします

2019-09-18 09:09 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +Mixed Reality プロジェクトは、デフォルトの設定で、すべての入力イベントを連結するための堅牢で十分にトレーニングされてきた入力システムを提供します。
ここの訳難しい...

2019-09-18 09:09 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +Mixed Reality プロジェクトは、デフォルトの設定で、すべての入力イベントを連結するための堅牢で十分にトレーニングされてきた入力システムを提供します。
連結　と　トレーニング　のところが意味が伝わりづらい

2019-09-18 09:09 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +Mixed Reality プロジェクトは、デフォルトの設定で、すべての入力イベントを連結するための堅牢で十分にトレーニングされてきた入力システムを提供します。
すべての入力イベントを連結するための堅牢で十分にトレーニングされてきた入力システムを提供します。

すべての入力イベントを取り扱うための堅牢で十分に熟練した入力システムを提供します。

2019-09-18 09:09 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +Mixed Reality プロジェクトは、デフォルトの設定で、すべての入力イベントを連結するための堅牢で十分にトレーニングされてきた入力システムを提供します。
あんまり変わらないような気もする...

2019-09-18 10:15 UTC, cindychen0204 commented
たるこすさんのコメントによる修正
アンカー、テーブルはDocfxで確認済み

2019-09-18 12:26 UTC, tarukosu reviewed
117 行目まで

2019-09-18 12:26 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +メインの Mixed Reality Toolkit 設定プロファイルを開くと、Inspector (インスペクター)に次の画面が表示されます。
\[Inspector]（インスペクター）

[ つけてもらえる？

2019-09-18 12:26 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +境界 (Boundary) システムは、基底になるプラットフォームの境界線/保護システムにより、体感できる境界に変換します。境界ビジュアライザー (Boundary visualizer) 設定を使用すると、シーン内で記録された境界をユーザーの位置に対して自動的に表示できます。境界線は、ユーザーがシーン内でテレポートする場所に基づいて反応/更新も行われます。
> 境界 (Boundary) システムは、基底になるプラットフォームの境界線/保護システムにより、体感できる境界に変換します。

境界 (Boundary) システムは、元となるプラットフォームの境界/ガーディアン システムから取得した境界を解釈します。

2019-09-18 12:26 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +Mixed Reality プロジェクトは、デフォルトで選択されたプロジェクトのテレポーテーション イベントを管理するための完全な機能を備えています。
Mixed Reality プロジェクトは、プロジェクトでのテレポーテーション イベントを管理するための完全な機能を備えたテレポーテーション システムを提供しており、これはデフォルトで選択されています。

which is selected by default の解釈これで合っているかな？

2019-09-18 12:29 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +Mixed Reality プロジェクトは、デフォルトの設定で、すべての入力イベントを取り扱うための堅牢で十分に熟練した入力システムを提供します。
Mixed Reality プロジェクトは、すべての入力イベントを取り扱うための堅牢で十分に熟練した入力システムを提供しており、これはデフォルトで選択されています。

2019-09-18 12:30 UTC, tarukosu commented on Documentation.ja/MixedRealityConfigurationGuide.md
> +Mixed Reality プロジェクトは、デフォルトの設定で、すべての入力イベントを取り扱うための堅牢で十分に熟練した入力システムを提供します。
which is selected by default
は、こっちもこんな感じにすると読みやすいかな

2019-09-18 15:47 UTC, cindychen0204 commented
たるこすさんの指示で読むやすくなった。

2019-09-19 04:54 UTC, decoc approved these changes

2019-09-19 05:39 UTC, merged