Origin/doc ja/readme tooltip.html
HoloLabInc/MixedRealityToolkit-Unity pull request #37
Opened 2019-10-02 02:08 UTC by cindychen0204

2019-10-02 13:32 UTC, decoc requested changes

2019-10-02 13:32 UTC, tattichan commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、[Hierarchy](ヒエラルキー) ウィンドウ に直接追加し、オブジェクトをターゲットとすることができます。
ウィドウは元の英文にないですー

2019-10-02 13:32 UTC, tattichan commented on Documentation.ja/README_Tooltip.md
> +この使用では、Tooltip コンポーネントの Tip State プロパティを変更して、常に表示されるツールチップ、またはスクリプトを介して表示/非表示のツールチップを想定しています。
この使用法は、

2019-10-02 13:32 UTC, tattichan commented on Documentation.ja/README_Tooltip.md
> +この使用では、Tooltip コンポーネントの Tip State プロパティを変更して、常に表示されるツールチップ、またはスクリプトを介して表示/非表示のツールチップを想定しています。
ツールチップ→Tooltip

2019-10-02 13:32 UTC, tattichan commented on Documentation.ja/README_Tooltip.md
> +## 動的に tooltips を作成##
作成する

2019-10-02 13:32 UTC, tattichan commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスに表示および非表示にする事前設定もできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Feature
タップまたはフォーカスしたときに、

2019-10-02 13:45 UTC, cindychen0204 commented
デコシのコメントによる修正

2019-10-03 03:05 UTC, decoc requested changes

2019-10-03 03:05 UTC, tattichan commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスしたときに、表示および非表示にする事前設定もできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Fe
表示と消失の遅延→ツールチップが、現れたり、消える時の遅延時間は、

と書いた方が分かりやすいかな。何の表示かが、文章からだと読み取りにくい。

2019-10-03 03:05 UTC, tattichan commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスしたときに、表示および非表示にする事前設定もできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Fe
過ぎに消えます→過ぎると消えます

2019-10-03 03:05 UTC, tattichan commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスしたときに、表示および非表示にする事前設定もできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Fe
Spawn → Spawner

2019-10-03 04:31 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
1行目だけ、カタカナで読み方を書いておくと良いと思います
```
# Tooltip（ツールチップ） #
```

2019-10-03 04:31 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +## 動的に tooltips を作成する##
tooltips -> Tooltip

かな。

2019-10-03 13:25 UTC, tarukosu commented
@cindychen0204 
そこまで悪影響はないんだけど、ブランチ名が間違ってる(originが入ってる）ね

2019-10-03 23:32 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +この方法を使用するには、単にゲームオブジェクトと[Tooltip プレハブ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Tooltips) をシーンの [Hierarchy](ヒエラルキー)
ゲーム オブジェクト

2019-10-03 23:34 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +この方法を使用するには、単にゲームオブジェクトと[Tooltip プレハブ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Tooltips) をシーンの [Hierarchy](ヒエラルキー)
Tooltip を持つ -> Tooltip を持たせる

2019-10-04 00:27 UTC, tarukosu requested changes
レビュー途中です

2019-10-04 06:12 UTC, cindychen0204 commented
デコシさん、たるこすさんによる修正

2019-10-05 08:43 UTC, tarukosu requested changes

2019-10-05 08:43 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +Tooltip は通常、オブジェクトを詳しく調べるときにヒントや追加情報を伝えるために使用されます。Tooltip を使用して、物理環境内のオブジェクトにアノテーションを付けることができます。
詳しく調べるときに
-> 詳しく調べるときの

2019-10-05 08:43 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +この方法を使用するには、単にゲーム オブジェクトと[Tooltip プレハブ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Tooltips) をシーンの [Hierarchy](ヒエラルキー)
> それぞれの Tooltip のテキスト フィールドに入力します。

Tooltip のテキスト フィールドにそれぞれのテキストを入力します。

2019-10-05 08:43 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +この使用は、Tooltip コンポーネントの Tip State プロパティを変更して、常に表示される Tooltip、またはスクリプトを介して表示/非表示のツールチップを想定しています。
> この使用は、Tooltip コンポーネントの Tip State プロパティを変更して、常に表示される Tooltip、またはスクリプトを介して表示/非表示のツールチップを想定しています

この使用方法は、Tooltip が常に表示される場合や、Tooltip コンポーネントの Tooltip State プロパティをスクリプトで変更して表示/非表示を切り替える場合を想定しています。

2019-10-05 08:43 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスしたときに、表示および非表示にする事前設定もできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Fe
> Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスしたときに、表示および非表示にする事前設定もできます。

Tooltip は、事前に設定しておいてタップやフォーカスによって表示と非表示を行うだけでなく、実行時にオブジェクトに動的に追加することもできます。

2019-10-05 08:43 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスしたときに、表示および非表示にする事前設定もできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Fe
> Tooltip が、現れたり、消える時の遅延時間は、は、スクリプト インスペクタと有効期間で設定できるため、Tooltip は設定された期間が過ぎると消えます。

スクリプトのインスペクターにて、設定された期間が過ぎると Tooltip が消えるように生存期間を設定したり、現れたり消えたりする際の遅延時間を設定したりできます。

2019-10-05 08:43 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスしたときに、表示および非表示にする事前設定もできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Fe
> Tooltip には、spawner スクリプトの背景ビジュアルなどのスタイル プロパティも備えています。

Tooltip は背景の見た目のようなスタイルのプロパティも備えており、ToolTipSpawner スクリプトで設定できます。

2019-10-05 08:43 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、実行時にオブジェクトに動的に追加できるだけでなく、タップまたはフォーカスしたときに、表示および非表示にする事前設定もできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/Fe
> デフォルトでは、Tooltip は spawner スクリプトを使用してオブジェクトに固定されます。

デフォルトでは、Tooltip は ToolTipSpawner スクリプトを持つオブジェクトに固定されます。

2019-10-05 13:58 UTC, cindychen0204 commented
たるこすさんによる修正

2019-10-05 17:14 UTC, decoc approved these changes

2019-10-06 01:08 UTC, decoc requested changes
review状態戻し

2019-10-06 23:14 UTC, tarukosu requested changes

2019-10-06 23:14 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、事前に設定しておいてタップやフォーカスによって表示と非表示を行うだけでなく、実行時にオブジェクトに動的に追加することもできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/F
追加するだけです のあとに「。」

2019-10-08 00:04 UTC, tarukosu commented on Documentation.ja/README_Tooltip.md
> +Tooltip は、事前に設定しておいてタップやフォーカスによって表示と非表示を行うだけでなく、実行時にオブジェクトに動的に追加することもできます。 [`ToolTipSpawner`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.SDK/F
@cindychen0204 
ここだけ修正お願いします

2019-10-09 01:31 UTC, cindychen0204 commented
たるこすさんによる修正

2019-10-09 01:34 UTC, tarukosu approved these changes
レビュー完了しました

2019-10-09 14:09 UTC, merged