Input Overview.mdの翻訳
HoloLabInc/MixedRealityToolkit-Unity pull request #39
Opened 2019-10-03 05:02 UTC by HiromuKato

2019-10-03 06:43 UTC, decoc requested changes

2019-10-03 06:43 UTC, tattichan commented on Documentation.ja/Input/Overview.md
> +<sup>MRTK 入力システムの概要</sup>
Input SystemはMRTKの用語なので、Input System (入力システム) の方がいいですかね

2019-10-03 06:43 UTC, tattichan commented on Documentation.ja/Input/Overview.md
> +入力は [**入力データ プロバイダー(デバイス マネージャー) (Input Data Providers(Device Manager))**](InputProviders.md) によって生成されます。各プロバイダーは、Open VR、Windows Mixed Reality (WMR)、Unity Joystick、Windows Speech など、入力の特定のソースに対応していま
伝達ができていなくて申し訳ないのですが、日本語(英語)ではなく英語(日本語)にしてもらえると助かります
Input Data Providers (入力データ プロバイダー)

2019-10-03 06:43 UTC, tattichan commented on Documentation.ja/Input/Overview.md
> +[**コントローラー (Controllers)**](Controllers.md) は、入力デバイスが検出されたときに *入力プロバイダー (input providers)* によって作成され、入力デバイスが失われたり切断されたりすると破棄されます。たとえば、WMR 入力プロバイダーは、6 DOF デバイス用の *WMR コントローラー*と、多関節ハンド用の *WMR 多関節ハンド コント
WMR 多関節ハンド コントローラー-> WMR articulated hand controllers

2019-10-03 06:43 UTC, tattichan commented on Documentation.ja/Input/Overview.md
> +[**コントローラー (Controllers)**](Controllers.md) は、入力デバイスが検出されたときに *入力プロバイダー (input providers)* によって作成され、入力デバイスが失われたり切断されたりすると破棄されます。たとえば、WMR 入力プロバイダーは、6 DOF デバイス用の *WMR コントローラー*と、多関節ハンド用の *WMR 多関節ハンド コント
多関節ハンド　→ articulated hand (多関節ハンド)

2019-10-03 13:33 UTC, tarukosu commented on Documentation.ja/Input/Overview.md
> +<sup>MRTK Input System (入力システム)</sup>
MRTK Input System (入力システム)の概要

2019-10-05 09:06 UTC, tarukosu commented on Documentation.ja/Input/Overview.md
> +コントローラーには、[**Pointers (ポインター)**](Pointers.md) をアタッチして、シーンを照会してフォーカスのあるゲーム オブジェクトを決定し、[**Pointer Events (ポインター イベント)**](Pointers.md#pointer-event-interfaces) を発生させることができます。例として、*line pointer (ライン ポインタ
> 例として、*line pointer (ライン ポインター)* はコントローラーのポーズを使用してシーンに対してレイキャストを実行し、レイの原点と方向を計算します。

例として、*line pointer (ライン ポインター)* はレイの原点と方向を計算するためにコントローラーの姿勢を利用し、シーンに対してレイキャストを行います。

2019-10-05 11:56 UTC, HiromuKato commented on Documentation.ja/Input/Overview.md
> +コントローラーには、[**Pointers (ポインター)**](Pointers.md) をアタッチして、シーンを照会してフォーカスのあるゲーム オブジェクトを決定し、[**Pointer Events (ポインター イベント)**](Pointers.md#pointer-event-interfaces) を発生させることができます。例として、*line pointer (ライン ポインタ
訂正後の文章のほうがわかりやすいですね。ありがとうございます。

2019-10-05 12:01 UTC, tarukosu commented on Documentation.ja/Input/Overview.md
> +コントローラーには、[**Pointers (ポインター)**](Pointers.md) をアタッチして、シーンを照会してフォーカスのあるゲーム オブジェクトを決定し、[**Pointer Events (ポインター イベント)**](Pointers.md#pointer-event-interfaces) を発生させることができます。例として、Iline pointer (ライン ポインタ
*line が Iline になってます！

2019-10-05 12:09 UTC, HiromuKato commented on Documentation.ja/Input/Overview.md
> +コントローラーには、[**Pointers (ポインター)**](Pointers.md) をアタッチして、シーンを照会してフォーカスのあるゲーム オブジェクトを決定し、[**Pointer Events (ポインター イベント)**](Pointers.md#pointer-event-interfaces) を発生させることができます。例として、Iline pointer (ライン ポインタ
わー、すみません。

2019-10-05 12:21 UTC, tarukosu approved these changes

2019-10-05 17:13 UTC, decoc approved these changes

2019-10-05 17:13 UTC, merged