Update README_SystemKeyboard.md
HoloLabInc/MixedRealityToolkit-Unity pull request #43
Opened 2019-10-05 13:20 UTC by cindychen0204

2019-10-05 17:13 UTC, decoc requested changes

2019-10-05 17:13 UTC, tattichan commented on Documentation.ja/README_SystemKeyboard.md
> +# システム キーボード #
System keyboard (システム キーボード)
これはmrtkの用語なので

2019-10-05 17:13 UTC, tattichan commented on Documentation.ja/README_SystemKeyboard.md
> +Unity アプリケーションならば、いつでもシステム キーボードを呼び出すことができます。システム キーボードはターゲット プラットフォームの機能に従って機能し、たとえば HoloLens 2 のキーボードは手の直接操作をサポートし、HoloLens (第 1 世代) のキーボードは GGV をサポートすることに注意してください。<sup>[1](https://docs.microsoft.c
ターゲット プラットフォームの機能に応じて動作し、

2019-10-05 17:13 UTC, tattichan commented on Documentation.ja/README_SystemKeyboard.md
> +Unity アプリケーションならば、いつでもシステム キーボードを呼び出すことができます。システム キーボードはターゲット プラットフォームの機能に従って機能し、たとえば HoloLens 2 のキーボードは手の直接操作をサポートし、HoloLens (第 1 世代) のキーボードは GGV をサポートすることに注意してください。<sup>[1](https://docs.microsoft.c
手の直接操作をサポートし、→ダイレクト ハンド インタラクションをサポートしますが、

2019-10-05 17:13 UTC, tattichan commented on Documentation.ja/README_SystemKeyboard.md
> +## 入力の読み込み方法 ##
読み込み方
上と揃えよう

2019-10-05 17:13 UTC, tattichan commented on Documentation.ja/README_SystemKeyboard.md
> +## システム キーボードのサンプル ##
システム キーボードを表示する簡単な例を見ることができます。

2019-10-09 03:00 UTC, cindychen0204 commented on Documentation.ja/README_SystemKeyboard.md
> +# システム キーボード #
中身をSystem keyboardで書きます！

2019-10-09 03:03 UTC, cindychen0204 commented on Documentation.ja/README_SystemKeyboard.md
> +## システム キーボードのサンプル ##
デコシさんによる修正

2019-10-09 03:03 UTC, cindychen0204 commented
デコシさんによる修正

2019-10-24 23:11 UTC, tarukosu requested changes

2019-10-24 23:11 UTC, tarukosu commented on Documentation.ja/README_SystemKeyboard.md
> +Unity アプリケーションならば、いつでもシステム キーボードを呼び出すことができます。システム キーボードはターゲット プラットフォームの機能に応じて動作し、たとえば HoloLens 2 のキーボードはダイレクト ハンド インタラクションをサポートしますが、HoloLens (第 1 世代) のキーボードは GGV をサポートすることに注意してください。<sup>[1](https://d
```suggestion
Unity アプリケーションならば、いつでもシステム キーボードを呼び出すことができます。システム キーボードはターゲット プラットフォームの機能に応じて動作し、たとえば HoloLens 2 のキーボードはダイレクト ハンド インタラクションをサポートしますが、HoloLens (第 1 世代) のキーボードは GGV<sup>[1](https://docs.microsoft.com/en-us/windows/mixed-reality/gaze)</sup> をサポートすることに注意してください。
```

2019-10-24 23:11 UTC, tarukosu commented on Documentation.ja/README_SystemKeyboard.md
> +システム キーボードを表示する簡単な例を見ることができます。 [`OpenKeyboard.cs`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/OpenKeyboard.
```suggestion
システム キーボードを表示する簡単な例は、[`OpenKeyboard.cs`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_release/Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/OpenKeyboard.cs) にて見ることができます。
```

2019-10-25 04:30 UTC, cindychen0204 commented
修正しました

2019-10-27 01:07 UTC, merged