Update TeleportSys_Overview.md
HoloLabInc/MixedRealityToolkit-Unity pull request #44
Opened 2019-10-05 13:54 UTC by cindychen0204

2019-10-05 17:01 UTC, decoc requested changes

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> -be enabled.
Opaque Display (不透明なディスプレイ)
これはUnity用語なので

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは MRTK のサブシステムで、アプリケーションが不透明なディスプレイ (opaque display) を使用しているときにユーザのテレポートの処理をします。AR 体験( HoloLens など)の場合、テレポート システムが非アクティブです。没入型 HMD エクスペリエンス ( OpenVR、WMR ) でのテレポート システムを有効にすることができます。
ユーザー

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは MRTK のサブシステムで、アプリケーションが不透明なディスプレイ (opaque display) を使用しているときにユーザのテレポートの処理をします。AR 体験( HoloLens など)の場合、テレポート システムが非アクティブです。没入型 HMD エクスペリエンス ( OpenVR、WMR ) でのテレポート システムを有効にすることができます。
など) の後にスペース

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは MRTK のサブシステムで、アプリケーションが不透明なディスプレイ (opaque display) を使用しているときにユーザのテレポートの処理をします。AR 体験( HoloLens など)の場合、テレポート システムが非アクティブです。没入型 HMD エクスペリエンス ( OpenVR、WMR ) でのテレポート システムを有効にすることができます。
エクスペリエンスでの→エクスペリエンス向けに

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは、プロファイルのチェック ボックスをオン/オフに切り替えることができます。
チェックボックス

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +"Teleport" をクリックしてから "Enable Teleport System" のチェック ボックスをオンにすることで設定できます。
余計な改行

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +"Teleport" をクリックしてから "Enable Teleport System" のチェック ボックスをオンにすることで設定できます。
チェックボックス

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +"Teleport" をクリックしてから "Enable Teleport System" のチェック ボックスをオンにすることで設定できます。
オンにする→有効にする

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは[`IMixedRealityTeleportHandler`](xref:Microsoft.MixedReality.Toolkit.Teleport.IMixedRealityTeleportHandler) を通じてイベントを公開します。
通じて→通して

2019-10-05 17:01 UTC, decoc commented on Documentation.ja/TeleportSystem/Overview.md
> +### テレポート　イベントの登録方法
テレポーテーション

2019-10-05 17:01 UTC, tattichan commented on Documentation.ja/TeleportSystem/Overview.md
> +次のコードは、テレポーテーションのイベントに待機する (Listen) MonoBehaviour を作成する方法を示しています。
イベントをリッスンする

2019-10-05 17:01 UTC, tattichan commented on Documentation.ja/TeleportSystem/Overview.md
> +このコードの前提は、テレポート システムが有効になっていることです。
余計な改行

2019-10-05 17:01 UTC, tattichan commented on Documentation.ja/TeleportSystem/Overview.md
> +このコードの前提は、テレポート システムが有効になっていることです。
このコードはテレポート システムが有効になっていることを前提とします。

2019-10-09 03:10 UTC, cindychen0204 commented
デコシさんによる修正

2019-10-24 23:22 UTC, tarukosu requested changes

2019-10-24 23:22 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは MRTK のサブシステムで、アプリケーションが Opaque Display (不透明なディスプレイ) を使用しているときにユーザーのテレポートの処理をします。AR 体験( HoloLens など )の場合、テレポート システムが非アクティブです。没入型 HMD エクスペリエンス ( OpenVR、WMR ) 向けにテレポート システムを有効にすることができます。
```suggestion
テレポート システムは MRTK のサブシステムで、アプリケーションが Opaque Display (不透明なディスプレイ) を使用しているときにユーザーのテレポートの処理をします。AR 体験 (HoloLens など) の場合、テレポート システムは非アクティブです。没入型 HMD エクスペリエンス (OpenVR、WMR) では、テレポート システムを有効にすることができます。
```

2019-10-24 23:22 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは、プロファイルのチェックボックスをオン/オフに切り替えることができます。
```suggestion
テレポート システムは、プロファイルのチェックボックスをオン/オフに切り替えることで有効にしたり無効にしたりできます。
```

2019-10-24 23:22 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +"Teleport" をクリックしてから "Enable Teleport System" のチェックボックスを有効にすることで設定できます。
```suggestion
"Teleport" をクリックしてから "Enable Teleport System" のチェックボックスをトグルすることで設定できます。
```

2019-10-24 23:22 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +次のコードは、テレポーテーションのイベントをリッスンする MonoBehaviour を作成する方法を示しています。ここのコードはテレポート システムが有効になっていることを前提とします。
```suggestion
次のコードは、テレポーテーションのイベントをリッスンする MonoBehaviour を作成する方法を示しています。このコードはテレポート システムが有効になっていることを前提とします。
```

2019-10-24 23:22 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは[`IMixedRealityTeleportHandler`](xref:Microsoft.MixedReality.Toolkit.Teleport.IMixedRealityTeleportHandler) を通してイベントを公開します。
```suggestion
テレポート システムは [`IMixedRealityTeleportHandler`](xref:Microsoft.MixedReality.Toolkit.Teleport.IMixedRealityTeleportHandler) インターフェイスを通してイベントを公開します。
```

2019-10-24 23:22 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +インターフェイスは、テレポート アクションの開始、終了、またはキャンセル時に通知を提供します。
```suggestion
このインターフェイスは、テレポート アクションの開始、終了、またはキャンセル時に通知を提供します。
```

2019-10-24 23:22 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +イベントの仕組みとそれに関連する負荷などの詳細については、リンク付きの API ドキュメントをご参照ください。
```suggestion
イベントの仕組みとそれに関連するデータの詳細については、リンク先の API ドキュメントをご参照ください。
```

2019-10-25 04:26 UTC, cindychen0204 commented on Documentation.ja/TeleportSystem/Overview.md
> +"Teleport" をクリックしてから "Enable Teleport System" のチェックボックスを有効にすることで設定できます。
チェックボックスをトグルする　は初めて聞きました.....

2019-10-25 04:27 UTC, cindychen0204 commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは[`IMixedRealityTeleportHandler`](xref:Microsoft.MixedReality.Toolkit.Teleport.IMixedRealityTeleportHandler) を通してイベントを公開します。
丁寧ですね。

2019-10-25 04:28 UTC, cindychen0204 commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは、プロファイルのチェックボックスをオン/オフに切り替えることができます。
同じこと2回言っていると思います！

2019-10-25 04:28 UTC, cindychen0204 commented
修正+コメントしました！

2019-10-25 09:14 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは、プロファイルのチェックボックスをオン/オフに切り替えることができます。
toggling の部分と enabled or disabled の部分を表してます

2019-10-25 09:15 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは、プロファイルのチェックボックスをオン/オフに切り替えることができます。
テレポート システムは、プロファイルのチェックボックスをトグルすることで有効にしたり無効にしたりできます。

2019-10-25 09:15 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +テレポート システムは、プロファイルのチェックボックスをオン/オフに切り替えることができます。
これでもいいかも

2019-10-25 09:16 UTC, tarukosu commented on Documentation.ja/TeleportSystem/Overview.md
> +"Teleport" をクリックしてから "Enable Teleport System" のチェックボックスを有効にすることで設定できます。
toggle を表す簡潔な日本語がないから、トグルでいいかなと思ってます

2019-10-27 05:58 UTC, cindychen0204 commented on Documentation.ja/TeleportSystem/Overview.md
> +"Teleport" をクリックしてから "Enable Teleport System" のチェックボックスを有効にすることで設定できます。
「チェックを入れる」はだめですか？

2019-10-27 06:01 UTC, cindychen0204 commented
修正しました！

2019-10-27 06:19 UTC, merged