[WIP] Doc ja readme mrtkstandardshader md
HoloLabInc/MixedRealityToolkit-Unity pull request #45
Opened 2019-10-06 07:31 UTC by tattichan

Standard Shader の翻訳

- 一部訳ができていない部分の翻訳をお願いしたいです
- Texture Combiner の訳が怪しいので重点的にみてほしい

2019-10-07 03:39 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +MRTK Standard shading システムは，単一で柔軟なシェーダーで， Unityの Standard shader に似たビジュアルを実現しつつ，[Fluent Design System (フルーエントデザインシステム)](https://www.microsoft.com/design/fluent/) の原則に則り，加えて MR デバイスでパフォーマンスを維持することができま
Unity の (半角スペースの追加)

2019-10-07 03:40 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +MRTK Standard shading システムは，単一で柔軟なシェーダーで， Unityの Standard shader に似たビジュアルを実現しつつ，[Fluent Design System (フルーエントデザインシステム)](https://www.microsoft.com/design/fluent/) の原則に則り，加えて MR デバイスでパフォーマンスを維持することができま
フルーエント デザイン システム (半角スペースの追加)

2019-10-07 03:41 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +このシーンにある全てのマテリアルは、MRTK/Standard を使用しています。
MRTK/Standard シェーダーを使用しています。

2019-10-07 03:54 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +[MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes) に
[MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes) に Unity/Standard シェーダーと MRTK/Standard シェーダーの比較やテストができるシーンがあります。

2019-10-07 03:57 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +MRTK/Standard Shader　は、[Unity のシェーダープログラムのバリアント機能](https://docs.unity3d.com/Manual/SL-MultipleProgramVariants.html) というマテリアルのプロパティに応じて最適な Shader コードを自動生成生成する機能を使った、Uber Shader (ウーバーシェーダー) です。ユーザがマテリア
Shader は英語かカタカナのどちらかに統一したいですね。カタカナが良いですかね。

2019-10-07 03:59 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +MRTK/Standard Shader　は、[Unity のシェーダープログラムのバリアント機能](https://docs.unity3d.com/Manual/SL-MultipleProgramVariants.html) というマテリアルのプロパティに応じて最適な Shader コードを自動生成生成する機能を使った、Uber Shader (ウーバーシェーダー) です。ユーザがマテリア
"uber shader"
原文が小文字であるところを大文字にしたのは何か意味がありますか？

2019-10-07 04:49 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +**MixedRealityStandardShaderGUI.cs** という MRTK/Standard Shader 用のカスタム マテリアル インスペクタがあります。インスペクタはユーザの選択に基づいて自動的に Shader 機能の有効/無効をユーザの選択し，レンダリング状態のセットアップを補助します。各機能の詳細情報は，各プロパティ上にカーソルを置いて，Unity エディターのツールチ
> 自動的に Shader 機能の有効/無効をユーザの選択し

自動的にシェーダー機能を有効/無効にし

2019-10-07 04:55 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +**MixedRealityStandardShaderGUI.cs** という MRTK/Standard Shader 用のカスタム マテリアル インスペクタがあります。インスペクタはユーザの選択に基づいて自動的に Shader 機能の有効/無効をユーザの選択し，レンダリング状態のセットアップを補助します。各機能の詳細情報は，各プロパティ上にカーソルを置いて，Unity エディターのツールチ
> 各機能の詳細情報は，各プロパティ上にカーソルを置いて，Unity エディターのツールチップを確認してください。

各機能の詳細情報は，Unity エディターの各プロパティ上にカーソルを置いてツールチップを確認してください。

2019-10-07 05:26 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +Unity Standard Shader よりも MRTK Standard Shader を使用する主な利点の１つは、パフォーマンスです。MRTK Standard Shader は、有効な機能のみを利用するように拡張できます。ただし、 MRTK Standard Shader は、Unity Standard Shader と同等の見栄えをはるかに低いコストで提供するように作成されています
> 一般的に、MRTK Standard Shader は、Unity Starndard Shader よりも大幅に少ない計算を実行します。

「一般的に、MRTK Standard シェーダーは Unity Starndard シェーダーよりも計算量は大幅に少なくなります。」等でどうでしょうか？

2019-10-07 05:26 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +MRTK Standard shading システムは，単一で柔軟なシェーダーで， Unityの Standard shader に似たビジュアルを実現しつつ，[Fluent Design System (フルーエントデザインシステム)](https://www.microsoft.com/design/fluent/) の原則に則り，加えて MR デバイスでパフォーマンスを維持することができま
「，」か「、」のどちらかに統一したいです。

2019-10-07 05:46 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +Hover Light は、オブジェクトの表面近くでホバリングする「Point Light (ポイント ライト)」を模倣する Fluent Design System (フルーエント デザイン システム) のパラダイムです。多くの場合、アプリケーションは [**HoverLight.cs**](xref：Microsoft.MixedReality.Toolkit.Utilities.Hover
> 多くの場合、アプリケーションは [**HoverLight.cs**](xref：Microsoft.MixedReality.Toolkit.Utilities.HoverLight) を介して Hover Light のプロパティを制御できます。

「遠くのカーソル点灯によく使われ、アプリケーションは [**HoverLight.cs**](xref：Microsoft.MixedReality.Toolkit.Utilities.HoverLight) を介して Hover Light のプロパティを制御できます。」
という感じでしょうか？

2019-10-07 06:05 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +Proximity Light は、オブジェクトの表面近くでホバリングする「Gradient inverse point light (階調度反転ポイント ライト) 」を模倣する Fluent Design System (フルーエント デザイン システム) のパラダイムです。多くの場合、カーソルの近辺のライトに使用され、アプリケーションは [**ProximityLight.cs**](xre
> P roximity

Proximity

2019-10-07 06:10 UTC, HiromuKato commented on Documentation.ja/README_MRTKStandardShader.md
> +ピクセルごとの Unity Standard shader とのパリティを向上させるために、[Channel packing (チャンネル パッキング)](http://wiki.polycount.com/wiki/ChannelPacking)を使用して、metallic (金属らしさ)、smoothness (滑らかさ)、emissive (放射)、および occlusion (オクルージ
「パリティ」を「同等性」とするのはどうでしょうか？

2019-10-07 06:23 UTC, HiromuKato requested changes
気になった点についてコメントしたので、ご確認ください。

2019-10-10 08:31 UTC, tarukosu commented
#52 v2.1.0 での変更があるので、その変更も反映させましょう

2019-11-05 02:37 UTC, closed without merging