Update README_Slate.md
HoloLabInc/MixedRealityToolkit-Unity pull request #46
Opened 2019-10-09 04:25 UTC by cindychen0204

2019-10-24 12:19 UTC, tarukosu requested changes

2019-10-24 12:19 UTC, tarukosu commented on Documentation.ja/README_Slate.md
> +スレート プレハブは、2D コンテンツを表示するための薄いウィンドウ型のコントロールを提供しています (例えば、プレーンテキストやメディアを含む記事)。これは、掴める (grabbable) タイトルバーだけでなく、*Follow Me* と *Close* 機能を提供しています。コンテンツ ウィンドウは、多関節のハンドの入力を介してスクロールすることができます。
```suggestion
スレート プレハブは、2D コンテンツを表示するための薄いウィンドウ スタイルのコントロールを提供しています (例えば、プレーンテキストやメディアを含む記事)。これは、掴める (grabbable) タイトル バーだけでなく、*Follow Me* と *Close* 機能を提供しています。コンテンツ ウィンドウは、多関節ハンドの入力を介してスクロールすることができます。
```

2019-10-24 12:19 UTC, tarukosu commented on Documentation.ja/README_Slate.md
> +## スレートをコントロールする方法 ##
```suggestion
## スレート コントロールの使い方 ##
```

2019-10-24 12:19 UTC, tarukosu commented on Documentation.ja/README_Slate.md
> +スレートをコントロールする方法は、次の要素で構成されます:
```suggestion
スレート コントロールは、次の要素で構成されています:
```

2019-10-24 12:19 UTC, tarukosu commented on Documentation.ja/README_Slate.md
> +スレート コントロールには、スケーリングと回転用のバウンディング ボックス スクリプトが含まれています。バウンディング ボックスの詳細については、[バウンディング ボックスス](README_BoundingBox.md) ページを参照してください。
```suggestion
スレート コントロールには、スケーリングと回転用のバウンディング ボックス スクリプトが含まれています。バウンディング ボックスの詳細については、[バウンディング ボックス](README_BoundingBox.md) ページを参照してください。
```

2019-10-24 12:19 UTC, tarukosu commented on Documentation.ja/README_Slate.md
> +* **Close**: スレートを無効にする。
```suggestion
* **Close**: スレート オブジェクトを無効にする。
```

2019-10-24 12:19 UTC, tarukosu commented on Documentation.ja/README_Slate.md
> +* **Follow Me**: Toggles と orbital solver コンポーネントでユーザーをフォローさせることができます。
```suggestion
* **Follow Me**: スレート オブジェクトがユーザーを追いかけるようにするための orbital solver コンポーネントをトグルする。
```

2019-10-24 12:19 UTC, tarukosu commented on Documentation.ja/README_Slate.md
> +一般的に、 スクリプト `NearInteractionTouchable.cs` は `IMixedRealityTouchHandler` からのタッチイベントを受け取るために、必ず何からしらのオブジェクトにアタッチするこは必要です。
```suggestion
一般的に、`NearInteractionTouchable.cs` スクリプトは `IMixedRealityTouchHandler` からのタッチ イベントを受け取りたいすべてのオブジェクトにアタッチする必要があります。
```

2019-10-24 12:19 UTC, tarukosu commented on Documentation.ja/README_Slate.md
> +* `HandInteractionPan.cs` このスクリプトは、多関節のハンド入力を処理することにより、スレートの *ContentQuad* 上のコンテンツに触れたり移動させたりします。
```suggestion
* `HandInteractionPan.cs` このスクリプトは、多関節ハンドの入力を処理することにより、スレートの *ContentQuad* 上のコンテンツに触れたり移動したりできます。
```

2019-10-25 04:32 UTC, cindychen0204 commented
修正しました

2019-10-27 01:08 UTC, merged