InputSimulationService MRTKv2.1対応
HoloLabInc/MixedRealityToolkit-Unity pull request #59
Opened 2019-10-10 17:00 UTC by torikasyu

## Overview

MRTKv2.1対応

"default"は"規定"に変更しました。

https://www.microsoft.com/ja-jp/language/Search?&searchTerm=default&langID=412&Source=true&productid=551

## Changes
- Fixes: # .

## Verification
> This optional section is a place where you can detail the specific type of verification 
> you want from reviewers. For example, if you want reviewers to checkout the PR locally
> and validate the functionality of specific scenarios, provide instructions
> on the specific scenarios and what you want verified.
>
> If there are specific areas of concern or question feel free to highlight them here so
> that reviewers can watch out for those issues.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

2019-10-15 11:43 UTC, tarukosu requested changes
31 行目までレビューしました

2019-10-15 11:43 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +MRTK では、入力シミュレーションは既定で有効化されています。
デフォルトのほうがわかりやすいので、他のところはデフォルトで統一しているのですが、いかがでしょう。

2019-10-15 11:43 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +* __Platform(s)__ は、デフォルトで全ての _Editor_ プラットフォームを含みます。これは、サービスがキーボードとマウスの入力を思料するためです。
思料 -> 使用

2019-10-15 11:43 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
>  > 現時点では、どのタイプのプロファイルもアサインすることができます。別のプロファイルをサービスにアサインする場合は、必ず _Input Simulation_ タイプのプロファイルを使用してください。そうしないと機能しません。
この部分は新しいドキュメントだと消えていると思います。

2019-10-15 11:43 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +_Mixed Reality Toolkit > Utilities > Input Simulation_ メニューから、入力シミュレーションツール ウィンドウを有効化します。このウィンドウは、プレイモードの間、入力シミュレーションサービスの状態を提供します。
シミュレーションツール
-> シミュレーション ツール

2019-10-15 11:43 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +_Mixed Reality Toolkit > Utilities > Input Simulation_ メニューから、入力シミュレーションツール ウィンドウを有効化します。このウィンドウは、プレイモードの間、入力シミュレーションサービスの状態を提供します。
> 入力シミュレーションサービスの状態を提供します。

入力シミュレーションの状態へのアクセスを提供します。

2019-10-15 14:06 UTC, tarukosu requested changes

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +## 入力シミュレーションツール ウィンドウ
シミュレーションツール
-> シミュレーション ツール

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +基本的な手の配置をコントロールするエディタ内ボタンのプレファブは、入力シミュレーションサービスの __Indicators Prefab__ 配下のプロファイルで指定することができます。これは、オプションのユーティリティで、同じ機能には [input simulation tools window](#input-simulation-tools-window) からアクセスすることができます。
> 基本的な手の配置をコントロールするエディタ内ボタンのプレファブは、入力シミュレーションサービスの __Indicators Prefab__ 配下のプロファイルで指定することができます。

基本的な手の配置をコントロールするエディタ内ボタンのプレファブは、__Indicators Prefab__ 配下の入力シミュレーション プロファイルで指定することができます。

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +基本的な手の配置をコントロールするエディタ内ボタンのプレファブは、入力シミュレーションサービスの __Indicators Prefab__ 配下のプロファイルで指定することができます。これは、オプションのユーティリティで、同じ機能には [input simulation tools window](#input-simulation-tools-window) からアクセスすることができます。
```
> 同じ機能には [input simulation tools window](#input-simulation-tools-window) 

同じ機能には[入力シミュレーション ツール ウィンドウ](#入力シミュレーション-ツール-ウィンドウ) 
```

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +Hand icons show the state of the simulated hands:
ハンドアイコンは、シミュレーションされたハンドの状態を表します。

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +頭の動きは入力シミュレーションサービスでエミュレートされます。
シミュレーション サービス

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +## カメラを回転する
```
### カメラを回転させるには:
```

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +カメラの位置と回転角度は、ツールウインドウで明示的にセットすることもできます。__Reset__　ボタンでカメラを既定の状態にリセットすることができます。
ツール ウィンドウ

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
Camera rotation speed can be configured by changing the Mouse Look Speed setting in the input simulation profile.

Alternatively use the Look Horizontal/Look Vertical axes to rotate the camera (default: game controller right thumbstick).

この内容が抜けてますね

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +## カメラを移動する
```
### カメラを移動させるには:
```

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +## ハンドシミュレーションモード
```
## ハンド シミュレーション モード
```

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +[input simulation tools window](#input-simulation-tools-window) 内で、 __Hand Simulation Mode__ は、２つの異なる入力モデルの切り替えを行います。
```
[入力シミュレーション ツール ウィンドウ](#入力シミュレーション-ツール-ウィンドウ)内で、 __Hand Simulation Mode__ の設定は、2つの異なる入力モデルの切り替えを行います。
```

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +既定のモードは入力シミュレーションプロファイルでもセットできます。
シミュレーション プロファイル

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +__Left/Right Hand Manipulation Key__ （既定：左Shift/Space がそれぞれ 左手/右手 に対応）を押し続けてそれぞれの手をコントロールします。キーを押し続けている間、手が表示されます。マウスの動きで手を移動できます。Manipuration キーが押されなくなると、手は短い __Hand Hide Timeout__ の後に表示されなくなります。
```
__Left/Right Hand Manipulation Key__ （既定：左Shift/Space がそれぞれ 左手/右手 に対応）を押し続けてそれぞれの手をコントロールします。操作キーを押し続けている間、ハンドが表示されます。操作キーが押されなくなると、短い __Hand Hide Timeout__ の後にハンドは表示されなくなります。
```

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +[input simulation tools window](#input-simulation-tools-window) で手の表示を永続的に切り替えるには、 __Toggle Left/Right Hand Key__ （既定：T/Y が 左手/右手 に対応）を押してください。Toggle キーを再度押すと、再度手の表示を消すことができます。
```
ハンドは[入力シミュレーション ツール ウィンドウ](#入力シミュレーション-ツール-ウィンドウ)内、または __Toggle Left/Right Hand Key__ （既定：T/Y が 左手/右手 に対応）を押すことで、永続的に表示を切り替えられます。Toggle キーを再度押すと、再度手の表示を消すことができます。
```

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +マウスの動きは、ビュー内で手の動きとなります。手は、__mouse wheel__ を使って遠ざけたり近づけたりすることができます。
> 遠ざけたり近づけたり

カメラから遠ざけたり近づけたり

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +To rotate hands using the mouse, hold both the __Left/Right Hand Control Key__ (shift/space) _and_ the __Hand Rotate Button__ (default: right mouse button). Hand rotation speed can be configured by c
元の英語が残っちゃってます

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +マウスを使用して手を回転させるには、__Left / Right Hand Control Key__（シフト/スペース）_と_ __Hand Rotate Button__（既定：マウスの右ボタン）の両方を押します。入力シミュレーションプロファイルの __Mouse Hand Rotation Speed__ 設定を変更することにより、手の回転速度を設定できます。
シミュレーション プロファイル

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +全ての手の配置（手を既定の状態にリセットすることも含む）は[input simulation tools window](#input-simulation-tools-window)でも変更することができます。
```
[入力シミュレーション ツール ウィンドウ](#入力シミュレーション-ツール-ウィンドウ)
```

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +* __Hand Depth Multiplier__ は、マウススクロールホイールの深さの動きの感度を制御します。数値を大きくすると、手のズームが速くなります。
マウス スクロール ホイール

2019-10-15 14:06 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +1. [Input Simulation Profile](#enabling-the-input-simulation-service) で、__Hand Simulation Mode__ を _Gestures_ にすることにより、GGV のシミュレーションに切り替えることができます
```
> [Input Simulation Profile](#enabling-the-input-simulation-service)
```

```
[Input Simulation Profile](#入力シミュレーション-サービスの有効化)
```

2019-10-15 14:07 UTC, tarukosu commented
@torikasyu @tattichan 
hand は手ではなくハンドで統一したほうがわかりやすいと思ったのですが、どうでしょうか？

2019-10-18 02:30 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +MRTK では、入力シミュレーションは既定で有効化されています。
MSのランゲージポータルではすべて「既定」だったので、公式の翻訳として使ってもらう場合は既定なのかと思いました。現時点ではデフォルトに統一するということであればそうします。

2019-10-18 03:15 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +[input simulation tools window](#input-simulation-tools-window) 内で、 __Hand Simulation Mode__ は、２つの異なる入力モデルの切り替えを行います。
リンクは翻訳するんでしたでしょうか？

2019-10-18 03:19 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +[input simulation tools window](#input-simulation-tools-window) 内で、 __Hand Simulation Mode__ は、２つの異なる入力モデルの切り替えを行います。
あ、ページ内アンカーなので訳さないと飛ばないんですね。

2019-10-20 13:12 UTC, tarukosu requested changes

2019-10-20 13:12 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +_Mixed Reality Toolkit > Utilities > Input Simulation_ メニューから、入力シミュレーション ツール ウィンドウを有効化します。このウィンドウは、プレイモードの間、入力シミュレーションサービスの状態へのアクセスを提供します。
```suggestion
_Mixed Reality Toolkit > Utilities > Input Simulation_ メニューから、入力シミュレーション ツール ウィンドウを有効化します。このウィンドウは、プレイモードの間、入力シミュレーションの状態へのアクセスを提供します。
```

2019-10-20 13:12 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +[入力シミュレーション ツール ウィンドウ](#入力シミュレーション-ツール-ウィンドウ) でハンドの表示を永続的に切り替えるには、 __Toggle Left/Right Hand Key__ （デフォルト:T/Y が 左ハンド/右ハンド に対応）を押してください。Toggle キーを再度押すと、再度ハンドの表示を消すことができます。
```suggestion
ハンドは[入力シミュレーション ツール ウィンドウ](#入力シミュレーション-ツール-ウィンドウ)内、または __Toggle Left/Right Hand Key__ （デフォルト:T/Y が 左ハンド/右ハンド に対応）を押すことで、永続的に表示を切り替えられます。Toggle キーを再度押すと、再度ハンドの表示を消すことができます。
```

2019-10-20 13:12 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +1. [Input Simulation Profile](#enabling-the-input-simulation-service) で、__Hand Simulation Mode__ を _Gestures_ にすることにより、GGV のシミュレーションに切り替えることができます
```suggestion
1. [Input Simulation Profile](#入力シミュレーション-サービスの有効化) で、__Hand Simulation Mode__ を _Gestures_ にすることにより、GGV のシミュレーションに切り替えることができます
```

2019-10-22 09:42 UTC, tarukosu approved these changes

2019-10-22 11:58 UTC, merged