Feature/htk to mrtk porting guide.md
HoloLabInc/MixedRealityToolkit-Unity pull request #7
Opened 2019-08-28 00:14 UTC by YusukeSaitoHolo

## Overview
htk to mrtk porting guide.mdの日本語化

## Changes
- Fixes: # .

## Verification
> This optional section is a place where you can detail the specific type of verification 
> you want from reviewers. For example, if you want reviewers to checkout the PR locally
> and validate the functionality of specific scenarios, provide instructions
> on the specific scenarios and what you want verified.
>
> If there are specific areas of concern or question feel free to highlight them here so
> that reviewers can watch out for those issues.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

2019-08-28 00:16 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +﻿# HTK2017 から MRTK v2への移植ガイド
v2 のあとスペース？

2019-08-28 00:18 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> + の設定はシーン内の Main Camera オブジェクト上で変更されています。
改行が入っちゃってる

2019-08-28 00:19 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +Windows Mixed Reality Device Managerなどのプラットフォームサポートコンポーネントは、対応するサービスのデータプロバイダーに追加する必要があります。
Manager のあと半角スペース

2019-08-28 00:21 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| 設定                     | Main Camera を削除し、MixedRealityCameraParent / MixedRealityCamera / HoloLensCamera プレハブをシーンに追加します。 **あるいは**  Mixed Reality Toolkit > Configure > Apply Mixed Reality Scene Sett
Configure のあとの空白いらない？

2019-08-28 00:23 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +## 音声認識( Speech )
> 音声認識( Speech )

音声認識 (Speech)  
こっちのほうが見やすそうです

2019-08-28 00:24 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +## 音声認識( Speech )
Dictation なども同じ

2019-08-28 00:25 UTC, YusukeSaitoHolo commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +## 音声認識( Speech )
()内の空白はなしにします

2019-08-28 00:26 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| ボタン( Button )                     | [Interactable Objects](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit-Examples/UX/Readme/README_InteractableObjectExa
ボタン (Button)
でお願いします！

2019-08-28 00:26 UTC, YusukeSaitoHolo commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +Windows Mixed Reality Device Managerなどのプラットフォームサポートコンポーネントは、対応するサービスのデータプロバイダーに追加する必要があります。
「データプロバイダー」と「データプロバイダ」でゆれがあるので、こちらは「データプロバイダ」に統一します

2019-08-28 00:27 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| タガロング( Tagalong ) | [`RadialView`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.RadialView) あるいは [`Orbital`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.Orbital) [Solver](README_
カタカナにするなら、タグアロングですかね？

2019-08-28 00:29 UTC, tarukosu reviewed
Setup -> セットアップ
Configuration -> 設定
のほうがわかりやすいかも。

2019-08-28 00:32 UTC, YusukeSaitoHolo commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| タガロング( Tagalong ) | [`RadialView`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.RadialView) あるいは [`Orbital`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.Orbital) [Solver](README_
意味的にはTag-Alongなのですが、読み的にはタガロングだと以前忠告を受けた覚えがあります（誰か忘れました）。とりあえず私もタグアロングの表記の方が良いと思っているので、そちらに変更します。

2019-08-28 00:34 UTC, tarukosu commented
「コンフィギュレーション」でも良さそう

2019-08-28 00:38 UTC, YusukeSaitoHolo commented
Configuration -> コンフィギュレーション は、ちょっと直訳しすぎかなと思ってます。
ちょっとこの辺、ほかのメンバーの意見も聞きましょう。統一したほうがよいと思いますし。

2019-08-28 04:04 UTC, decoc requested changes

2019-08-28 04:04 UTC, tattichan commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +一部のイベントに関しては固有のイベントがなくなり、MRTK v2 では[MixedRealityInputAction](Input/InputActions.md) に含まれます。
含まれます。のあとに余分スペース

2019-08-28 04:04 UTC, tattichan commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +## 空間認識・空間マッピング
空間認識・空間マッピング (Spatial awareness / mapping) となっている方がいいですね

2019-08-28 05:27 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +## 音声認識(Speech)
@tattichan 
音声認識と ( の間にスペース入れますよね？

2019-08-28 05:29 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| 設定             | 認識するキーワードをSpeechInputSource のインスペクタで設定します。| キーワードは [Mixed Reality Speech Commands Profile](Input/Speech.md) で設定されます。 |
> キーワードは [Mixed Reality Speech Commands Profile](Input/Speech.md) で設定されます。

キーワードは [Mixed Reality Speech Commands Profile](Input/Speech.md) で設定します。

2019-08-28 05:31 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| HTK 2017 |  MRTK v2  | Action への紐付け |
「対応付け」のほうがいいかも？

2019-08-28 05:43 UTC, tattichan commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +## 音声認識(Speech)
入れたほうがいいですね

2019-08-29 01:50 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| セットアップ                     | Sharing service の場合: Sharing プレハブをシーンに追加します。<br>UNet の場合: SharingWithUNET example を使用してください。 | 更新中の状態です。 |
<br> を入れているのは、読みやすさを考慮してでしょうか？

2019-08-29 02:04 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| セットアップ                     | Sharing service の場合: Sharing プレハブをシーンに追加します。<br>UNet の場合: SharingWithUNET example を使用してください。 | 更新中の状態です。 |
たしかに、あったほうが良さそうですね

2019-08-29 02:04 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +これらの動作は Input Actions プロファイルで指定され、Controller Mapping profile 内で特定のコントローラーやプラットフォームに対応付けされます。`OnInputDown` のようなイベントは MixedRealityInputAction タイプをチェックする必要があります。
対応付けされる　－＞　対応付けられる　のほうが自然ですかね？

2019-08-29 02:04 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| 設定             | シーン内の個々のスクリプト上でインスペクタ内に構成されています。 | 以下に示す Mixed Reality Input System プロファイルおよび関連するプロファイルが構成されています。 |
スクリプト上でインスペクタ内に構成されています。
->　スクリプトのインスペクタで設定されます

プロファイルおよび関連するプロファイルが構成されています。
-> プロファイルおよび関連するプロファイルによって設定されます

という感じでどうでしょうか

2019-08-29 02:04 UTC, tarukosu commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| 設定             | Camera settings の構成がプレハブインスタンスで実行されます。 | [Mixed Reality Camera Profile](xref:Microsoft.MixedReality.Toolkit.MixedRealityCameraProfile) にて Camera settings が構成されます。 |
> Camera settings の構成がプレハブインスタンスで実行されます。 

Camera の設定は、プレハブインスタンスにて行います。

 >[Mixed Reality Camera Profile](xref:Microsoft.MixedReality.Toolkit.MixedRealityCameraProfile) にて Camera settings が構成されます。

[Mixed Reality Camera Profile](xref:Microsoft.MixedReality.Toolkit.MixedRealityCameraProfile) にて Camera の設定を行います。

2019-08-29 02:15 UTC, YusukeSaitoHolo commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +| セットアップ                     | Sharing service の場合: Sharing プレハブをシーンに追加します。<br>UNet の場合: SharingWithUNET example を使用してください。 | 更新中の状態です。 |
ですですー

2019-08-29 02:17 UTC, YusukeSaitoHolo commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +これらの動作は Input Actions プロファイルで指定され、Controller Mapping profile 内で特定のコントローラーやプラットフォームに対応付けされます。`OnInputDown` のようなイベントは MixedRealityInputAction タイプをチェックする必要があります。
んー、紐づけられる→対応付けられるに直したときに、違和感が生じたので直してみたんです。
このレベルになると、そんなに重要じゃない部分に対する沼にはまっているような気がしています。

2019-09-02 08:51 UTC, YusukeSaitoHolo commented on Documentation.ja/HTKToMRTKPortingGuide.md
> +一部のイベントに関しては固有のイベントがなくなり、MRTK v2 では[MixedRealityInputAction](Input/InputActions.md) に含まれます。
修正しましたー

2019-09-03 04:23 UTC, tarukosu approved these changes

2019-09-05 02:11 UTC, merged