[WIP] README_Solver の翻訳
HoloLabInc/MixedRealityToolkit-Unity pull request #71
Opened 2019-10-26 08:28 UTC by tarukosu

2019-11-04 13:18 UTC, tarukosu commented
長いので、前半後半に分けてレビュー&マージをしようと思います

2019-11-05 09:55 UTC, HiromuKato requested changes

2019-11-05 09:55 UTC, HiromuKato commented on Documentation.ja/README_Solver.md
> +* [`Momentum`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.Momentum): 他のソルバーやコンポーネントによって動かされるオブジェクトに対して、慣性や弾性をシミュレーションするために、加速度、速度、摩擦を適用します。
```suggestion
* [`Momentum`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.Momentum): 他のソルバーやコンポーネントによって動かされるオブジェクトに対して、運動量や弾性をシミュレーションするために、加速度、速度、摩擦を適用します。
```

2019-11-05 09:55 UTC, HiromuKato commented on Documentation.ja/README_Solver.md
> +> ソルバーシステムの使い方の例は、**SolverExamples.scene** ファイルにて見つけることができます。
```suggestion
> ソルバー システムの使い方の例は、**SolverExamples.scene** ファイルにて見つけることができます。
```

2019-11-05 09:55 UTC, HiromuKato commented on Documentation.ja/README_Solver.md
> +    * どちらの手（左手、右手、両手）を優先するかを選択するには、`TrackedHandedness` プロパティを使用します。
利き手はどちらかという感じか、好みはどちらかというニュアンスに感じられたので優先とまで言っていいかちょっと悩ましいです。

2019-11-05 09:55 UTC, HiromuKato commented on Documentation.ja/README_Solver.md
> +    * どちらの手（左手、右手、両手）を優先するかを選択するには、`TrackedHandedness` プロパティを使用します。
同上

2019-11-05 09:55 UTC, HiromuKato commented on Documentation.ja/README_Solver.md
> +すべてのソルバーは抽象基底クラスである [`Solver`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.Solver) を継承しなければなりません。Solver の拡張に主に必要となるのは、`SolverUpdate` メソッドのオーバーライドに関するものです。このメソッドで、開発者は継承された `GoalPosition`、`G
コンシューマーは利用者でもいいかもしれないですね。
あと、参照座標系という訳でいいのかは判断できませんでした。

2019-11-07 11:00 UTC, tarukosu commented on Documentation.ja/README_Solver.md
> +    * どちらの手（左手、右手、両手）を優先するかを選択するには、`TrackedHandedness` プロパティを使用します。
両手が使える場合にどちらを選ぶかなので、「優先」でよいと思いました

2019-11-07 11:01 UTC, tarukosu commented on Documentation.ja/README_Solver.md
> +すべてのソルバーは抽象基底クラスである [`Solver`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.Solver) を継承しなければなりません。Solver の拡張に主に必要となるのは、`SolverUpdate` メソッドのオーバーライドに関するものです。このメソッドで、開発者は継承された `GoalPosition`、`G
たしかに、利用者がいいですね

2019-11-07 11:01 UTC, tarukosu commented on Documentation.ja/README_Solver.md
> +すべてのソルバーは抽象基底クラスである [`Solver`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.Solver) を継承しなければなりません。Solver の拡張に主に必要となるのは、`SolverUpdate` メソッドのオーバーライドに関するものです。このメソッドで、開発者は継承された `GoalPosition`、`G
```suggestion
すべてのソルバーは抽象基底クラスである [`Solver`](xref:Microsoft.MixedReality.Toolkit.Utilities.Solvers.Solver) を継承しなければなりません。Solver の拡張に主に必要となるのは、`SolverUpdate` メソッドのオーバーライドに関するものです。このメソッドで、開発者は継承された `GoalPosition`、`GoalRotation`、`GoalScale` プロパティを望ましい値に更新すべきです。さらに、`SolverHandler.TransformTarget` を、利用者が望む参照座標系として利用すると、たいていの場合に役に立つでしょう。
```

2019-11-07 15:07 UTC, HiromuKato approved these changes

2019-11-08 08:07 UTC, merged