README_Interactable.md の翻訳 #75
HoloLabInc/MixedRealityToolkit-Unity pull request #80
Opened 2019-10-27 09:16 UTC by hatsunea

2019-11-03 23:36 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +1) 複数のGameObjectを対象とした [ビジュアル テーマ](VisualThemes.md)
```suggestion
1) 複数の GameObjec tを対象とした [ビジュアル テーマ](VisualThemes.md)
```

2019-11-03 23:44 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*States* は [ScriptableObject](https://docs.unity3d.com/Manual/class-ScriptableObject.html) パラメータで、[Interactable プロファイル](#Interactable-プロファイル)と[ビジュアル テーマ](VisualThemes.md)に対して、押下や監視などの相互作用フェーズを定義します。
```suggestion
*States* は [Interactable プロファイル](#interactable-プロファイル)と[ビジュアル テーマ](VisualThemes.md)で利用する、押された、見られている、といったインタラクションのフェーズを定義する [ScriptableObject](https://docs.unity3d.com/Manual/class-ScriptableObject.html) パラメータです。
```

2019-11-03 23:46 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +# Interactable (対話型 : インターラクティブル)
```suggestion
# Interactable (インタラクタブル、インタラクション可能な)
```

2019-11-03 23:51 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +[`Interactable`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable) コンポーネントは、あらゆるオブジェクトを容易に対話可能にし、入力に応答するオールインワンコンテナです。Interactable は、タッチ、ハンド レイ、音声認識などを含むすべてのタイプの入力のためのキャッチオールとして機能し、これらの相互作用を [イベント
```suggestion
[`Interactable`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable) コンポーネントは、あらゆるオブジェクトを容易に *interactable(インタラクション可能)* にし、入力に応答させるオールインワン コンテナです。Interactable は、タッチ、ハンド レイ、音声などを含むすべてのタイプの入力のためのキャッチオールとして機能し、これらのインタラクションを [イベント](#events) および [Visual Themes (ビジュアル テーマ)](visualthemes.md) の応答に流し込みます。このコンポーネントを使用すると、ボタンの作成やフォーカスによるオブジェクトの色の変更などを簡単に行うことができます。
```

2019-11-03 23:56 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +[**DefaultInteractableStates**](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/States/DefaultInteractableStates.asset
```suggestion
[**DefaultInteractableStates**](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/States/DefaultInteractableStates.asset) は MRTK にそのまま含まれている、*Interactable* コンポーネントのデフォルトのパラメーターです。
```

2019-11-03 23:58 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*DefaultInteractableStates* アセットには4つの状態が含まれており、[`InteractableStates`](xref:Microsoft.MixedReality.Toolkit.UI.InteractableStates) ステート モデルの実装を利用します。
```suggestion
*DefaultInteractableStates* アセットには4つのステートが含まれており、[`InteractableStates`](xref:Microsoft.MixedReality.Toolkit.UI.InteractableStates) ステート モデルの実装を利用します。
```

2019-11-03 23:58 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Default**: 何も起こっていません。これは最も独立したベース状態です。
```suggestion
* **Default**: 何も起こっていません。これは最も独立したベース ステートです。
```

2019-11-04 00:06 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Focus**: オブジェクトが指定されています。これは単一の状態で、他の状態は現在設定されていませんが、ランクはDefaultになります。
```suggestion
* **Focus**: オブジェクトがポイントされています。これは単一のステートで、他のステートは現在設定されていませんが、Default より優先されます。
```

2019-11-04 00:11 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Press**: オブジェクトをポイントし、ボタンまたはハンドを押しています。Press 状態は Default と Focus をランク付けします。この状態は、フィジカルでの押す動作に対するフィードバックとしても設定されます。
```suggestion
* **Press**: オブジェクトがポイントされており、ボタンまたはハンドが押しています。Press ステートは Default と Focus よりも優先されます。このステートは、Physical Press (物理的な押下) に対するフォールバックとしても設定されます。
```

2019-11-04 00:14 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Disabled**: このボタンはインタラクティブであってはなりません。また、何らかの理由でこのボタンが現在使用できないことが視覚的なフィードバックによってユーザーに通知されます。理論的には、disabled 状態には他のすべての状態を含めることができますが、Enabled がオフの場合は、Disabled 状態が他のすべての状態より優先されます。
```suggestion
* **Disabled**: このボタンはインタラクティブであってはなりません。また、何らかの理由でこのボタンが現在使用できないことが視覚的なフィードバックによってユーザーに通知されます。理論的には、Disabled ステートには他のすべての状態を含めることができますが、Enabled がオフの場合は、Disabled ステートが他のすべてのステートより優先されます。
```

2019-11-04 00:14 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +リスト内の順序に応じて、ビット値 (#) が状態に割り当てられます。
```suggestion
リスト内の順序に応じて、ビット値 (#) がステートに割り当てられます。
```

2019-11-08 10:25 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +> ただし、テーマの駆動に使用できる Interactable の状態は17ありますが、一部は他のコンポーネントによって駆動されるように設計されています。以下は、機能が組み込まれているもののリストです。
```suggestion
> ただし、テーマの駆動に使用できる Interactable のステートは17ありますが、一部は他のコンポーネントによって駆動されるように設計されています。以下は、そのようなステートで、機能が組み込まれているもののリストです。
```

2019-11-08 10:26 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +> * VoiceCommand: 音声コマンドを使用して、Interactable をトリガーしました.
```suggestion
> * VoiceCommand: Interactable をトリガーするのに音声コマンドが使われました。
```

2019-11-08 10:28 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +> * PhysicalTouch: タッチ入力が検出されました。 [`NearInteractionTouchable`](xref:Microsoft.MixedReality.Toolkit.Input.NearInteractionTouchable) を使用して有効にしてください。
```suggestion
> * PhysicalTouch: タッチ入力が現在検出されています。[`NearInteractionTouchable`](xref:Microsoft.MixedReality.Toolkit.Input.NearInteractionTouchable) を使用して有効にしてください。
```

2019-11-08 10:29 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +> * Grab: ハンド入力がオブジェクトの境界をグラブしています。[`NearInteractionGrabbable`](xref:Microsoft.MixedReality.Toolkit.Input.NearInteractionGrabbable) を使用して有効にしてください。
```suggestion
> * Grab: ハンドが現在オブジェクトの境界内でグラブしています。[`NearInteractionGrabbable`](xref:Microsoft.MixedReality.Toolkit.Input.NearInteractionGrabbable) を使用して有効にしてください。
```

2019-11-08 10:30 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +Interactable を有効にするかどうかを切り替えます。これは、コードの [`Interactable.IsEnabled`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.IsEnabled) に対応します。
```suggestion
Interactable が開始時に有効かどうかを切り替えます。これは、コードの [`Interactable.IsEnabled`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.IsEnabled) に対応します。
```

2019-11-08 10:38 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*Interactable* の enabled プロパティーは、GameObject/Component (例:SetActiveなど) で設定された enabled プロパティーとは異なります。GameObject または *Interactable* MonoBehavior を無効にすると、入力、ビジュアル テーマ、イベントなど、クラス内のすべてのものの実行が無効になります。[`Inte
```suggestion
*Interactable* の enabled プロパティは、GameObject/Component で (SetActive などによって) 設定された enabled プロパティとは異なります。GameObject または *Interactable* MonoBehavior を無効にすると、入力、ビジュアル テーマ、イベントなど、クラス内のすべてのものの実行が無効になります。[`Interactable.IsEnabled`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.IsEnabled) を介して無効にすると、ほとんどの入力処理が無効になり、関連する入力ステートがリセットされます。ただし、クラスはすべてのフレームで実行され、無視される入力イベントを受け取ります。これは、Interactable をビジュアル テーマを介して disabled ステートで表示する場合に便利です。この典型的な例は、すべての必須入力フィールドが完了するのを待つ送信ボタンです。
```

2019-11-08 10:40 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +入力設定またはコントローラマッピングプロファイルから、*Interactable* コンポーネントが反応する [input action](./Input/InputActions.md) を選択します。
```suggestion
入力設定またはコントローラー マッピング プロファイルから、*Interactable* コンポーネントが反応する [input action](./Input/InputActions.md) を選択します。
```

2019-11-08 10:41 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +このプロパティは、コードの実行時に [`Interactable.InputAction`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.InputAction) を使用して設定できます。
```suggestion
このプロパティは、実行時に [`Interactable.InputAction`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.InputAction) を使用してコードで設定できます。
```

2019-11-08 10:44 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +true の場合、選択した [input action](./Input/InputActions.md) のグローバル入力リスナーとしてコンポーネントがマークされます。デフォルトの動作は false で、入力はこの *Interactable* collider/GameObject のみに制限されます。
```suggestion
true の場合、選択した [input action](./Input/InputActions.md) のグローバル入力リスナーとしてコンポーネントがマークされます。デフォルトの動作は false で、この *Interactable* collider/GameObject のみへの入力に制限されます。
```

2019-11-08 10:44 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +このプロパティは、コードの実行時に [`Interactable.IsGlobal`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.IsGlobal) を使用して設定できます。
```suggestion
このプロパティは、実行時に [`Interactable.IsGlobal`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.IsGlobal) を使用してコードで設定できます。
```

2019-11-08 10:47 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +音声対話のための OnClick イベントをトリガするには、MRTK Speech Commands Profileの [Speech command](./Input/Speech.md) を使用します。
```suggestion
音声対話で OnClick イベントをトリガーするための、MRTK Speech Commands Profile で設定された [Speech command (音声コマンド)](./Input/Speech.md) です。
```

2019-11-08 10:47 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +このプロパティは、コードの実行時に [`Interactable.VoiceCommand`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.VoiceCommand) を使用して設定できます。
```suggestion
このプロパティは、実行時に [`Interactable.VoiceCommand`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.VoiceCommand) を使用してコードで設定できます。
```

2019-11-08 10:51 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +true の場合、音声コマンドは、ポインタからすでにフォーカスがある場合にのみ、*Interactable* をアクティブにします。false の場合、*Interactable* は選択した音声コマンドのグローバルリスナーとして機能します。複数のグローバルスピーチリスナーをシーン内に編成するのは困難な場合があるため、既定値の動作は true です。
```suggestion
true の場合、音声コマンドは、ポインタからすでにフォーカスがある場合にのみ、*Interactable* を作動させます。false の場合、*Interactable* は選択した音声コマンドのグローバル リスナーとして機能します。複数のグローバル スピーチ リスナーをシーン内で整理するのは困難な場合があるため、デフォルトの動作は true です。
```

2019-11-08 10:51 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +このプロパティは、コードの実行時に [`Interactable.VoiceRequiresFocus`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.VoiceRequiresFocus) を使用して設定できます。
```suggestion
このプロパティは、実行時に [`Interactable.VoiceRequiresFocus`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.VoiceRequiresFocus) を使用してコードで設定できます。
```

2019-11-08 10:58 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +このプロパティは、選択ロジックを定義します。*Interactable* がクリックされると、次の *Dimension* レベルに反復されます。*Dimensions* はランクと似ており、入力以外の状態 (例: フォーカス、押下など) を定義します。これらは、ボタンに関連付けられたトグル状態やその他のマルチランク状態を定義する場合に便利です。現在のディメンションレベルは、`Interacta
```suggestion
このプロパティは、選択ロジックを定義します。*Interactable* がクリックされると、次の *Dimension* レベルに反復されます。*Dimensions* はランクと似ており、入力 (フォーカス、押下など) の外側の状態を定義します。これらは、ボタンに関連付けられたトグル状態やその他のマルチランク状態を定義する場合に便利です。現在の Dimension レベルは、`Interactable.DimensionIndex` で取得できます。
```

2019-11-08 10:59 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Button** - *Dimensions* = 1 の場合、*Interactable* をクリック可能
```suggestion
* **Button** - *Dimensions* = 1、シンプルなクリック可能な *Interactable*
```

2019-11-08 11:01 UTC, tarukosu requested changes
87 行目まで見ました

2019-11-09 01:00 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Toggle** - *Dimensions* = 2 の場合、*Interactable* は *on*/*off* 状態を交互に切り替えます
```suggestion
* **Toggle** - *Dimensions* = 2、*Interactable* は *on*/*off* 状態を交互に切り替えます
```

2019-11-09 01:01 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Multi-dimension** - *Dimensions* >= 3 の場合、クリックするたびに現在の dimension level に 1 加算します。ボタンの状態をリストなどに定義する場合に便利です。
```suggestion
* **Multi-dimension** - *Dimensions* >= 3、クリックするたびに現在の dimension level に 1 加算します。ボタンの状態をリストなどに定義する場合に便利です。
```

2019-11-09 01:03 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*Interactable* では、*Dimension* ごとに複数のテーマを定義することもできます。たとえば、*SelectionMode=Toggle* の場合、あるテーマは *Interactable* が *deselected* のときに適用され、別のテーマはコンポーネントが *selected* のときに適用されます。
```suggestion
*Interactable* では、*Dimension* ごとに複数のテーマを定義することもできます。たとえば、*SelectionMode=Toggle* の場合、あるテーマを *Interactable* が *deselected* のときに適用させ、別のテーマをコンポーネントが *selected* のときに適用させられます。
```

2019-11-09 01:04 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
>  **Selection Mode**
```suggestion
**Selection Mode (選択モード)**
```

2019-11-09 09:34 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +現在の選択モードは、実行時に [`Interactable.ButtonMode`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.ButtonMode) を使用して照会できます。実行時にモードを更新するには、 [`Interactable.Dimensions`](xref:Microsoft.MixedReality.Toolkit.
```suggestion
現在の選択モードは、実行時に [`Interactable.ButtonMode`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.ButtonMode) を使用して照会できます。実行時にモードを更新するには、 [`Interactable.Dimensions`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.Dimensions) プロパティを使用して、目的の機能に一致させます。さらに、*Toggle* および *Multi-Dimension* モードで便利な現在の寸法には、[`Interactable.CurrentDimension`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.CurrentDimension) からアクセスできます。
```
```suggestion
現在の選択モードは、実行時に [`Interactable.ButtonMode`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.ButtonMode) を使用して照会できます。実行時にモードを更新するには、 [`Interactable.Dimensions`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.Dimensions) プロパティを使用して、目的の機能に一致させます。さらに、*Toggle* および *Multi-Dimension* モードで役立つ、現在の Dimension には、[`Interactable.CurrentDimension`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.CurrentDimension) からアクセスできます。
```

2019-11-09 09:35 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +現在の選択モードは、実行時に [`Interactable.ButtonMode`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.ButtonMode) を使用して照会できます。実行時にモードを更新するには、 [`Interactable.Dimensions`](xref:Microsoft.MixedReality.Toolkit.
```suggestion
現在の選択モードは、実行時に [`Interactable.ButtonMode`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.ButtonMode) を使用して照会できます。実行時にモードを更新するには、 [`Interactable.Dimensions`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.Dimensions) プロパティを使用して、目的の機能に一致させます。さらに、*Toggle* および *Multi-Dimension* モードで役立つ、現在の Dimension には、[`Interactable.CurrentDimension`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.CurrentDimension) からアクセスできます。
```

2019-11-09 09:42 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*Profiles*は、GameObject と [ビジュアル テーマ](VisualThemes.md) の間の関係を作成するアイテムです。プロファイルは、 [state change occurs](#general-入力設定) 時にテーマによって操作されるコンテンツを定義します。
```suggestion
*Profiles* は、GameObject と [ビジュアル テーマ](VisualThemes.md) の間の関係を作成するアイテムです。プロファイルは、[ステートの変更が起こる](#general-入力設定) 時にテーマによって操作されるコンテンツを定義します。
```

2019-11-09 09:45 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +テーマはマテリアルとよく似ています。これらは、現在の状態に基づいてオブジェクトに割り当てられるプロパティのリストを含むスクリプト可能なオブジェクトです。テーマも再利用可能で、複数の *Interactable* UX オブジェクトに割り当てることができます。
```suggestion
テーマはマテリアルのような働きをします。これらは、現在の状態に基づいてオブジェクトに割り当てられるプロパティのリストを含むスクリプタブル オブジェクトです。テーマも再利用可能で、複数の *Interactable* UX オブジェクトに割り当てることができます。
```

2019-11-09 09:45 UTC, tarukosu reviewed
101 行目まで見ました

2019-11-09 12:21 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +すべての *Interactable* コンポーネントには、コンポーネントが単純に選択されたときに起動する *OnClick* イベントがあります。ただし、*Interactable* は、*OnClick* 以外の入力イベントの検出にも使用できます。
```suggestion
すべての *Interactable* コンポーネントには、コンポーネントが単純に選択されたときに発火する *OnClick* イベントがあります。ただし、*Interactable* は、*OnClick* 以外の入力イベントの検出にも使用できます。
```

2019-11-09 12:25 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +イベントレシーバ定義の新しいタイプを追加するには、[*Add Event*] ボタンをクリックします。追加したら、目的のイベントのタイプを選択します。
```suggestion
Event Receiver 定義の新しいタイプを追加するには、[*Add Event*] ボタンをクリックします。追加したら、目的のイベントのタイプを選択します。
```

2019-11-09 12:28 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +さまざまなタイプの入力に応答するイベント受信側には、さまざまなタイプがあります。MRTK には、次のレシーバーが同梱されています。
```suggestion
さまざまなタイプの入力に応答する、さまざまなタイプのイベント レシーバーがあります。MRTK には、次のレシーバーが同梱されています。
```

2019-11-09 12:29 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*トリガー イベント レシーバーの例*
```suggestion
*Toggle Event Receiver の例*
```

2019-11-09 12:38 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> + [`InteractableReceiver`](xref:Microsoft.MixedReality.Toolkit.UI.InteractableReceiver) コンポーネントを使用すると、イベントをsource *Interactable* コンポーネントの外部で定義できます。*InteractableReceiver* は、別の *Interactable* によって開始されたフ
```suggestion
 [`InteractableReceiver`](xref:Microsoft.MixedReality.Toolkit.UI.InteractableReceiver) コンポーネントを使用すると、元となる *Interactable* コンポーネントの外部でイベントを定義できます。*InteractableReceiver* は、別の *Interactable* によって発火されるフィルターされたイベント タイプをリッスンします。*Interactable* プロパティが直接割り当てられていない場合、*Search Scope* プロパティは、自身、親、または、子 GameObject のどの方向で *InteractableReceiver* がイベントをリッスンするかを定義します。
```

2019-11-09 12:43 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +[`InteractableReceiverList`](xref:Microsoft.MixedReality.Toolkit.UI.InteractableReceiverList) も同じように動作しますが、一致するイベントのリストが表示されます。
```suggestion
[`InteractableReceiverList`](xref:Microsoft.MixedReality.Toolkit.UI.InteractableReceiverList) も同じように動作しますが、マッチするイベントがリストとなっています。
```

2019-11-09 12:44 UTC, tarukosu reviewed
134 行目まで

2019-11-09 12:58 UTC, hatsunea commented on Documentation.ja/README_Interactable.md
> +* **Toggle** - *Dimensions* = 2 の場合、*Interactable* は *on*/*off* 状態を交互に切り替えます
「= 1 の場合」と同様に「= 2 の場合」の方がよいのではないでしょうか？

2019-11-09 12:59 UTC, hatsunea commented on Documentation.ja/README_Interactable.md
> +* **Multi-dimension** - *Dimensions* >= 3 の場合、クリックするたびに現在の dimension level に 1 加算します。ボタンの状態をリストなどに定義する場合に便利です。
「= 1 の場合」と同様に「>= 3 の場合」の方がよいのではないでしょうか？

2019-11-09 13:39 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Toggle** - *Dimensions* = 2 の場合、*Interactable* は *on*/*off* 状態を交互に切り替えます
「= 2 の場合」とすると Toggle で Dimension が 2 じゃない場合もあるようにも読めるので、ちょっとわかりづらいかと思いました

2019-11-09 22:12 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +1) [`ReceiverBase`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBase) クラスを拡張して、イベント タイプのドロップダウンリストに表示されるカスタム イベントを作成します。Unity イベントはデフォルトで提供されますが、追加の Unity イベントを追加したり、Unity イベントを非表示に設定したりすることができます。
```suggestion
1) [`ReceiverBase`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBase) クラスを拡張して、イベント タイプのドロップダウン リストに表示されるカスタム イベントを作成します。Unity イベントはデフォルトで提供されますが、追加の Unity イベントを追加したり、Unity イベントを非表示に設定したりすることができます。この機能を使用すると、プロジェクトにおいてデザイナーはエンジニアと協力し、デザイナーがエディターで設定できるカスタム イベントを作成できます。
```

2019-11-09 22:14 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +1) [`ReceiverBaseMonoBehavior`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBaseMonoBehavior) クラスを拡張して、*Interactable* または別のオブジェクトに配置できる完全にカスタムなイベントコンポーネントを作成します。[`ReceiverBaseMonoBehavior`](xref:M
```suggestion
1) [`ReceiverBaseMonoBehavior`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBaseMonoBehavior) クラスを拡張して、*Interactable* または別のオブジェクトに配置できる完全にカスタムなイベント コンポーネントを作成します。[`ReceiverBaseMonoBehavior`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBaseMonoBehavior) は、*Interactable* を参照して状態の変化を検出します。
```

2019-11-09 22:15 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
>  **States**
```suggestion
**States (ステート)**
```

2019-11-09 22:16 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
>  **Enabled**
```suggestion
**Enabled (有効)**
```

2019-11-09 22:17 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
>  **Input Actions**
```suggestion
**Input Actions (入力アクション)**
```

2019-11-09 22:17 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
>  **IsGlobal**
```suggestion
**IsGlobal (グローバルである)**
```

2019-11-09 22:17 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
>  **Requires Focus**
```suggestion
**Requires Focus (フォーカスが必要)**
```

2019-11-09 22:19 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +`MixedRealityToolkit.Examples` 配下の [`CustomInteractablesReceiver`](xref:Microsoft.MixedReality.Toolkit.UI) クラスは、*Interactable* に関するステータス情報を表示し、カスタムイベントレシーバの作成例となります。
```suggestion
`MixedRealityToolkit.Examples` 配下の [`CustomInteractablesReceiver`](xref:Microsoft.MixedReality.Toolkit.UI) クラスは、*Interactable* に関するステータス情報を表示し、カスタム イベント レシーバの作成例となります。
```

2019-11-09 22:22 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +次のメソッドは、カスタムイベントレシーバの作成時にオーバーライドまたは実装する場合に便利です。 [`ReceiverBase.OnUpdate()`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBase) は、状態パターン/遷移の検出に使用できる抽象メソッドです。さらに、[`ReceiverBase.OnVoiceCommand()`](xre
```suggestion
次のメソッドは、カスタム イベント レシーバーの作成時にオーバーライドまたは実装する場合に便利です。 [`ReceiverBase.OnUpdate()`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBase) は、ステートのパターン/遷移の検出に使用できる抽象メソッドです。さらに、[`ReceiverBase.OnVoiceCommand()`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBase) および [`ReceiverBase.OnClick()`](xref:Microsoft.MixedReality.Toolkit.UI.ReceiverBase) メソッドは、*Interactable* が選択されている場合にカスタム イベント ロジックを作成するのに便利です。
```

2019-11-09 22:25 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*ReceiverBase* スクリプトは、 [`InspectorField`](xref:Microsoft.MixedReality.Toolkit.Utilities.Editor.InspectorField) 属性を使用して Inspector (インスペクタ) にカスタムプロパティを公開します。次に、Vector3 のツールチップとラベル情報を持つカスタム プロパティの例を示します
```suggestion
*ReceiverBase* スクリプトは、 [`InspectorField`](xref:Microsoft.MixedReality.Toolkit.Utilities.Editor.InspectorField) 属性を使用して Inspector (インスペクター) にカスタム プロパティを公開します。次に、Vector3 のツールチップとラベル情報を持つカスタム プロパティの例を示します。このプロパティは、*Interactable* GameObject が選択され、関連付けられた *Event Receiver* タイプが追加されている場合に、インスペクターで設定可能として表示されます。
```

2019-11-09 22:26 UTC, tarukosu reviewed
193行目まで

2019-11-09 22:30 UTC, tarukosu commented
@hatsunea 
コードのコメント部分も翻訳していただけますか？

2019-11-09 22:34 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* [Speech (音声 コマンド)](./Input/Speech.md)
```suggestion
* [Speech Commads (音声 コマンド)](./Input/Speech.md)
```

2019-11-09 22:34 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* [Button (ボタン)](README_Button.md)
```suggestion
* [Buttons (ボタン)](README_Button.md)
```

2019-11-10 05:13 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> + **Selection Mode (選択モード)**
```suggestion
**Selection Mode (選択モード)**
```

2019-11-10 05:20 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +入力イベントを受信するように構成された GameObject に *Interactable* コンポーネントを追加するだけで、簡単なボタンを作成することができます。入力を受け取ためのコライダがついていたり子供がいたりします。Unity UI ベースの GameObject で *Interactable* を使用する場合は、Canvas GameObject の下に配置する必要があります。
```suggestion
入力イベントを受信するように構成された GameObject に *Interactable* コンポーネントを追加するだけで、簡単なボタンを作成することができます。入力を受け取るために自身または子要素にコライダーを持っていることがあります。Unity UI ベースの GameObject で *Interactable* を使用する場合は、Canvas GameObject の下に配置する必要があります。
```

2019-11-10 05:24 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +> 押下可能な [Button (ボタン)](README_Button.md) を作成するには、コンポーネントが必要です。さらに、 `PhysicalPressEventRouter` コンポーネントは、押下イベントを *Interactable* コンポーネントに転送するために必要です。
```suggestion
> 押下可能な [Button (ボタン)](README_Button.md) を作成するには、`PressableButton` コンポーネントが必要です。さらに、`PhysicalPressEventRouter` コンポーネントは、押下イベントを *Interactable* コンポーネントに転送するために必要です。
```

2019-11-10 05:30 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +ボタンをトグル可能にするには、[`Selection Mode`](xref:Microsoft.MixedReality.Toolkit.UI.SelectionModes) フィールドに `Toggle` と入力します。*Profiles* セクションでは、*Interactable* がオンになっている場合に使用されるプロファイルごとに、トグルされた新しいテーマが追加されます。
```suggestion
ボタンをトグル可能にするには、[`Selection Mode`](xref:Microsoft.MixedReality.Toolkit.UI.SelectionModes) フィールドを `Toggle` タイプに変更します。*Profiles* セクションでは、それぞれのプロファイルに、*Interactable* がトグル オンになっている場合に使用される新しいトグル用のテーマが追加されます。
```

2019-11-10 05:33 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +While the [`SelectionMode`](xref:Microsoft.MixedReality.Toolkit.UI.SelectionModes) が `Toggle` に設定されている場合、*IsToggled* チェックボックスを使用して、実行時初期化時のコントロールのデフォルト値を設定できます。
```suggestion
[`SelectionMode`](xref:Microsoft.MixedReality.Toolkit.UI.SelectionModes) が `Toggle` に設定されている場合、*IsToggled* チェック ボックスを使用して、実行時初期化時のコントロールのデフォルト値を設定できます。
```

2019-11-10 05:34 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*CanSelect* は、*Interactable* が *off* から *on* になることを意味し、*CanDeselect* はその逆を意味します。
```suggestion
*CanSelect* は、*Interactable* が *off* から *on* に遷移できることを意味し、*CanDeselect* はその逆を意味します。
```

2019-11-10 05:39 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +通常、トグルボタンのリストがあり、一度にアクティブにできるのは1つだけです。これはラジアルセットまたはラジオボタンなどとも呼ばれます。
```suggestion
トグル ボタンのリストを作り、一度にアクティブにできるのは1つだけにすることがよくあります。これはラジアル セットまたはラジオ ボタンなどとも呼ばれます。
```

2019-11-10 05:42 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +この機能を有効にするには、[`InteractableToggleCollection`](xref:Microsoft.MixedReality.Toolkit.UI.InteractableToggleCollection) コンポーネントを使用します。このコントロールにより、常に1つの *Interactable* のみがオンになります。 [*RadialSet* prefab](http
```suggestion
この機能を有効にするには、[`InteractableToggleCollection`](xref:Microsoft.MixedReality.Toolkit.UI.InteractableToggleCollection) コンポーネントを使用します。このコントロールにより、常に1つの *Interactable* のみがオンになります。[*RadialSet* prefab](https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/RadialSet.prefab) も、すぐに使える素晴らしい出発点です。
```

2019-11-10 05:45 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +1) 複数の *Interactable* GameObjects/ボタンの作成
```suggestion
1) 複数の *Interactable* GameObjects/ボタンを作成します。
```

2019-11-10 05:46 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +1) *SelectionMode* = Toggle、*CanSelect* = true、および、*CanDeselect* = false を指定して、それぞれ *Interactable* を設定します。
```suggestion
1) それぞれの *Interactable* を *SelectionMode* = Toggle、*CanSelect* = true、および、*CanDeselect* = false に設定します。
```

2019-11-10 05:51 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +Multi-Dimension 選択モードは、連続したボタンや、速い(1倍)、やや速い(2倍)、最も速い(3倍) という3つの値で速度をコントロールするような、3つ以上のステップを持つボタンを作成するために使用します。
```suggestion
Multi-Dimension 選択モードは、連続的なボタンや、速い(1倍)、やや速い(2倍)、最も速い(3倍) という3つの値で速度をコントロールするといったような、3つ以上のステップを持つボタンを作成するために使用します。
```

2019-11-10 05:54 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +Dimensions が数値の場合、最大9つのテーマを追加して、各速度設定のボタンのテキストラベルまたはテクスチャを制御できます。各ステップに異なるテーマを使用します。
```suggestion
Dimensions が数値の場合、最大9つのテーマを追加して、それぞれの速度設定のボタンのテキスト ラベルまたはテクスチャを制御できます。各ステップには異なるテーマを使用します。
```

2019-11-10 05:57 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +すべてのクリックイベントは、実行時に `DimensionIndex` の値になるまで `Dimensions` の値を 1 づつ進め、その後、数値は 0 にリセットされ、また 1 づつ加算されるサイクルとなります。
```suggestion
すべてのクリックイベントは実行時に `DimensionIndex` の値を 1 ずつ進め、`Dimensions` の値に到達すると、このサイクルは 0 にリセットされます。
```

2019-11-10 06:01 UTC, hatsunea commented on Documentation.ja/README_Interactable.md
> +* **Toggle** - *Dimensions* = 2 の場合、*Interactable* は *on*/*off* 状態を交互に切り替えます
1の場合、２の場合、３以上の場合、の３つの列挙かなーと

2019-11-10 06:01 UTC, tarukosu reviewed
269 行目まで見ました

2019-11-10 06:04 UTC, hatsunea commented on Documentation.ja/README_Interactable.md
>  **IsGlobal**
IsGlobalは、英語というよりプロパティ名みたいなものなので訳さないほうがよいかと

2019-11-10 06:05 UTC, hatsunea commented on Documentation.ja/README_Interactable.md
> +* [Speech (音声 コマンド)](./Input/Speech.md)
Commands でしょうか？

2019-11-10 06:24 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* **Toggle** - *Dimensions* = 2 の場合、*Interactable* は *on*/*off* 状態を交互に切り替えます
1の場合、ボタン
2の場合、トグル

という書き方なら場合でしっくりくるんですが、

ボタン *Dimensions* = 1
トグル *Dimensions* = 2

という書き方なので場合がないほうが自分はわかりやすいです

2019-11-10 06:26 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* [Speech (音声 コマンド)](./Input/Speech.md)
原文が Speech Commands なので、Speech Commands がいいかと思います。

2019-11-10 06:29 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +* [Speech (音声 コマンド)](./Input/Speech.md)
リンク表示の文字列と、リンク先のタイトルが一致していないこともありますが、
原文を尊重して「リンク表示の文字列の翻訳」で統一しています。

2019-11-10 06:31 UTC, hatsunea commented on Documentation.ja/README_Interactable.md
> +* **Toggle** - *Dimensions* = 2 の場合、*Interactable* は *on*/*off* 状態を交互に切り替えます
では、= 1のところもサジェスチョンしてもらえるとー

2019-11-10 07:47 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
>  **IsGlobal**
他の項目（Speech Command とか）も訳さないほうが良いということですか？

訳したほうがわかりやすいと思いました

2019-11-10 07:53 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +    HideUnityEvents = true; // 受信側の Unity イベントを非表示にします
```suggestion
    HideUnityEvents = true; // レシーバーの Unity イベントを非表示にします。コードのみであると意味します。
```

2019-11-10 07:54 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
>      // voice command called, perform some action
```suggestion
    // 音声 コマンドが呼ばれたので、なにかアクションを実行する
```

2019-11-10 07:56 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +// 選択モード = トグルを使用する場合 (例 Dimensions == 2)
```suggestion
// SelectionMode = Toggle (すなわち Dimensions == 2) を使用する場合
```

2019-11-10 07:57 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +// 選択モード = Multi-dimension 選択モードを使用する場合 (例 Dimensions >= 3)
```suggestion
// SelectionMode = Multi-dimension (すなわち Dimensions >= 3) を使用する場合 
```

2019-11-10 07:58 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +// テーマ エンジンの InteractableColorTheme の既定の構成を取得する
```suggestion
// テーマ エンジン InteractableColorTheme のデフォルトの設定を取得する
```

2019-11-10 07:59 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +// 既定の Interactable ステート カラーを定義する
```suggestion
// デフォルトの Interactable ステートでのすべてのステートのカラーを定義する
```

2019-11-10 08:00 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +    // トグル機能を持つ interactable をコードで作成する
```suggestion
    // コードで interactable にトグル機能を持たせる
```

2019-11-10 08:01 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +    // GUI エディターよりもはるかに簡単
```suggestion
    // GUI エディターでは、はるかに簡単
```

2019-11-10 08:04 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +### 実行時に Interactable を作成
```suggestion
### 実行時に Interactable を作成する
```

2019-11-10 08:04 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +*Interactable* は、実行時に任意のGameObjectに簡単に追加できます。以下に [ビジュアル テーマ](visualthemes.md) を使用してプロファイルを割り当てる例を示します。
```suggestion
*Interactable* は、実行時に任意の GameObject に簡単に追加できます。以下に [ビジュアル テーマ](visualthemes.md) を使用してプロファイルを割り当てる例を示します。
```

2019-11-10 08:08 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +### コードを使用した Interactable なイベント
```suggestion
### コードを使用した Interactable イベント
```

2019-11-10 08:10 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +次の例のようなコードを使用して、ベース [`Interactable.OnClick`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.OnClick) イベントにアクションを追加できます。
```suggestion
次の例のようなコードを使用して、ベースとなる [`Interactable.OnClick`](xref:Microsoft.MixedReality.Toolkit.UI.Interactable.OnClick) イベントにアクションを追加できます。
```

2019-11-10 08:15 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +以下のサンプル・コードは、フォーカスの開始/終了をリッスンする [InteractableOnFocusReceiver](xref:Microsoft.MixedReality.Toolkit.UI.InteractableOnFocusReceiver) を追加する方法、さらにイベント インスタンスが起動したときに実行するアクション コードを定義する方法を示しています。
```suggestion
以下のサンプル コードは、フォーカスの開始/終了をリッスンする [InteractableOnFocusReceiver](xref:Microsoft.MixedReality.Toolkit.UI.InteractableOnFocusReceiver) を追加する方法、さらにイベント インスタンスが発火したときに実行するアクション コードを定義する方法を示しています。
```

2019-11-10 08:23 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +以下のサンプル コードは、[InteractableOnToggleReceiver](xref:Microsoft.MixedReality.Toolkit.UI.InteractableOnFocusReceiver) を追加する方法を示しています。これは、切り替え可能な *Interactables* 上の選択/選択解除された状態遷移をリッスンし、さらに、イベント インスタンスが発生したと
```suggestion
以下のサンプル コードは、トグル可能な *Interactables* の選択/選択解除のステート遷移をリッスンする [InteractableOnToggleReceiver](xref:Microsoft.MixedReality.Toolkit.UI.InteractableOnFocusReceiver) を追加する方法、さらにイベント インスタンスが発火したときに実行するアクション コードを定義する方法を示しています。
```

2019-11-10 08:24 UTC, tarukosu commented on Documentation.ja/README_Interactable.md
> +以下のサンプル コードは、[InteractableOnToggleReceiver](xref:Microsoft.MixedReality.Toolkit.UI.InteractableOnFocusReceiver) を追加する方法を示しています。これは、切り替え可能な *Interactables* 上の選択/選択解除された状態遷移をリッスンし、さらに、イベント インスタンスが発生したと
一つ前の書き方に合わせました

2019-11-10 08:25 UTC, tarukosu reviewed
最後まで見終わりました！

2019-11-10 09:03 UTC, hatsunea commented
レビュー結果の反映完了

2019-11-10 12:43 UTC, merged