Input/speech.mdの翻訳
HoloLabInc/MixedRealityToolkit-Unity pull request #82
Opened 2019-10-29 15:20 UTC by torikasyu

## Overview
Input/speech.mdの翻訳

## Changes
- Fixes: # .

## Verification
> This optional section is a place where you can detail the specific type of verification 
> you want from reviewers. For example, if you want reviewers to checkout the PR locally
> and validate the functionality of specific scenarios, provide instructions
> on the specific scenarios and what you want verified.
>
> If there are specific areas of concern or question feel free to highlight them here so
> that reviewers can watch out for those issues.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

2019-10-29 21:57 UTC, hatsunea commented on Documentation.ja/Input/Speech.md
> +# 音声
# Speech (音声)

2019-10-29 21:57 UTC, hatsunea commented on Documentation.ja/Input/Speech.md
> +別の方法として、開発者はカスタムスクリプトコンポーネントに [`IMixedRealitySpeechHandler`](xref:Microsoft.MixedReality.Toolkit.Input.IMixedRealitySpeechHandler) インターフェイスを実装することにより [音声入力イベントを扱う](InputEvents.md#input-event-interfac
別の方法として、開発者はカスタム スクリプト コンポーネントに [`IMixedRealitySpeechHandler`](xref:Microsoft.MixedReality.Toolkit.Input.IMixedRealitySpeechHandler) インターフェイスを実装することにより [音声入力イベントを扱う](InputEvents.md#input-event-interface-example) ことができます。

2019-11-11 08:19 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +*Windows Speech Input* などの音声入力プロバイダーは、コントローラーを作成しませんが、代わりに認識時に音声入力イベントを発生させるキーワードを定義することができます。 *Input System Profile* の **Speech Commands Profile** は、認識するキーワードを設定する場所です。各コマンドでは次のこともできます：
```suggestion
*Windows Speech Input* などの音声入力プロバイダーは、コントローラーを作成しませんが、代わりに認識時に音声入力イベントを発生させるキーワードを定義することができます。*Input System Profile* の **Speech Commands Profile** は、認識するキーワードを設定する場所です。各コマンドでは次のこともできます：
```

2019-11-11 08:22 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +- マップする **input action** を選択します。この方法では、たとえば、キーワード *Select* を使用して、同じアクションをマップすることにより、マウスの左クリックと同じ効果を得ることができます。
```suggestion
- マップする **input action** を選択します。この方法では、たとえば、キーワード *Select* を使用して、マウスの左クリックと同じアクションにマップすることにより、クリックと同じ効果を得ることができます。
```

2019-11-11 08:23 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +- UWPアプリで使用される **localization key** を追加して、アプリのリソースからローカライズされたキーワードを取得します。
```suggestion
- UWP アプリで使用される **localization key** を追加して、アプリのリソースからローカライズされたキーワードを取得します。
```

2019-11-11 09:58 UTC, tarukosu requested changes
コメントしました

2019-11-11 09:58 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +[**`Speech Input Handler`**](xref:Microsoft.MixedReality.Toolkit.Input.SpeechInputHandler) スクリプトは、音声コマンドを扱うために、[**UnityEvents**](https://docs.unity3d.com/Manual/UnityEvents.html) を使用してGameObjectに追加する
```suggestion
[**`Speech Input Handler`**](xref:Microsoft.MixedReality.Toolkit.Input.SpeechInputHandler) スクリプトは、[**UnityEvents**](https://docs.unity3d.com/Manual/UnityEvents.html) を使用して音声コマンドを扱うために、GameObject に追加することができます。**Speech Commands Profile** で定義されたキーワードのリストが自動的に表示されます。
```

2019-11-11 09:58 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +オプションの **SpeechConfirmationTooltip.prefab** を割り当てることによって、認識時にアニメーションする確認ツールチップラベルを表示することができます。
```suggestion
オプションの **SpeechConfirmationTooltip.prefab** を割り当てることによって、認識時にアニメーションする確認用ツールチップ ラベルを表示することができます。 
```

2019-11-11 09:58 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +別の方法として、開発者はカスタム スクリプト コンポーネントに [`IMixedRealitySpeechHandler`](xref:Microsoft.MixedReality.Toolkit.Input.IMixedRealitySpeechHandler) インターフェイスを実装することにより [音声入力イベントを扱う](InputEvents.md#input-event-interf
```suggestion
別の方法として、開発者はカスタム スクリプト コンポーネントに [`IMixedRealitySpeechHandler`](xref:Microsoft.MixedReality.Toolkit.Input.IMixedRealitySpeechHandler) インターフェイスを実装することにより、[音声入力イベントを扱う](InputEvents.md#input-event-interface-example)ことができます。
```

2019-11-11 09:58 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +`MixedRealityToolkit.Examples\Demos\Input\Scenes\Speech` の **SpeechInputExample** シーンでは、音声を扱う方法を見ることができます。また、[`IMixedRealitySpeechHandler`](xref:Microsoft.MixedReality.Toolkit.Input.IMixedRealitySpee
```suggestion
`MixedRealityToolkit.Examples\Demos\Input\Scenes\Speech` の **SpeechInputExample** シーンでは、音声を扱う方法を見ることができます。また、[`IMixedRealitySpeechHandler`](xref:Microsoft.MixedReality.Toolkit.Input.IMixedRealitySpeechHandler) を実装することにより、自分のスクリプトで直接音声コマンドを聞き取ることができます([event handlers](InputEvents.md) の表を参照してください)。
```

2019-11-14 04:09 UTC, torikasyu commented on Documentation.ja/Input/Speech.md
> +- マップする **input action** を選択します。この方法では、たとえば、キーワード *Select* を使用して、同じアクションをマップすることにより、マウスの左クリックと同じ効果を得ることができます。
２回目の「クリックと」は冗長な気がします。もしくは、２回目も左をつけるかどちらかではないかと。

マウスの左クリックと同じアクションにマップすることにより、（左クリックと）同じ効果を得ることができます。

2019-11-14 04:37 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +- マップする **input action** を選択します。この方法では、たとえば、キーワード *Select* を使用して、同じアクションをマップすることにより、マウスの左クリックと同じ効果を得ることができます。
左をつけたほうがいいなと思いました。

2019-11-14 04:38 UTC, tarukosu commented on Documentation.ja/Input/Speech.md
> +- マップする **input action** を選択します。この方法では、たとえば、キーワード *Select* を使用して、同じアクションをマップすることにより、マウスの左クリックと同じ効果を得ることができます。
suggestion 変更しました。

2019-11-14 05:09 UTC, tarukosu approved these changes

2019-11-14 05:09 UTC, merged