README_Sliders.mdの翻訳 #83
HoloLabInc/MixedRealityToolkit-Unity pull request #84
Opened 2019-11-04 15:37 UTC by hatsunea

2019-11-08 11:03 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +# Sliders (スライダ)
```suggestion
# Sliders (スライダー)
```

2019-11-08 11:07 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +スライダは、トラック上でスライダを動かして値を連続的に変更できるUIコンポーネントです。現在のところ、Pinch Slider (ピッチ スライダ) は、直接または一定の距離でスライダをつかんで移動できます。スライダは、モーション コントローラ、ハンド、または、ジェスチャ+音声を使用して、AR および VR で動作します。
```suggestion
スライダーは、トラック上でスライダーを動かして、値を連続的に変更できる UI コンポーネントです。現在のところ、Pinch Slider (ピッチ スライダー) は、直接または少し離れた位置でスライダーをつかんで移動できます。スライダーは、モーション コントローラー、ハンド、または、ジェスチャ+音声を使用して、AR および VR で動作します。
```

2019-11-08 11:11 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +**SliderExample** シーンの以下の場所にサンプルがあります。:
```suggestion
以下の場所の **SliderExample** シーンにサンプルがあります:
```

2019-11-08 11:16 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +**PinchSlider** プレハブをシーン ヒエラルキにドラッグ＆ドロップします。独自のスライダを変更または作成する場合は、次の操作を行います:
```suggestion
**PinchSlider** プレハブをシーン ヒエラルキーにドラッグ＆ドロップします。独自のスライダを変更または作成する場合は、次の操作を行います:
```

2019-11-08 11:35 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +- thumb オブジェクトにコライダがあることを確認します。PinchSlider プレハブでは、コライダは `SliderThumb/Button_AnimationContainer/Slider_Button` にあります。
```suggestion
- thumb オブジェクトにコライダーがあることを確認します。PinchSlider プレハブでは、コライダーは `SliderThumb/Button_AnimationContainer/Slider_Button` にあります。
```

2019-11-08 11:38 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +- スライダを近くでつかみたい場合は、コライダを含むオブジェクトにも Near Interaction Grabbable (握ることが可能な近接相互作用) コンポーネントがあることを確認します。
```suggestion
- スライダーを近くでつかみたい場合は、コライダーを含むオブジェクトが Near Interaction Grabbable コンポーネントも持っていることを確認します。
```

2019-11-08 11:38 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +また、次のヒエラルキを使用することをお勧めします
```suggestion
また、次のヒエラルキーを使用することをお勧めします
```

2019-11-08 11:39 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +- PinchSlider - sliderComponent が含まれます
```suggestion
- PinchSlider - sliderComponent を含みます
```

2019-11-08 11:51 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +## スライダ イベント
```suggestion
## スライダー イベント
```

2019-11-08 11:52 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +スライダは次のイベントを公開します:
```suggestion
スライダーは次のイベントを公開します:
```

2019-11-08 11:52 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +- OnValueUpdated - スライダの値が変更されるたびに呼び出されます
```suggestion
- OnValueUpdated - スライダーの値が変更されるたびに呼び出されます
```

2019-11-08 11:53 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +- OnInteractionStarted - ユーザがスライダをつかんだときに呼び出されます
```suggestion
- OnInteractionStarted - ユーザーがスライダーをつかんだときに呼び出されます
```

2019-11-08 11:53 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +- OnInteractionEnded - ーザがスライダを離したときに呼び出されます
```suggestion
- OnInteractionEnded - ユーザーがスライダーを離したときに呼び出されます
```

2019-11-08 11:56 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +- OnHoverEntered - ユーザのハンドまたはコントローラが、近くまたは遠くのインタラクションを使用してスライダの上に移動したときに呼び出されます
```suggestion
- OnHoverEntered - ユーザーのハンドまたはコントローラーが、ニアまたはファー インタラクションを使用してスライダーの上に移動したときに呼び出されます
```

2019-11-08 11:57 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +- OnHoverExited - ユーザのハンドまたはコントローラが、スライダの近くにない場合に呼び出されます。
```suggestion
- OnHoverExited - ユーザーのハンドまたはコントローラーが、スライダーの近くから離れたときに呼び出されます。
```

2019-11-08 11:58 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +_Slider Axis_ フィールドを使用してスライダの軸 (ローカル空間) を指定することもできます。
```suggestion
_Slider Axis_ フィールドを使用してスライダの軸 (ローカル空間における) を指定することもできます。
```

2019-11-08 12:02 UTC, tarukosu commented on Documentation.ja/README_Sliders.md
> +ハンドルを使用できない場合は、 _Slider Start Distance_ フィールドと _Slider End Distance_ フィールドを使用して、スライダの開始点と終了点を指定できます。スライダの開始 / 終了位置を、スライダの中心からの距離としてローカル座標で指定します。つまり、スライダの開始距離と終了距離を必要に応じて設定すると、開始距離と終了距離を更新しなくても、スライダを拡
```suggestion
ハンドルを使用できない場合は、代わりに _Slider Start Distance_ フィールドと _Slider End Distance_ フィールドを使用して、スライダーの開始点と終了点を指定できます。スライダの開始 / 終了位置を、スライダの中心からの距離としてローカル座標で指定します。つまり、スライダーの開始距離と終了距離を必要に応じて設定すると、開始距離と終了距離を更新しなくても、スライダーを縮小または拡大できます。
```

2019-11-08 12:02 UTC, tarukosu requested changes
コメントしました

2019-11-09 13:06 UTC, hatsunea commented
レビューの確認完了

2019-11-09 13:35 UTC, tarukosu approved these changes

2019-11-09 13:35 UTC, merged