hologram-stabilization.md の翻訳 #85
HoloLabInc/MixedRealityToolkit-Unity pull request #86
Opened 2019-11-04 21:44 UTC by hatsunea

2019-11-05 00:06 UTC, decoc requested changes
1/3みました

2019-11-05 00:06 UTC, decoc commented on Documentation.ja/hologram-stabilization.md
> +## 環境の管理
環境のトラッキング

2019-11-05 00:06 UTC, decoc commented on Documentation.ja/hologram-stabilization.md
> +安定なホログラフィック レンダリングは、プラットフォームとデバイスによるヘッド ポーズ トラッキングに大きく依存します。Unity は、基礎となるプラットフォームによって推定および提供されるカメラ ポーズからのフレームごとにシーンをレンダリングします。このトラッキングが実際のヘッドの動きに正確に追従しない場合、ホログラムは視覚的に不正確に見えます。HoloLens のような AR デバイスでは、
安定したホログラフィック レンダリング

2019-11-05 00:06 UTC, decoc commented on Documentation.ja/hologram-stabilization.md
> +安定なホログラフィック レンダリングは、プラットフォームとデバイスによるヘッド ポーズ トラッキングに大きく依存します。Unity は、基礎となるプラットフォームによって推定および提供されるカメラ ポーズからのフレームごとにシーンをレンダリングします。このトラッキングが実際のヘッドの動きに正確に追従しない場合、ホログラムは視覚的に不正確に見えます。HoloLens のような AR デバイスでは、
ヘッドポーズ　はハイフンなので繋げる

2019-11-05 00:06 UTC, decoc commented on Documentation.ja/hologram-stabilization.md
> +安定なホログラフィック レンダリングは、プラットフォームとデバイスによるヘッド ポーズ トラッキングに大きく依存します。Unity は、基礎となるプラットフォームによって推定および提供されるカメラ ポーズからのフレームごとにシーンをレンダリングします。このトラッキングが実際のヘッドの動きに正確に追従しない場合、ホログラムは視覚的に不正確に見えます。HoloLens のような AR デバイスでは、
プラットフォームとデバイスによって　の方がわかりやすいです

2019-11-05 00:06 UTC, tattichan commented on Documentation.ja/hologram-stabilization.md
> +安定なホログラフィック レンダリングは、プラットフォームとデバイスによるヘッド ポーズ トラッキングに大きく依存します。Unity は、基礎となるプラットフォームによって推定および提供されるカメラ ポーズからのフレームごとにシーンをレンダリングします。このトラッキングが実際のヘッドの動きに正確に追従しない場合、ホログラムは視覚的に不正確に見えます。HoloLens のような AR デバイスでは、
Unity は、基礎となるプラットフォームによって推定、提供されるカメラ ポーズから、シーンを毎フレームレンダリング します。

2019-11-05 00:06 UTC, tattichan commented on Documentation.ja/hologram-stabilization.md
> +安定なホログラフィック レンダリングは、プラットフォームとデバイスによるヘッド ポーズ トラッキングに大きく依存します。Unity は、基礎となるプラットフォームによって推定および提供されるカメラ ポーズからのフレームごとにシーンをレンダリングします。このトラッキングが実際のヘッドの動きに正確に追従しない場合、ホログラムは視覚的に不正確に見えます。HoloLens のような AR デバイスでは、
仮想　→ バーチャル

2019-11-05 00:06 UTC, tattichan commented on Documentation.ja/hologram-stabilization.md
> +### Depth バッファの共有
Depth Buffer Sharing (深度バッファの共有)
この用語はUnityでそのまま使われているため

2019-11-12 13:26 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +## 環境の管理
```suggestion
## 環境トラッキング
```

2019-11-12 13:26 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +安定したホログラフィック レンダリングは、プラットフォームとデバイスによるヘッドポーズ トラッキングに大きく依存します。Unity は、基礎となるプラットフォームによって推定および提供されるカメラ ポーズから、シーンをフレームごとにレンダリングします。このトラッキングが実際のヘッドの動きに正確に追従しない場合、ホログラムは視覚的に不正確に見えます。HoloLens のような AR デバイスでは、
```suggestion
安定したホログラフィック レンダリングは、プラットフォームとデバイスによるヘッドポーズ トラッキングに大きく依存します。Unity は、基礎となるプラットフォームによって推定および提供されるカメラ ポーズから、シーンをフレームごとにレンダリングします。このトラッキングが実際のヘッドの動きに正確に追従しない場合、ホログラムは視覚的に不正確に見えます。HoloLens のような AR デバイスでは、ユーザーがバーチャル ホログラムを現実世界に関連付けることができるため、これは特に明白で重要です。パフォーマンスは信頼性の高いヘッド トラッキングに重要ですが、[そのほかにも重要な特徴](https://docs.microsoft.com/ja-jp/hololens/hololens-environment-considerations) があります。ユーザ エクスペリエンスに影響を与える環境要素のタイプは、対象となるプラットフォームの仕様によって異なります。
```

2019-11-12 13:26 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +Windows Mixed Realityプラットフォームは、プラットフォーム上でホログラムを安定させるための [ホログラムの安定性](https://docs.microsoft.com/ja-jp/windows/mixed-reality/hologram-stability) を提供します。開発者がホログラムの視覚体験を改善するために利用できる主要なツールはいくつかあります。
```suggestion
Windows Mixed Reality プラットフォームは、プラットフォーム上でホログラムを安定させるための[参考資料](https://docs.microsoft.com/ja-jp/windows/mixed-reality/hologram-stability)を提供しています。開発者がホログラムの視覚体験を改善するために利用できる主要なツールはいくつかあります。
```

2019-11-14 11:16 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +### Depth Buffer Sharing (深度バッファの共有)
```suggestion
### Depth Buffer Sharing (デプス バッファーの共有)
```

2019-11-14 11:16 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +### Depth Buffer Sharing (深度バッファの共有)
Unity マニュアルではデプスバッファ、
Microsoft ドキュメントでは 深度バッファーとなっていたので、
デプス バッファーに統一しました。

2019-11-14 11:16 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +Unity の開発者はアプリケーションの Depth バッファをプラットフォームと共有することができます。これは、現在のフレームに対してホログラムが存在する場合に、プラットフォームが Late-Stage Reprojection として知られるハードウェアで支援されたプロセスを介してホログラムを安定化するために利用できる情報を提供します。
```suggestion
Unity の開発者はアプリケーションのデプス バッファーをプラットフォームと共有することができます。これは、現在のフレームに対してホログラムが存在する場合に、プラットフォームが Late-Stage Reprojection として知られるハードウェアで支援されたプロセスを介してホログラムを安定化するために利用できる情報を提供します。
```

2019-11-14 11:16 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +フレームのレンダリングが終了すると、Windows Mixed Reality プラットフォームは、アプリケーションによって生成されたカラーと depth のレンダ ターゲットを使用して最終的な画面出力を変換し、最後のヘッド ポーズ予測以降のわずかなヘッドの動きを考慮します。アプリケーションのゲーム ループの実行には時間がかかります。たとえば、60 FPS の場合、これはアプリケーションがフレー
```suggestion
フレームのレンダリングが終了すると、Windows Mixed Reality プラットフォームは、アプリケーションによって生成されたカラーとデプスのレンダー ターゲットを使用し、最後のヘッド ポーズ予測以降のわずかなヘッドの動きを考慮するために最終的な画面出力を変換します。アプリケーションのゲーム ループの実行には時間がかかります。たとえば、60 FPS の場合、これはアプリケーションがフレームをレンダリングするのに 16.667 ms 以下の時間がかかることを意味します。これは非常に短い時間のように思えるかもしれませんが、ユーザーの頭の位置と向きが変わり、結果的にレンダリング時のカメラのプロジェクション マトリックスが新しくなります。Late-Stage Reprojection では、この新しいパースペクティブを考慮して最終的な画像のピクセルを変換します。
```

2019-11-14 11:30 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +Windows Mixed Reality デバイス上で実行されるデバイスエンドポイントと OS のバージョンに応じて、Late-Stage Reprojection アルゴリズムはピクセル単位または [安定化平面]　(https://docs.microsoft.com/ja-jp/windows/mixed-reality/hologram-stability#stabilization-p
```suggestion
Windows Mixed Reality デバイス上で動作するデバイス エンドポイントと OS のバージョンに応じて、Late-Stage Reprojection アルゴリズムはピクセル単位または [安定化平面]　(https://docs.microsoft.com/ja-jp/windows/mixed-reality/hologram-stability#stabilization-plane) を介して実行されます。
```

2019-11-16 00:19 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +##### ピクセル単位の depth-based
```suggestion
##### ピクセルごとのデプス ベース
```

2019-11-16 00:45 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +画素毎の深さに基づく reprojection は、depth バッファを利用して画素毎の画像出力を修正し、従って様々な距離でホログラムを安定化することを含みます。例えば、1 m 離れた球が 10 m 離れた柱の前にあるとします。ユーザがヘッドにわずかなタイトルを付けた場合、球を表すピクセルは、柱を表す遠くのピクセルとは異なる変換を持ちます。ピクセル単位の再投影では、より正確な再投影のために、各
```suggestion
ピクセルごとのデプスに基づいた Reprojection (再投影) は、デプス バッファーを利用してピクセルごとの画像出力を修正し、従って様々な距離でホログラムを安定化することに関与します。例えば、1 m 離れた球が 10 m 離れた柱の前にあるとします。ユーザーが頭を少し傾けた場合、球を表すピクセルは、柱を表す遠くのピクセルとは異なる変換を持ちます。ピクセルごとの再投影では、より正確な再投影のために、各ピクセルでのこの距離差が考慮されます。
```

2019-11-16 00:45 UTC, tarukosu reviewed
29行目まで見ました

2019-11-16 12:44 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +プラットフォームと共有する正確な depth バッファを作成できない場合、別の形式の LSR は安定化平面を使用します。シーン内のすべてのホログラムにはある程度の安定化が適用されますが、目的の平面にあるホログラムには最大のハードウェア安定化が適用されます。平面の点と法線は、*HolographicSettings.SetFocusPointForFrame* [Unity のフォーカスポイント]
```suggestion
プラットフォームと共有する正確なデプス バッファーを作成できない場合、別の形式の LSR は安定化平面を使用します。シーン内のすべてのホログラムにはある程度の安定化が適用されますが、目的の平面にあるホログラムには最大のハードウェア安定化が適用されます。平面の点と法線は、[Unity で提供される API の](https://docs.microsoft.com/ja-jp/windows/mixed-reality/focus-point-in-unity)  *HolographicSettings.SetFocusPointForFrame* を介してプラットフォームに提供されます。
```

2019-11-16 12:45 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +#### Depth バッファ フォーマット
```suggestion
#### デプス バッファー フォーマット
```

2019-11-16 12:48 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +HoloLens を開発に使用する場合は、24 ビットよりも 16 ビット depth バッファ フォーマットを使用することを強くお勧めします。これにより、depth 値の精度は低くなりますが、パフォーマンスが大幅に向上します。精度の低さを補正して [z-fighting](https://en.wikipedia.org/wiki/Z-fighting) を回避するには、Unity で設定され
```suggestion
HoloLens を開発のターゲットとする場合は、24 ビットよりも 16 ビット デプス バッファー フォーマットを使用することを強くお勧めします。これにより、デプス値の精度は低くなりますが、パフォーマンスが大幅に向上します。精度の低さを補い [z-fighting](https://en.wikipedia.org/wiki/Z-fighting) を回避するには、[far clip plane](https://docs.unity3d.com/Manual/class-Camera.html) の値を Unity で設定されているデフォルト値の 1000m から減らすことをお勧めします。 
```

2019-11-16 12:49 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +#### Unity での Depth Buffer Sharing
```suggestion
#### Unity での Depth Buffer Sharing (デプス バッファー シェアリング)
```

2019-11-16 12:50 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +depth ベース LSR を利用するために、開発者が取る必要のある2つの重要なステップがあります。
```suggestion
デプス ベースの LSR を利用するために、開発者が取る必要のある2つの重要なステップがあります。
```

2019-11-16 12:51 UTC, tarukosu reviewed
41 行目まで

2019-11-17 00:10 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +1. **Edit** > **Project Settings** > **Player** > **XR Settings** > **Virtual Reality SDKs** > Enable **Depth Buffer Sharing** 配下
```suggestion
1. **Edit** > **Project Settings** > **Player** > **XR Settings** > **Virtual Reality SDKs** 配下の **Depth Buffer Sharing** を有効にします。
```

2019-11-17 00:11 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +    1. HoloLens ターゲットする場合は、**16-bit depth format** も選択することをお勧めします
```suggestion
    1. HoloLens をターゲットとする場合は、**16-bit depth format** も選択することをお勧めします。
```

2019-11-17 00:14 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +1. 画面上でカラーをレンダリングする場合は、レンダリング深度も同様にレンダリングします。
```suggestion
1. 画面上でカラーをレンダリングする場合は、デプスも同様にレンダリングします。
```

2019-11-17 00:28 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +Unity の [Opaque GameObjects](https://docs.unity3d.com/Manual/StandardShaderMaterialParameterRenderingMode.html) は、depth を自動的に書き込みます。ただし、透明およびテキスト オブジェクトは、通常、規定では depth 方向に書き込まれません。MRTK 標準シェーダ、または、Tex
```suggestion
一般に、Unity の [Opaque GameObjects](https://docs.unity3d.com/Manual/StandardShaderMaterialParameterRenderingMode.html) は、デプスに自動的に書き込みます。ただし、透明およびテキスト オブジェクトは、通常、デフォルトではデプスに書き込みません。MRTK Standard Shader、または、Text Mesh Pro を使用している場合は、簡単に修正できます。
```

2019-11-17 00:29 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +##### Transparent MRTK 標準 シェーダ
```suggestion
##### Transparent MRTK Standard Shader
```

2019-11-17 00:31 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +[MRTK Standard shader](README_MRTKStandardShader.md) を使用した透明なマテリアルの場合は、マテリアルを選択して *Inspector* ウィンドウに表示します。次に、*Fix Now* ボタンをクリックして、マテリアルを書き込み深さ (例： Z-Write On) に変換します。
```suggestion
[MRTK Standard shader](README_MRTKStandardShader.md) を使用した透明なマテリアルの場合は、マテリアルを選択して *Inspector* ウィンドウに表示します。次に、*Fix Now* ボタンをクリックして、マテリアルをデプスに書き込むように (すなわち、Z-Write On) に変更します。
```

2019-11-17 00:31 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +変換前
```suggestion
変更前
```

2019-11-17 00:32 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +変換後
```suggestion
変更後
```

2019-11-17 00:33 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +Text Mesh Pro オブジェクトの場合は、TMP GameObject を選択してインスペクタに表示します。マテリアル コンポーネントの下で、割り当てられたマテリアルのシェーダを切り替えて MRTK TextMeshPro シェーダを使用します。
```suggestion
Text Mesh Pro オブジェクトの場合は、TMP GameObject を選択してインスペクターに表示します。マテリアル コンポーネントの下で、割り当てられたマテリアルのシェーダーを MRTK TextMeshPro シェーダーを使用するように切り替えます。
```

2019-11-17 00:35 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +- [Unity 座標系](https://docs.microsoft.com/ja-jp/windows/mixed-reality/coordinate-systems-in-unity)
```suggestion
- [Unity での座標系](https://docs.microsoft.com/ja-jp/windows/mixed-reality/coordinate-systems-in-unity)
```

2019-11-17 00:36 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +- [Mixed Reality のパフォーマンスに関する推奨事項](https://docs.microsoft.com/ja-jp/windows/mixed-reality/understanding-performance-for-mixed-reality)
```suggestion
- [Mixed Reality のパフォーマンスについて](https://docs.microsoft.com/ja-jp/windows/mixed-reality/understanding-performance-for-mixed-reality)
```

2019-11-17 00:36 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +- [Mixed Reality のパフォーマンスに関する推奨事項](https://docs.microsoft.com/ja-jp/windows/mixed-reality/understanding-performance-for-mixed-reality)
リンク先ページの翻訳に合わせました

2019-11-17 00:37 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +##### カスタム シェーダ
```suggestion
##### カスタム シェーダー
```

2019-11-17 00:43 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +カスタムシェーダを記述する場合は、[ZWrite flag](https://docs.unity3d.com/Manual/SL-CullAndDepth.html) を *Pass* ブロック定義の一番上に追加し、シェーダが depth バッファに書き込むように設定します。
```suggestion
カスタムシェーダーを記述する場合は、[ZWrite flag](https://docs.unity3d.com/Manual/SL-CullAndDepth.html) を *Pass* ブロック定義の一番上に追加し、シェーダーがデプス バッファーに書き込むように設定します。
```

2019-11-17 00:49 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +上記のメソッドが特定のシナリオで機能しない場合 (例： Unity UI を使用時) 、別のオブジェクトを depth バッファに書き込むことができます。一般的な例として、シーン内のフローティング パネルで Unity UI テキストを使用する場合があります。パネルを不透明にするか、少なくとも depth 方向に書き込むことによって、テキストとパネルの両方の z 値が互いに非常に近くなるため、プ
```suggestion
上記のメソッドが特定のシナリオ（すなわち、Unity UI 使用時）で機能しない場合、別のオブジェクトにデプス バッファーに書き込ませることができます。一般的な例として、シーン内のフローティング パネルで Unity UI テキストを使用する場合があります。パネルを不透明にするか、少なくともデプスに書き込むことによって、テキストとパネルの両方の Z 値が互いに非常に近くなるため、プラットフォームによってそれらが安定化されます。
```

2019-11-17 01:05 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +視覚的な安定性を確保するために正しい構成を確実にするとともに、ホログラムが正しい物理的位置で安定していることを確実にすることが重要です。物理的なスペースの重要な場所についてプラットフォームに通知するために、開発者はGameObjectsの [WorldAnchors](https://docs.unity3d.com/ScriptReference/XR.WSA.WorldAnchor.html
```suggestion
視覚的な安定性を確保するための正しい設定がなされていることを確実にするとともに、ホログラムが正しい物理的位置で安定することを確実にすることが重要です。物理空間での重要な場所についてプラットフォームに通知するために、開発者はある場所に留まる必要がある GameObjects で  [WorldAnchors](https://docs.unity3d.com/ScriptReference/XR.WSA.WorldAnchor.html) を活用することができます。[WorldAnchors](https://docs.unity3d.com/ScriptReference/XR.WSA.WorldAnchor.html) は、GameObject に追加されるコンポーネントで、オブジェクトの Transform を完全に制御します。
```

2019-11-17 05:11 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +HoloLens のようなデバイスは常に環境をスキャンし、学習しています。そのため、HoloLens が空間での動きと位置を追跡すると、予測値が更新され、 [Unity 座標系](https://docs.microsoft.com/en-us/windows/mixed-reality/coordinate-systems-in-unity) が更新されます。例えば、最初にカメラから 1 m
```suggestion
HoloLens のようなデバイスは常に環境をスキャンし、学習しています。そのため、HoloLens が空間での動きと位置を追跡するにつれて、その予測値は更新され、[Unity 座標系は調整されます](https://docs.microsoft.com/en-us/windows/mixed-reality/coordinate-systems-in-unity)。例えば、最初にカメラから 1 m 離れたところに GameObject を配置した場合、HoloLens が環境を追跡するにつれて、GameObject が配置されている物理的な位置が実際には 1.1 m 離れていることに気づくかもしれません。これにより、ホログラムがドリフトします。GameObject にワールドアンカーを適用すると、アンカーがオブジェクトの Transform を制御できるようになり、オブジェクトが正しい物理的位置に留まります (すなわち、実行時に 1 m ではなく 1.1 m 先へと更新されます)。[WorldAnchors](https://docs.unity3d.com/ScriptReference/XR.WSA.WorldAnchor.html) をアプリのセッション間で維持するために、開発者は [WorldAnchorStore](https://docs.unity3d.com/ScriptReference/XR.WSA.Persistence.WorldAnchorStore.html) を使って [WorldAnchors の保存とロード](https://docs.microsoft.com/ja-jp/windows/mixed-reality/persistence-in-unity) を行えます。
```

2019-11-17 05:13 UTC, tarukosu commented on Documentation.ja/hologram-stabilization.md
> +> いったん WorldAnchor コンポーネントが GameObject に追加されると、その GameObject のトランスフォーム (例： transform.position = x) を変更することはできません。変換を編集するには、WorldAnchor を削除する必要があります。
```suggestion
> いったん WorldAnchor コンポーネントが GameObject に追加されると、その GameObject の Transform を変更する (すなわち、transform.position = x) ことはできません。Transform を編集するには、WorldAnchor を削除する必要があります。
```

2019-11-17 05:14 UTC, tarukosu reviewed
すべて見終わりました！

2019-12-01 15:05 UTC, hatsunea commented
@tarukosu レビュー結果の確認完了

2019-12-02 13:46 UTC, merged