Doc_ja/InputSimurationService.md
HoloLabInc/MixedRealityToolkit-Unity pull request #9
Opened 2019-08-28 05:32 UTC by torikasyu

翻訳してみました。

原文で_Toggle Button_ などアンダースコアで強調されている部分はそのままにしていますが訳した方がいいでしょうか？

2019-08-28 05:41 UTC, tarukosu commented
@torikasyu Pull Request 先は feature/mrtk_documentation_ja でお願いします！

2019-08-28 05:42 UTC, tarukosu requested changes
Pull Request 先のブランチが違っていました！

2019-08-28 05:51 UTC, torikasyu commented
Pull Request先を修正しました

2019-08-28 06:32 UTC, tarukosu reviewed
レビューコメント書きました

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +* HoloLens または VRデバイスのハンドトラッキング
VRの後にスペース
ハンドトラッキング -> ヘッドトラッキング

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +* HoloLens 2 の詳細なハンドトラッキング
多関節ハンドトラッキング　ですかね...
難しい

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +ユーザーは、従来のキーボードやマウスの組み合わせで実行時に操作をシミュレーションすることができます。それにより、デバイスに配布する前にUnity Editor 上でインタラクションをテストすることができます。
自分の担当のところでは、deploy は デプロイにしました。
Unity Editor の前にスペース

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +> これは、Unityの XR Holographic Emulation > Emulation Mode = "Simulate in Editor" では動作しません。Unity Editor 内でのシミュレーションは、MRTK のインプットシミュレーションの制御を奪い取ります。MRTKのインプットシミュレーションサービスを使用するには、XR Holographic Emulationを、
MRTK の後にスペース
Emulation の後にスペース

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +インプットシミュレーションサービスは、ハンドデバイスをサポートします。バーチャルハンドは、ボタンやグラブ可能オブジェクトなどの、ハンドデバイスをサポートしたオブジェクトと対話することができます。
> グラブ可能オブジェクト
グラバブルオブジェクト (Grabbable objects)

ですかね。ほかのドキュメントとも合わせたほうが良さそうです。

---

> ハンドデバイスをサポートしたオブジェクトと対話することができます

通常のハンドデバイスをサポートしたオブジェクトとインタラクションできます

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +   フォーカスは視線ポインタを使ってコントロールします。_Air Tap_ ジェスチャーでボタンと対話します
インタラクションします

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +_Left/Right Hand Manipulation Key_ （デフォルトでは 左Shift/Space がそれぞれ 左手/右手 に対応）を押し続けてそれぞれの手をコントロールします。キーを押し続けている間、手が表示されます。マウスの動きで手を移動できます。
Shift の左にスペース

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +デフォルトでは、シミュレートされた手の関節は完全に静的なものです。実機デバイスでは、ハンドトラッキングの根本として、いくらかのジッターやノイズが発生することに注意してください。
根本ってのが変な感じですね

「ハンドトラッキングに基づいた」とかですかね...

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +   別の方法では、Toggle キー（T/Y）を使って手の on/off を切り替えることもできます
> 方法では

方法としては

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +_Left/Middle/Right Mouse Hand Gesture_ 設定を使用して、各マウスボタンを、手の形が異なるジェスチャーにマップすることができます。
The Default Hand Gesture の文が抜けている

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +4. これで両手で同じオブジェクトをグラブした状態になるので、それぞれの手を動かして両手での操作を行います
> それぞれの手を動かして両手での操作を行います

どちらかの手を動かせば両手操作が行えます。

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +1. [Input Simulation Profile](#enabling-the-input-simulation-service) で、__Hand Simulation Mode__ を _Gestures_ にすることにより、GGVのシミュレーションに切り替えることができます
GGV の後にスペース

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +2. カメラを回転させて、視線カーソルを対話可能なオブジェクトにポイントします（左マウスボタンを使用）
インタラクション可能なオブジェクト

右のマウスボタン

2019-08-28 06:32 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +[Eye tracking simulation](../EyeTracking/EyeTracking_BasicSetup.md#simulating-eye-tracking-in-the-unity-editor) は、[Input Simulation Profile](#enabling-the-input-simulation-service) の __Simulate Eye P
使用すべきではありません

2019-08-28 06:50 UTC, tattichan commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# インプットシミュレーションサービス
```
入力シミュレーションサービス (Input Simulation Service)
```
と書いてある方が分かりやすいですかね

2019-08-28 06:50 UTC, tattichan commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +ユーザーは、従来のキーボードやマウスの組み合わせで実行時に操作をシミュレーションすることができます。それにより、デバイスに配布する前にUnity Editor 上でインタラクションをテストすることができます。
配布する前に[スペース]Unity

2019-08-28 06:50 UTC, tattichan commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +> これは、Unityの XR Holographic Emulation > Emulation Mode = "Simulate in Editor" では動作しません。Unity Editor 内でのシミュレーションは、MRTK のインプットシミュレーションの制御を奪い取ります。MRTKのインプットシミュレーションサービスを使用するには、XR Holographic Emulationを、
Unity[スペース]の

2019-08-28 06:50 UTC, tattichan commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +MRTK では、インプットシミュレーションはデフォルトで有効化されています。
インプットシミュレーション　－＞　入力シミュレーション

2019-08-28 06:50 UTC, tattichan commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# カメラコントロール
元ファイルのヘッダーレベルが間違っていますね…

```
# カメラコントロール -> ## カメラコントロール
```

以下一段ずれる

こういうときどうしますかね(--;;)
直しちゃってもいい気がします

2019-08-28 06:50 UTC, tattichan commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +インプットシミュレーションサービスは、ハンドデバイスをサポートします。バーチャルハンドは、ボタンやグラブ可能オブジェクトなどの、ハンドデバイスをサポートしたオブジェクトと対話することができます。
対話ー＞インタラクション

2019-08-28 08:11 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# カメラコントロール
間違ってはいないんじゃない？

2019-08-28 08:15 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +* HoloLens 2 の詳細なハンドトラッキング
slackのアンケートでも多かった「多関節ハンド」に統一します

2019-08-28 08:23 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +インプットシミュレーションサービスは、ハンドデバイスをサポートします。バーチャルハンドは、ボタンやグラブ可能オブジェクトなどの、ハンドデバイスをサポートしたオブジェクトと対話することができます。
interactable objectは「インタラクタブルオブジェクト」でなく「インタラクション可能オブジェクト」としていたので、いったん「グラブ可能オブジェクト」にしてみます（方針決まったら変えます）

2019-08-28 08:36 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# インプットシミュレーションサービス
そうですね。タイトルのみ（）を付けて、それ以外は入力～にしてみます。

2019-08-28 08:39 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# カメラコントロール
MD025/single-title/single-h1: Multiple top level headings in the same document

の警告が出るので#は複数使ってはいけない決まりでしょうか
階層構造的には間違っていないようですね

2019-08-28 08:58 UTC, tattichan commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# カメラコントロール
マークダウンのフォーマット的にはありだけど、InputSimulationServiceとCameraControlが同じレベルかというと違う気がします🤔
InputSimulationServiceの一機能として、CameraControlが提供されているので本来一段下なんじゃないかなー…と思いますがどうでしょう

2019-08-28 09:14 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# カメラコントロール
言いたいことはよくわかるんだけど、ネストが深くなるのを嫌って # にしたのかなと思いました。
本家に聞いてみないとわからないですね

2019-08-28 09:22 UTC, tattichan commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# カメラコントロール
りょーかいです
ここは一旦、深く議論するのやめましょうか('ω')

2019-08-28 09:58 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# カメラコントロール
ここ以外は修正しました。

due to the underlying hand tracking  ＞ハンドトラッキングの原理的な特性として、は意訳しすぎですかね

2019-08-28 11:10 UTC, tarukosu approved these changes

2019-08-28 11:11 UTC, tarukosu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# 入力シミュレーションサービス(Input Simulation Service)
サービスの後にスペースをいれてください！

2019-08-28 11:12 UTC, tarukosu reviewed
コメントしました

2019-08-28 13:51 UTC, torikasyu commented on Documentation.ja/InputSimulation/InputSimulationService.md
> +# 入力シミュレーションサービス(Input Simulation Service)
いれました！

2019-08-30 06:53 UTC, tattichan commented
コンフリクトしたいた部分を直しておきました @torikasyu

2019-08-30 07:00 UTC, decoc approved these changes

2019-08-30 07:55 UTC, merged